### ISSUE TITLE
[Known issue] Debian Stretch support broken

### ISSUE THREAD

**Issue by jeroenops** [WordOps/WordOps#10]
**Description:** The WordOps installation currently fails on Debian Stretch.
**Status:** Bug, confirmed, working on it

**Tech info:**

`nginx-custom` requires `libssl10`, whereas Stretch only has `libssl11`. To be solved with a migration to `openresty`.

**Comment by VirtuBox** [comment]
Debian 9 support was added with WO v3.9.3
