### ISSUE TITLE
[Feature Request] Elasticsearch add-on

### ISSUE THREAD

**Issue by michacassola** [WordOps/WordOps#100]
It would be nice to have Elasticsearch as an addon with WordOps: 
`wo site create site.tld --wpredis --elasticsearch`

It could also install the plugin "ElasticPress" but it is not necessary.

**Comment by naflan121** [comment]
would love to have this feature, since i see there is a big woocommerce community

**Comment by michacassola** [comment]
Hey guys, i stumbled over Redisearch and a Plugin for it.
It is supposed to be faster...
https://github.com/7kmCo/wp-redisearch
https://oss.redislabs.com/redisearch/Quick_Start/#building_and_running_from_source
