### ISSUE TITLE
[Feature Request] Mautic app configuration

### ISSUE THREAD

**Issue by michacassola** [WordOps/WordOps#101]
Please add Mautic (PHP and MySQL based) to your "Add apps configuration"-List under "To-Do" here: https://github.com/WordOps/WordOps/projects/2

The Command could look like this:
`wo site create site.tld --mautic`

Especially with the remote backup feature this would be killer as it allows one to offer mautic hosting without the fear of losing all the lists and campaigns and so on (there is no native backup functionality).

More infos on mautic:
https://www.mautic.org/download/requirements
https://github.com/mautic/mautic#installation
https://www.mautic.org/tour/
https://wordpress.org/plugins/wp-mautic/

Thank you very much!

**Comment by Bidroiddroid** [comment]
It would be perfect to be able to install mautic with the remote, it would be really killer.

I wait anxiously,

Thanks to all the developers.

**Comment by suporterefacao** [comment]
Ninguém se prontificou a tentar criar essa funcionalidade? Poxa... isso seria maravilhoso. 

No one was willing to try to create this functionality? Wow... that would be wonderful.
