### ISSUE TITLE
Can't Update to WordOps v3.9.6.1

### ISSUE THREAD

**Issue by Endda** [WordOps/WordOps#103]
Just tried doing a wo update command as I saw there was a maintenance release pushed out for WordOps. However, I received the following error when I tried. . .

`root@vultr:~# wo update
Downloading update script        Unable to download file, /var/lib/wo/tmp/woupdate20190723-125717`

**Comment by VirtuBox** [comment]
Hello,
There was a typo error in the update function, so please use the following command as a temporary work-around : 
```bash
wo update --beta
```
Issue has already been fixed
