### ISSUE TITLE
[Feature Request] Alias / Add-on Domains + Cloning

### ISSUE THREAD

**Issue by michacassola** [WordOps/WordOps#106]
For mutlisite networks with different domains and for sites with different domains per language it would be really useful to be able to just specify more domains that are then mentioned in the server block of nginx and resolve to the same site.

The commands could look like:

To add alias:
`wo site create example.com --ssl=le --alias=site1.com,*.site2.com`
`wo site update example.com --alias=site1.com,*.site2.com (should work with multiple update arguments)`

To delete alias:
`wo site update example.com --alias-del=site1.com,*.site2.com`

To list all alias:
`wo site info example.com` Where they will simply be in an extra slot in the output list.
`wo site info example.com --alias` Will print only the alias.

**Comment by VirtuBox** [comment]
Hello @michacassola, 
Thanks for providing command examples in your feature suggestion. 
I have tried to define how to implement this feature in WordOps, but I'm not sure about how to handle few things : 
- letsencrypt certificates : how to deal with `--dns` for multiple domains ? It will be pretty easy to identify wildcard aliases but should WordOps use the same acme challenge for all aliases ? And is it better to use a single certificate for the main domain and aliases or to issue a new certificate per alias
- should WordOps create additional Nginx vhosts for aliases ? (to provide the ability to add custom configuration for each alias)

If someone want to suggest how to handle aliases into the internal SQLite database, that would be helpful because I'm thinking about making some changes in the database structure since the beginning but I haven't be able to define how to proceed.

**Comment by michacassola** [comment]
Thank you very much @VirtuBox !

- I do not know enough about lets encrypt to give an educated answer, I would however find it logical to split the acme challenges the way the user asks for the domains, so for the first challenge for `wo site create example.com --ssl=le --alias=site1.com,*.site2.com` the challenge should be for those two domains. If a domain gets deleted from the vhost the cert would not need to be renewed until the next renewal is necessary and then the domain could be dropped from the certificate. 
If another one gets added though through `wo site update example.com --alias=site3.com` I would suggest requesting an extra certificate for that.
Most improtant of all the way that gives the least problems to you developer to implement and maintain should be chosen.
- Please add the aliases to the same vhost (unless there is an advantage I don't see for having separate ones?)

**Comment by kanet0x** [comment]
Yea! We need the alias feature!

**Comment by dingman** [comment]
I've been doing this manually for some time now and it's very easy to do.

Edit your domain file, /etc/nginx/sites-available/domain.conf

and add whatever domain alias you want to the server_name row.

server_name domain1.com domain2.com domain3.com and it will listen for that domain.

**Comment by michacassola** [comment]
Yes, but I guess it becomes more complicated with Let's Encrypt and thus would make sense as being a functionality built in.

**Comment by dingman** [comment]
a very valid point. Absolutely, I agree it should be included. I was only stating that it's possible to do a work-around for the interim.

**Comment by michacassola** [comment]
The way I do it for now is what I picked up from the EE days. You make a php site where you can also add letsencrypt and then change the location to the one of the other original domain.

**Comment by dingman** [comment]
That makes sense, good solution.

Personally, I don't use LE at all in my cluster. I leverage Cloudflare and an AWS LB for SSL termination.

**Comment by michacassola** [comment]
Let's continue this in offtopic over at chat.wordops.net. :)

**Comment by mr119** [comment]
You could add it as a new domain, and symlink the public htdocs directory to the original domain name's public htdocs, just a workaround though, to preserve the originality.

**Comment by michacassola** [comment]
@mr119 Also sounds like a cool workaround, but changing the domain or being able to add an alias would make a lot of sense for me and I am sure others being built in. 

@VirtuBox and I have already talked about Linux Containers and they are a great way to have lightweight and nearly complete separation of sites (if you don't have network problems that I had/have). I have one container with a base site that has everything already installed and in the future will have all kinds of elements for quick real site wireframing, which then would be cool to just clone (the whole container that is) and then change the domain and then start developing the new site under a new domain. That would be a really really cool thing for me and save me a lot of time and effort.
