### ISSUE TITLE
NameSpace error in wo stack reload

### ISSUE THREAD

**Issue by vikas5914** [WordOps/WordOps#12]
Running `wo stack reload --all` gives this error: `'Namespace' object has no attribute 'php7'`

**Comment by jeroenops** [comment]
You could rerun the installation script - that fixes it - or wait for later today when we release version 3.9.5 - from there on you can use the update functionality as you are used to from EasyEngine :smile:

**Comment by vikas5914** [comment]
@jeroenops  

This was not a big problem for me. I created the issue just for tracking it.

**Comment by VirtuBox** [comment]
Issue fixed with PR https://github.com/WordOps/WordOps/pull/26
