### ISSUE TITLE
wo secure --auth

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#125]
when executing the command "wo secure --auth"
A new password is automatically generated.
It would be better to keep the password set, change only when the user requests it.

**Comment by tdtgit** [comment]
You can use the shorthand `wo secure --auth yournewusername youoldpassword` if you need.

**Comment by juanpvh** [comment]
The intention is not to change but just to verify which login and password.  The problem is that when executing the command it changes the password every time.

**Comment by VirtuBox** [comment]
Hello @juanpvh,
I'm planning to make the following changes in the `wo secure` section : 
- add sub-commands such as `add`, `update`, `remove` to manage multiple credentials
- `update` will provide the ability to update only username or password
