### ISSUE TITLE
Unable to install admin tools

### ISSUE THREAD

**Issue by majiix** [WordOps/WordOps#134]
Hi, When i try to install admin tools for dashboard with this code `sudo wo stack install --admin` i get this error:
`Unable to search /opt/netdata/usr/lib/netdata/conf.d/health_alarm_notify.conf and replace SEND_EMAIL="YES" SEND_EMAIL="NO"`

What is the porblem and how can i solve it?

System Information

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

```
WordOps v3.9.8.7
```

**Comment by VirtuBox** [comment]
Helo @majiix,
a new release has been published (v3.9.8.8) which include a fix for this issue.
Let me know if the issue still exist after you update WordOps.

**Comment by majiix** [comment]
I think it is fixed but another issue is generated:
```
Downloading phpMyAdmin           [Done]
Downloading phpRedisAdmin        [Done]
Downloading Composer             Unable to download file, /var/lib/wo/tmp/composer-install
```

**Comment by majiix** [comment]
I also encountered this one:
`Downloading Composer             module 'urllib' has no attribute 'HTTPError'`

**Comment by majiix** [comment]
I don't know how, but i removed admin stack and installed it again and it is installed correctly. so far it is working fine except the dashboard that i can't open at https://*.*.*.*:22222/

**Comment by VirtuBox** [comment]
Is the port 22222 closed by a firewall ?

**Comment by majiix** [comment]
OK it was due to firewall ports of the vps provider. now i see the main page of dashboard but can't have access or open pages in subdirectories like:

```
https://*.*.*.*:22222/netdata/
https://*.*.*.*:22222/db/pma/
https://*.*.*.*:22222/cache/redis/phpRedisAdmin/
```

and more URLs.
It's just a chrome error: `ERR_CONNECTION_TIMED_OUT`

and also after like 2 minutes i see this error in main page of dashboard:

`net.eth0 : data download failed for url: https://*.*.*.*:22222/netdata/api/v1/data?chart=net.eth0&format=array&points=NaN&group=average>ime=0&options=absolute%7Cjsonwrap%7Cnonzero&after=-480&dimensions=sent`

![Annotation 2019-09-06 012047](https://user-images.githubusercontent.com/6815416/64379734-c4d29780-d044-11e9-8918-0e8a2ac59b1f.jpg)

**Comment by majiix** [comment]
More errors!

![Annotation 2019-09-06 014917](https://user-images.githubusercontent.com/6815416/64381485-8d65ea00-d048-11e9-96ac-5ea0db088478.jpg)

**Comment by majiix** [comment]
Another problem.
If you're going to create vhostonly site you'll get an error:

```
wo site create a.io --wp --vhostonly
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Enter the MySQL database name [**]: 
Enter the MySQL database user name [**]: 
Enter the MySQL database password [**]:
Setting up database             [Done]
Installing plugin nginx-helper, please wait...
Testing Nginx configuration   [OK]
Reloading Nginx               [OK]


  RAN: /usr/bin/git --git-dir=/etc/nginx/.git --work-tree=/etc/nginx status -s

  STDOUT:


  STDERR:
fatal: Unable to read current working directory: No such file or directory
```
