### ISSUE TITLE
how to add ioncube loader 

### ISSUE THREAD

**Issue by FosterG4** [WordOps/WordOps#146]
how to add ioncube loader ?
i trying https://kb.virtubox.net/knowledgebase/install-ioncube-loader-php72-ubuntu-18-04-lts/
not work

**Comment by VirtuBox** [comment]
Hello @FosterG4,
you can try with my bash script : https://github.com/VirtuBox/bash-scripts/tree/master/apps/ioncube
But I'm planning to automate install with WordOps

**Comment by FosterG4** [comment]
i don't know to automate install with WordOps 
i'm just running this command wget -qO wo wops.cc && sudo bash wo
can help me to install ioncube from wordOps command?

**Comment by VirtuBox** [comment]
Please take a look on link I posted previously, you should be able to setup ioncube with this script.
Ioncube integration in WordOps is planned but not available yet

**Comment by AutoCultivo** [comment]
Thanks VirtuBox, works fine, solved me one work. Allways thanks

**Comment by febryanvaldo** [comment]
Thanks for the bash. You are hero...
