### ISSUE TITLE
Add Support for Minio Object Storage

### ISSUE THREAD

**Issue by majiix** [WordOps/WordOps#147]
Hi,
Thank you for all your efforts in making WordOps better and better. Minio is an object storage provider that is open source and Amazon S3 compatible object storage. It has a slightly complicated install and configure process which i think you can make it much better and easier with WordOps.
I hope you give it a try.

https://min.io

**Comment by VirtuBox** [comment]
Hello @majiix,
it's already planned : https://github.com/WordOps/WordOps/projects/2#card-20393869
