### ISSUE TITLE
multi-domain letsencrypt support for wp multisites

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [WordOps/WordOps#149]
Is this working with latest multisite wildcard le addition as well?
If not, could this be added, so multi domains within multisite networks are more easily to be handled?

https://github.com/WordOps/WordOps/issues/16

**Comment by VirtuBox** [comment]
@s-a-s-k-i-a Adding domain aliases support is planned, so it should cover multi domains within mulltisite networks
