### ISSUE TITLE
after EE to WO migration: existing multisite -> site update domain.com --wpsubdom --wprocket

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [WordOps/WordOps#150]
The multisite has WooCommerce and WPRocket active. Never a problem.
After EE to WO migration all seemed fine.
I used following command aftermigration:

site update domain.com --wpsubdom (or --wpsubdomain ..not sure rightnow) --wprocket

But now I got a report that there seems to be an issue regarding WooCommerce Addtocart
server responds with 405 not allowed

Any help? Seems like the nginx rules are not correct somehow

**Comment by s-a-s-k-i-a** [comment]
P.S.: This is happening only to not-logged-in users.
My logged-in admin doesn't see the 405 when adding anything to cart.

**Comment by s-a-s-k-i-a** [comment]
WP Rocket version: 3.3.7
I deactivated WPRocket. Add to cart no longer responding 405

There must be something wrong either in WPRocket or in nginx config. 
I will try a previous Version of WPRocket and see if issue persists

**Comment by s-a-s-k-i-a** [comment]
issue persists.
Maybe try implementing this nginx config https://github.com/SatelliteWP/rocket-nginx with WO

**Comment by cristian-rossi** [comment]
Same here. Might need to $skip_cache on POST requests.

**Comment by cristian-rossi** [comment]
By the way,
common/wprocket-php73.conf mentions this: $cache_uri variable set in /etc/nginx/conf.d/map-wp.conf

But I only found that variable set in conf.d/map-wp-fastcgi-cache.conf

**Comment by VirtuBox** [comment]
> issue persists.
> Maybe try implementing this nginx config https://github.com/SatelliteWP/rocket-nginx with WO

Hello @s-a-s-k-i-a, 
WordOps configuration for WP-Rocket is similar to rocket-nginx, but I do not want to use `if {}` to verify each cache exception.

> Same here. Might need to $skip_cache on POST requests.
It should already bypass cache on POST requests, which are not cached by default with Nginx.




> By the way,
> common/wprocket-php73.conf mentions this: $cache_uri variable set in /etc/nginx/conf.d/map-wp.conf
> 
> But I only found that variable set in conf.d/map-wp-fastcgi-cache.conf

Yes, because it's set globally with the map directive.

**Comment by cristian-rossi** [comment]
> 
> It should already bypass cache on POST requests, which are not cached by default with Nginx.
> 
I see, so if it only happens to not-logged-in-users maybe it's cookie related?
