### ISSUE TITLE
Bug: /etc/nginx/htpasswd-wo not matching passwords after wo secure --auth

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [WordOps/WordOps#152]
After using command 

wo secure --auth

the hashed password set in /etc/nginx/htpasswd-wo does not match the password chosen during wo's command routine.

hashing should use MD5 algorithm :)

I generated an md5 encrypted password manually and modified htpasswd-wo accordingly, restarted nginx, but still wasn't able to get past the httpauth... currently am locked out . *help*

EDIT: did some digging. My server is a migrated ee server. ee used to make use of a htpasswd-ee file located in /etc/nginx/ as well. 
The conf file that nginx uses is /etc/nginc/common/acl.conf
and this file references my old htpasswd-ee file instead of the newly created htpasswd-wo file generated by WO.
So we have two issues in one:
wo generates the password incorrectly in its own htpasswd-wo plus it never makes use of that file, because its not referenced anywhere on my migrated nginx config.

I modified the reference so it reflects correct htpasswd-wo filename., restarted nginx and now I am getting past the httpauth!

issue related to official wo-chat thread: https://chat.wordops.net/channel/general?msg=ZSeuQprAu9o9wwG9y

**Comment by VirtuBox** [comment]
Hello @s-a-s-k-i-a, 
I have found the cause of the issue, the file /etc/nginx/common/acl.conf isn't updated during migration from EasyEngine v3, and the previous file htpasswd-ee is still used by Nginx.
I added the following line to the install script to handle this : 

```bash
sed -i "s/htpasswd-ee/htpasswd-wo/" /etc/nginx/common/acl.conf
```
