### ISSUE TITLE
Easyengine to WordOps migration adding SSL not working. 

### ISSUE THREAD

**Issue by ankitsnlq** [WordOps/WordOps#153]
Hi, 

I have migrated one of server from Easyengine to Wordops. All process went fine except SSL addition to site is not working.I get error site is not pointed. 

Certificate type: Domain + www
Validation mode : Webroot challenge
Unable to install certificate   [..]
Please make sure that your site is pointed to 
same server on which you are running Let's Encrypt Client 
 to allow it to verify the site automatically.

So this not because of site is not pointed to server but I can see no acme.sh present inside /opt folder that's why ssl addition not working. 

System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

- [ ] `wo info`
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (7.2.22-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.9-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

MySQL (10.3.18-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             5
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] `nginx -V`
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-E8oIMT/nginx-1.16.1/debian/modules/ngx_brotli

- [ ] `wo -v`
WordOps v3.9.8.11
Copyright (c) 2019 WordOps.

- [ ] `wp cli info --allow-root`
OS:	Linux 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.9-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/opt
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.3.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
Here the link to provide in your github issue : Could not save metadata

**Comment by NicoJuicy** [comment]
Just a question. Are you sure your domain was changed?

Since:

Please make sure that your site is pointed to
same server on which you are running Let's Encrypt Client
to allow it to verify the site automatically.


Looks to me that Letsencrypt could not verify your server's IP versus the IP with the domain name.

**Comment by ankitsnlq** [comment]
I'm sure domain is pointed because I have upgraded already running server from Easyengine to WO. Since acme.sh script is not present that's why it is failing.

**Comment by VirtuBox** [comment]
Hello @ankitsnlq,
thanks for your report, I found the cause of this issue. I'm going to fix it asap.
As a workaround, here a script to setup acme.sh : https://git.io/JeOHr
