### ISSUE TITLE
Issues migration from EE -v 3 ( latest) to wordops

### ISSUE THREAD

**Issue by NicoJuicy** [WordOps/WordOps#154]
I created a website with --hvvm in the past ( easyengine)
I thought i migrated everything to PHP v7.0 in the stack a couple of months ago.

EasyEngine kept running v5.6 as PHP version ( the fallback), although the server used phpv7.3 ( now) as default. ( Not Nginx so it seems now)

I wasn't able to update to PHP v7.3 ( don't know why), although ee site info reported php v 7 to be used.
phpinfo.php ( which i created) on the website said "PHP Version 5.6.30-7+deb.sury.org~xenial+1"

I used the documentation on WordOps to try and migrate to WordOps, instead of EE.

Haven't found any reference in the *.conf files to php 5.6, so i don't know where it's used ( checked available & enabled sites in the nginx folder).

I had the latest version of wo installed before restoring the latest snapshot.

When WordOpps was installed, i received http error 502, which is the same error as trying to turn off hvvm ( on easyengine) or removing php5.

System Information

- [x] 'ee -v' : v3.8.1
- [x] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
- [x] `wo info` -- none as described. It was the latest version when i tried.
- [x] `nginx -V`
nginx version: nginx/1.10.0
built with OpenSSL 1.0.2h  3 May 2016 (running with OpenSSL 1.0.2k  26 Jan 2017)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_mp4_module --with-http_random_index_module --with-http_secure_link_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-threads --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-dav-ext-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/ngx-fancyindex --add-module=/usr/src/packages/BUILD/debian/modules/nginx-http-push --add-module=/usr/src/packages/BUILD/debian/modules/nginx-lua --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upload-progress --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-development-kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module
- [x] `wo -v` -- none as described
- [x] `wp cli info --allow-root`
OS:     Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.3
PHP version:    7.3.9-1+ubuntu16.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.3/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:    
WP-CLI global config:   
WP-CLI project config:  
WP-CLI version: 2.1.0
- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`
Sorry, had no wordops installed - nice trick though

PS. If you want the extra info, of installing wordops. Please let me know. I will do it then again.

But i reverted the change, since i didn't expect updating my server of packages would take me this long ( => Since i saw that php 7 wasn't used, it took way longer than expected)

PS 2. I had the redis cache on and i do remember a modified version of redis to support HVVM ( not sure, just some extra information).

**Comment by VirtuBox** [comment]
Hello @NicoJuicy, 
we removed hhvm stack from WordOps, so there is no hhvm upstream in our Nginx configuration anymore, that's probably why you get http 502 errors. 
As a workaround, you should be able to use hhvm with WordOps by copying the hhvm upstream from EE configuration (`/etc/nginx/conf.d/upstream.conf`) into a new file like `/etc/nginx/conf.d/hhvm.conf`.

About PHP install, the easiest is probably to purge php7.2 & php7.3 from your server, and to reinstall them with WordOps : 

```bash
wo stack purge --php --php73
wo stack install --php --php73
```
