### ISSUE TITLE
Unable to install Wordops stacks

### ISSUE THREAD

**Issue by Gatewayy** [WordOps/WordOps#155]
System Information

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

wo info
NGINX (1.16.1 ):
user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1

PHP (7.2.22-1):
user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

MySQL (10.3.18-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             1
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

nginx -V
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-6VITbo/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-6VITbo/nginx-1.16.1/debian/modules/ngx_brotli

wo -v
WordOps v3.9.8.11
Copyright (c) 2019 WordOps.

wp cli info --allow-root
OS:     Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.2
PHP version:    7.2.22-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.2/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.3.0

curl -sL git.io/fjAp3 | sudo -E bash -
Here the link to provide in your github issue : https://transfer.sh/kOotY/wordops.tar.gz

--------------------------------------------------------------------------
I have installed WO for the first time today on a fresh VM with Digitaloocean that was created today and updated with the lates patches. I am unable to complete the optional stack installs as the install process sits at the installing netdata portion and the CPU usage on one of the VM's cores goes to 100%.  It appears that the kickstart.sh is the process utalizing the entire core.  

It does appear that this issue is affecting at least one other user on the community forums: https://community.wordops.net/d/171-can-t-complete-wordops-stack-installation.  Please let me know if additional information is needed.

**Comment by VirtuBox** [comment]
Hello @Gatewayy, 
I have tried few minutes ago to setup WordOps on a fresh Ubuntu 18.04 VM, and I haven't be able to reproduce this issue. 
Can you try to purge netdata stack and to try to reinstall it again ?
```bash
wo stack purge --netdata --force
wo stack install --netdata
```

**Comment by Gatewayy** [comment]
That seems to have corrected it, the user in the thread is also now wworking.  Perhaps Netdata was having some issue?

**Comment by VirtuBox** [comment]
Yes, Netdata binary packages repository was maybe unavailable for few hours.
Anyway, thanks for your report and I will try to add a function to check if remote repositories are available before trying to download something from them.
