### ISSUE TITLE
Lets encrypt IP validation

### ISSUE THREAD

**Issue by cristian-rossi** [WordOps/WordOps#162]
Hi,

When installing letsencrypt on a subdomain I got this error:

`subdomain.domain.com is not pointing to your server IP`.

After checking out the code I can see it first tries the real server IP and later the IP through a DNS. If not equal, the check fails:
`def check_dns(self, acme_domains):
        """Check if a list of domains point to the server IP"""
        **server_ip = requests.get('http://v4.wordops.eu/').text**
        for domain in acme_domains:
            **domain_ip = requests.get('http://v4.wordops.eu/dns/{0}/'
                                     .format(domain)).text**
            **if(not domain_ip == server_ip):**
                Log.warn(
                    self, "{0} is not pointing to your server IP"
                    .format(domain))
                Log.error(
                    self, "You have to add the "
                    "proper DNS record", False)
                return False
                break
        else:
            Log.debug(self, "DNS record are properly set")
            return True
`

This server is in a droplet on Digital Ocean on a fixed IP. 
DO also allows me to create a Floating IP and attach it to the server.

When configuring the DNS A entries I point the subdomain to the Floating IP and what happened is:

- This request found the fixed IP: http://v4.wordops.eu/
- This request found the floating IP: http://v4.wordops.eu/dns/{0}/

That obviously causes the check_dns function to fail, not allowing the installation of the LE certificate.

I worked around that by configuring my DNS to the fixed IP, generating the certificate, and configuring the floating IP back.

I have no idea how that could be accounted for but I at least suggest the warning shows something like this so we can better understand what went wrong:
`Your server IP ( 152.102.32.142 ) is different than the DNS IP ( 201.105.21.20 )`

**Comment by VirtuBox** [comment]
Hello @cristian-rossi, 
thanks for your suggestion. I will also add an option to ignore DNS check.

**Comment by VirtuBox** [comment]
`--force` flag has been added with the last WordOps release (v3.9.9.1)
