### ISSUE TITLE
SSH issue - SFTP Login Doesn't Work

### ISSUE THREAD

**Issue by nsgoyat** [WordOps/WordOps#166]
Hello @VirtuBox 
I have been using your "Hardened SSH Config File" for a long time and never faced any issue but with the recent changes with `wo secure ssh` I am facing a really serious issue.

After WO SSH Configuration, I can't login again to the server using the SFTP connection.

The workaround for me is changing `Subsystem /usr/libexec/openssh/sftp-server` to `Subsystem sftp internal-sftp` which makes SFTP working again.

**Comment by VirtuBox** [comment]
Hello @nsgoyat,
After running some tests, it seems the cause is the wrong sftp-server path, which is : `/usr/lib/openssh/sftp-server` on Ubuntu.
Can you try with this path instead of `/usr/libexec/openssh/sftp-server` ?

**Comment by nsgoyat** [comment]
Yes, the new path seems to be working fine, Master. Hope, the solution will be added in the next WO release :)

**Comment by VirtuBox** [comment]
Yes, I have already updated the sshd_config template
