### ISSUE TITLE
error on fresh install

### ISSUE THREAD

**Issue by buzucan** [WordOps/WordOps#17]
I try to install WordOps on fresh server and I recieve this error.
![image](https://user-images.githubusercontent.com/8757017/50630657-559f2380-0f4a-11e9-8598-270acc088f30.png)
![image](https://user-images.githubusercontent.com/8757017/50630727-8ed79380-0f4a-11e9-8a91-4999aa76cb89.png)
[wordops.log](https://github.com/WordOps/WordOps/files/2723181/wordops.log)
[install.log](https://github.com/WordOps/WordOps/files/2723182/install.log)

**Comment by ankitsnlq** [comment]
I faced the same issue with Ubuntu to and latest wo installer. Try this solution will work. 

Create one conf file in nginx conf.d folder.

`/etc/nginx/conf.d/webp.conf`

Add below lines in that file and save file. 

`map $http_accept $webp_suffix {
   default "";
   "~*webp" ".webp";
}
`
After that run create site command.

Let me know if it works. Looks like latest build is failing to create webp.conf file which is to handle WordPress webp images.

**Comment by buzucan** [comment]
Yes, is working now. :)

**Comment by lukasmejia** [comment]
Works for me as well!

**Comment by VirtuBox** [comment]
Issue has been fixed with the PR https://github.com/WordOps/WordOps/pull/24
