### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by kidmarche** [WordOps/WordOps#176]
I try to do manual install and get this:

`python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description = fh.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3799: ordinal not in range(128)
`

Im totally lost, this is a fresh Ubuntu 1604 64bit install. I followed the guides on https://docs.wordops.net/getting-started/installation-guide/

**Comment by kidmarche** [comment]
> I try to do manual install and get this:
> 
> `python3 setup.py install
> 
> Traceback (most recent call last):
> 
> File "setup.py", line 8, in
> 
> ```
> long_description = fh.read()
> ```
> 
> File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
> 
> ```
> return codecs.ascii_decode(input, self.errors)[0]
> ```
> 
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3799: ordinal not in range(128)
> `
> 
> Im totally lost, this is a fresh Ubuntu 1604 64bit install. I followed the guides on https://docs.wordops.net/getting-started/installation-guide/

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
