### ISSUE TITLE
New site creation error.

### ISSUE THREAD

**Issue by ufo56** [WordOps/WordOps#177]
System Information

- [x] `lsb_release -a`  Ubuntu 16.04.6 LTS
- [x] `wo info`  https://pastebin.com/raw/dDDMeUG1
- [x] `nginx -V`  nginx version: nginx/1.16.1 (WordOps Nginx-wo)
- [x] `wo -v`  WordOps v3.9.9.2
- [x] `wp cli info --allow-root`  https://pastebin.com/raw/VcT11ywg
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

When creating new site with command: "wo site create subdomain.domain.com --wp -le"
Successfully created site http://subdomain.domain.com

It creates new site with no ssl and with www...

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
