### ISSUE TITLE
connect() failed upstream: "fastcgi://127.0.0.1:9072"

### ISSUE THREAD

**Issue by buzucan** [WordOps/WordOps#18]
hello. i researched on my logs and I find a lot of errors with:

`connect() failed (111: Connection refused) while connecting to upstream`

there is a solutions for this?

**Comment by VirtuBox** [comment]
Hello,

 are you still experiencing this issue?

**Comment by VirtuBox** [comment]
Last WordOps release use unix:sockets for fastcgi, so this issue should be fixed
