### ISSUE TITLE
Use Redis for object caching with FastCGI caching

### ISSUE THREAD

**Issue by kassemz** [WordOps/WordOps#181]
Currently when you try to update a site installed using --wpfc and update it with --wpredis, it doesn't actually install the object caching plugin, it uses redis for full page caching and disables FastCGI file caching. How to make it use redis for object caching and keep using FastCGI file caching at the same time?

**Comment by VirtuBox** [comment]
Hello @kassemz,
just update your site to `--wpfc` and reinstall manually redis-object-cache plugin.

**Comment by kassemz** [comment]
Hi @VirtuBox 

Thanks for getting back to me. But if I don't first update the site with --wpredis, the Redis server won't get installed, right? So to get this config, one would need to do
wo update --wpredis
wo update --wpfc
then install redis-object-cache plugin.

Shouldn't it be a flag or this is something not many people would want to use?

**Comment by VirtuBox** [comment]
Yes, but you can also install redis-server with `wo stack install --redis` before  creating your site with `--wpfc`.

You are the first one to ask a question about using redis object cache with fastcgi so I'm not sure it require a flag

**Comment by risturiz** [comment]
Hi, actually im testing similar config... I have migrated to FastCGI Caching and installed Redis for object caching and transient caching ( redis config with non-persistent cache )

**Comment by danadalis** [comment]
Hi @VirtuBox

I just installed redis stack and then created a new site with wpfc.

What do you recommend as settings in Nginx Helper plugin?

Below is standard settings - could i keep these as is?

**Caching method?**
- [x] nginx Fastcgi cache (requires external settings for nginx)
- [ ] Redis cache


**Purge Method**
- [x] when a post/page/custom post is published.   Using a GET request to PURGE/url (Default option)
Uses the ngx_cache_purge module.
- [ ] Delete local server cache files	Checks for matching cache file in RT_WP_NGINX_HELPER_CACHE_PATH. Does not require any other modules. Requires that the cache be stored on the same server as WordPress. You must also be using the default nginx cache options (levels=1:2) and (fastcgi_cache_key "$scheme$request_method$host$request_uri").


**Purging Conditions**

Purge Homepage: 
- [x] when a post/page/custom post is modified or added.
- [x] when a post (or page/custom post) is modified or added.

Purge Post/Page/Custom Post Type:
- [x] when an existing post/page/custom post is modified.
- [x] when a published post (or page/custom post) is trashed

**Purge Archives:**
(date, category, tag, author, custom taxonomies)
- [x] when a post (or page/custom post) is modified or added.  
- [x] when an existing post/page/custom post is trashed.    when a published post (or page/custom post) is trashed.  
 
- [ ] when a comment is approved/published.    when a comment is approved/published.  
- [ ] when a comment is unapproved/deleted.    when a comment is unapproved/deleted.

**Comment by VirtuBox** [comment]
Hello @danadalis,
your settings are correct, Nginx-helper job is only to purge full-page cache (Nginx fastcgi_cache or Redis).
So when you are using Redis only for WordPress object-cache, purging redis isn't required.

**Comment by knilkantha** [comment]
Hi @VirtuBox ,
WordPress was initially installed with Redis cache using `wo site create site.tld --wpredis` . Now, I shift to fastcgi.
Does updating to fastcgi with `wo site update site.tld --wpfc` will also remove Redis stack from the server?
