### ISSUE TITLE
Error Updating to php73 on site update. Still poiting to php72

### ISSUE THREAD

**Issue by lpienia** [WordOps/WordOps#188]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

after executing site update domain.com --php73 the config nginx file is still poiting to php72. I need to make the change manually.

Regards

**Comment by VirtuBox** [comment]
Hello,
what flag did you used to create the site initially ?
