### ISSUE TITLE
sched_setaffinity() failed (22: Invalid argument) in nginx error.log 

### ISSUE THREAD

**Issue by renatofrota** [WordOps/WordOps#195]
Hello,

**/var/log/nginx/error.log** has several of these:

```
2019/11/07 18:03:18 [alert] 147148#147148: sched_setaffinity() failed (22: Invalid argument)
```

It seems to be related with `worker_processes 4` on **/var/www/22222/htdocs/db/pma/test/nginx.conf** (line 1).

I am a poor boy, my server has less than 4 cores... :joy: 

[apparently] Resolved changing `4` to `auto` ([worker_cpu_affinity docs](http://nginx.org/en/docs/ngx_core_module.html#worker_cpu_affinity)).

**Comment by VirtuBox** [comment]
Hello @renatofrota,
The file ` /var/www/22222/htdocs/db/pma/test/nginx.conf` is not included in WordOps Nginx configuration. 
We already use `worker_processes auto;` in /etc/nginx/nginx.conf.

**Comment by renatofrota** [comment]
I see... it is installed along PhpMyAdmin (https://github.com/WordOps/WordOps/blob/master/wo/cli/plugins/stack.py). I will report to them. Thanks.
