### ISSUE TITLE
Change Domain

### ISSUE THREAD

**Issue by swissky** [WordOps/WordOps#199]
Is there a easy command to change the domain to a new domain?

**Comment by VirtuBox** [comment]
Hello @swissky,

not currently but we are planning to add a similar feature with staging site support. We may also add this feature at the same time.

**Comment by swissky** [comment]
Oh nice. But how look the workaround to move a running website to WordOrps?

**Comment by tersor** [comment]
@swissky I have done this a couple of times manually.

1. Update sqlite database.

Find site ID:

```
sqlite3 /var/lib/wo/dbase.db 'select * from sites;' --column --header
```

Update `sitename`, `site_path` and `is_ssl` (use correct site ID):

```
sqlite3 /var/lib/wo/dbase.db 'update sites set sitename = 'new_domain.tld' where id = <ID>; update sites set site_path = '/var/www/new_domain.tld' where id = <ID>; update sites set is_ssl = 0 where id = <ID>;'
```

2. Move files

```
mv /var/www/old_domain.tld /var/www/new_domain.tld
```

3. Update symlinks and nginx config

```
rm /etc/nginx/sites-enabled/old_domain.tld
rm /etc/nginx/conf.d/force-ssl-old_domain.tld.conf
mv /etc/nginx/sites-available/old_domain.tld /etc/nginx/sites-available/new_domain.tld
sed -i -e 's/old_domain.tld/new_domain.tld/g' /etc/nginx/sites-available/new_domain.tld
ln -s /etc/nginx/sites-available/new_domain.tld /etc/nginx/sites-enabled
```

Check if everything is ok and reload nginx:

```
nginx -t
service nginx reload
```

4. Update URLs

```
wp search-replace 'https://old_domain.tld' 'http://new_domain.tld' --path=/var/www/new_domain.tld/htdocs --all-tables
```

5. Remove old cert and install new.

```
rm -rf /etc/letsencrypt/live/old_domain.tld /etc/letsencrypt/renew/old_domain.tld_ecc
wo site update new_domain.tld --le
```

**Comment by VirtuBox** [comment]
Thanks @tersor  for this detailled explanation. I will add it to the documentation, the time we add this feature into WordOps.

**Comment by JPaulMora** [comment]
In my case, I was moving `dev.mysite.com` to `mysite.com`. First, use @tersor instructions to migrate your current site to `old.mysite.com` but:

* Skip SSL renew
* skip the last SQL statement on line 2 (` update sites set is_ssl = 0 where id = <ID>;'`)
* Do all URL/string replacements with http**S** 

Then migrate your `dev.mysite.com` to the proper location with the same warnings as above.

Finally, delete your `/var/www/mysite.com/conf` and use the original one by moving  `/var/www/old.mysite.com/conf` to `/var/www/mysite.com/conf`

Done

**Comment by ibrahimhajjaj** [comment]
> @swissky I have done this a couple of times manually.
> 
> 1. Update sqlite database.
> 
> Find site ID:
> 
> ```
> sqlite3 /var/lib/wo/dbase.db 'select * from sites;' --column --header
> ```
> 
> Update `sitename`, `site_path` and `is_ssl` (use correct site ID):
> 
> ```
> sqlite3 /var/lib/wo/dbase.db 'update sites set sitename = "new_domain.tld" where id = <ID>; update sites set site_path = "/var/www/new_domain.tld" where id = <ID>; update sites set is_ssl = 0 where id = <ID>;'
> ```
> 
> 2. Move files
> 
> ```
> mv /var/www/old_domain.tld /var/www/new_domain.tld
> ```
> 
> 3. Update symlinks and nginx config
> 
> ```
> rm /etc/nginx/sites-enabled/old_domain.tld
> rm /etc/nginx/conf.d/force-ssl-old_domain.tld.conf
> mv /etc/nginx/sites-available/old_domain.tld /etc/nginx/sites-available/new_domain.tld
> sed -i -e 's/old_domain.tld/new_domain.tld/g' /etc/nginx/sites-available/new_domain.tld
> ln -s /etc/nginx/sites-available/new_domain.tld /etc/nginx/sites-enabled
> ```
> 
> Check if everything is ok and reload nginx:
> 
> ```
> nginx -t
> service nginx reload
> ```
> 
> 4. Update URLs
> 
> ```
> wp search-replace 'https://old_domain.tld' 'http://new_domain.tld' --path=/var/www/new_domain.tld/htdocs --all-tables
> ```
> 
> 5. Remove old cert and install new.
> 
> ```
> rm -rf /etc/letsencrypt/live/old_domain.tld /etc/letsencrypt/renew/old_domain.tld_ecc
> wo site update new_domain.tld --le
> ```

Unfortunately, this didn't work for me

**Comment by ibrahimhajjaj** [comment]
> > @swissky I have done this a couple of times manually.
> > 
> > 1. Update sqlite database.
> > 
> > Find site ID:
> > ```
> > sqlite3 /var/lib/wo/dbase.db 'select * from sites;' --column --header
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Update `sitename`, `site_path` and `is_ssl` (use correct site ID):
> > ```
> > sqlite3 /var/lib/wo/dbase.db 'update sites set sitename = "new_domain.tld" where id = <ID>; update sites set site_path = "/var/www/new_domain.tld" where id = <ID>; update sites set is_ssl = 0 where id = <ID>;'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Move files
> > 
> > ```
> > mv /var/www/old_domain.tld /var/www/new_domain.tld
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Update symlinks and nginx config
> > 
> > ```
> > rm /etc/nginx/sites-enabled/old_domain.tld
> > rm /etc/nginx/conf.d/force-ssl-old_domain.tld.conf
> > mv /etc/nginx/sites-available/old_domain.tld /etc/nginx/sites-available/new_domain.tld
> > sed -i -e 's/old_domain.tld/new_domain.tld/g' /etc/nginx/sites-available/new_domain.tld
> > ln -s /etc/nginx/sites-available/new_domain.tld /etc/nginx/sites-enabled
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Check if everything is ok and reload nginx:
> > ```
> > nginx -t
> > service nginx reload
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 4. Update URLs
> > 
> > ```
> > wp search-replace 'https://old_domain.tld' 'http://new_domain.tld' --path=/var/www/new_domain.tld/htdocs --all-tables
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. Remove old cert and install new.
> > 
> > ```
> > rm -rf /etc/letsencrypt/live/old_domain.tld /etc/letsencrypt/renew/old_domain.tld_ecc
> > wo site update new_domain.tld --le
> > ```
> 
> Unfortunately, this didn't work for me. When I run the sites list command I still get the old domain instead of the new domain.
> 
> But I get Welcome to Nginx! when I visit the new domain
> 
> wo site list

Managed to solve this by updating the include in nginx conf file from include /etc/nginx/sites-enabled/*;  to include /etc/nginx/sites-enabled/*.*; 

nano /etc/nginx/nginx.conf


nginx -t
service nginx reload

**Comment by crbon** [comment]
Is the site domain change feature still in the works/planned?
