### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by buzucan** [WordOps/WordOps#2]
hello, i tried your build. take a look 
![image](https://user-images.githubusercontent.com/8757017/49437809-31261f00-f7c5-11e8-9335-bf4aee218d44.png)

take install.log :)
[install.log](https://github.com/WordOps/WordOps/files/2643673/install.log)

**Comment by jeroenops** [comment]
Thank you kindly for checking it out - the newest commit should fix it. Could you re-run the setup?

**Comment by buzucan** [comment]
i`ve added install.log too [install.log](https://github.com/WordOps/WordOps/files/2643964/install.log)

**Comment by jeroenops** [comment]
Thank you!

Could you please post the output of:

```
lsb_release -a
uname -a
tail -n 50 /var/log/apt/term.log
```

Feel free to remove the hostname from the last two commands for privacy reasons :)

**Comment by buzucan** [comment]
![image](https://user-images.githubusercontent.com/8757017/49442943-a698ec00-f7d3-11e8-8cc9-19a7d9ec7980.png)

**Comment by jeroenops** [comment]
Thanks, I'll take a more in-depth look and fix this later today :smiley:

**Comment by buzucan** [comment]
if you want i can make you a user for live testing.

**Comment by wolerine** [comment]
I had exactly same error about on Debian 8.1
And on Ubuntu 16.04, _wo stack install -all_ fails while configuring nginx.

**Comment by janiosarmento** [comment]
Ubuntu 18.04 also breaks while installing Nginx:

```
root@ubuntu:~# wo stack install --nginx
Adding repository for NGINX, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Reload : nginx     [Failed]
Unable to change owner : /var/www/22222
root@ubuntu:~# nginx -t
nginx: [emerg] invalid port in upstream "127.0.0.1:" in /etc/nginx/conf.d/upstream.conf:11
nginx: configuration file /etc/nginx/nginx.conf test failed
root@ubuntu:~#
```

**Comment by jeroenops** [comment]
Thanks all! We'll have it resolved later today, seems like some changes in the installer yesterday are the reason this happens. Currently debugging using every supported Ubuntu/Debian version to get to the bottom of the issues.

**Comment by jeroenops** [comment]
Should all be resolved. Please run the installer again to fix it if you are still having issues. Otherwise, feel free to comment here or on our Slack channel - we have your back.
