### ISSUE TITLE
Error with SSL Let'sencrypt on fresh install (domain do not resolve) in wo-acme and --LE command

### ISSUE THREAD

**Issue by lukasmejia** [WordOps/WordOps#20]
Hi there, cannot get install a SSL on a fresh install (Ubuntu 18.04 LTS) Domain is pointed correctly but keeps saying with --LE command:
Unable to setup, Let’s Encrypt
Please make sure that your site is pointed to
same server on which you are running Let’s Encrypt Client
to allow it to verify the site automatically.

and with wo-acme:
socat is already the newest version (1.7.3.2-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
####################################
Error : domain do not resolve server IP

**Comment by manacim** [comment]
@lukasmejia check out my fix at https://community.wordops.org/d/12-lets-encrypt-fix-for-ubuntu-16-04

**Comment by VirtuBox** [comment]
WordOps do not use wo-acme-sh anymore, so I'm closing this issue
