### ISSUE TITLE
Wo update: Error Synchronizing wo database

### ISSUE THREAD

**Issue by andremacola** [WordOps/WordOps#201]
Running wo update:

```Synchronizing wo database, please wait...
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 111, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/sync.py", line 24, in default
    self.sync()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/sync.py", line 57, in sync
    'DB_NAME').split(',')[1]
AttributeError: 'bool' object has no attribute 'split'
WordOps (wo) upgrade to v3.10.3 was succesfull!```

But apparently WO is working...

**Comment by andremacola** [comment]
Same issue on a different server updating to 3.11.1

**Comment by VirtuBox** [comment]
Hello @andremacola, 
I think there is something wrong in one of your wp-config.php.
Try to go into each site root directory and to run `sudo -u www-data -H wp config list` to see if it return a warning or an error.

**Comment by andremacola** [comment]
@VirtuBox hmmm. Well, I do not run the sites under www-data, I have custom users/php-pool for each one and I do not use the default Wordpress configuration (I have a custom shell script doing this job for me). 

**For example:**
- My wp-config is just a wrapper for my real enviroment file configuration.
- I use composer to manage all my wordpress/themes and plugins
- My wordpress core files is under wp/ folder
- wp-content is app/
- I have a custom nginx configuration based on WO nginx files.

![Captura de Tela 2019-12-09 às 23 08 07](https://user-images.githubusercontent.com/3408809/70488961-0b6ade80-1ad9-11ea-8332-23e34a3bfbd2.png)

![Captura de Tela 2019-12-09 às 23 09 03](https://user-images.githubusercontent.com/3408809/70488963-0d34a200-1ad9-11ea-888a-669b8771211c.png)

In fact, if WO runs some wp-cli command inside the site root folder it return an error if I did not include the `wp-cli.yml ` file specifying the `htdocs/wp` directory

**Comment by andremacola** [comment]
Maybe you have to check if the wp-config.php exist before trying to `Synchronizing wo database` stuff.
