### ISSUE TITLE
 return 307 https://$host$request_uri

### ISSUE THREAD

**Issue by swissky** [WordOps/WordOps#203]
Hi, i try to follow this guide: https://blog.realkinetic.com/http-to-https-using-google-cloud-load-balancer-dda57ac97c and put this code inside my site config.

server {
 listen 80 default_server;
 listen [::]:80 default_server;
 server_name _;
 return 307 https://$host$request_uri;
}

When i try to restart the service, i don`t get a "Ok"

**Comment by VirtuBox** [comment]
Hello,
use `nginx - t` to check what is wrong in your configuration. But for me it's the usage of default_server

**Comment by swissky** [comment]
@VirtuBox ok thank you. Any idea how i can fix this? Its just one server with one Multisite on it. And i thing without this config the Load Balancer and then the CDN from Google doesn`t work.

**Comment by VirtuBox** [comment]
remove this part and edit `/etc/nginx/sites-available/default` to redirect the traffic on https

**Comment by swissky** [comment]
So like this 
`
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        # SSL configuration
        #
         listen 443 ssl default_server;
         listen [::]:443 ssl default_server;
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        # include snippets/snakeoil.conf;
        #
        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE
        # ssl_ciphers HIGH:!aNULL:!MD5;
        # ssl_prefer_server_ciphers on;`

or 

`server {
        listen 80 default_server;
        listen [::]:80 default_server;
return 307 https://$host$request_uri;
}
# SSL configuration
#
        #  listen 443 ssl default_server;
        #  listen [::]:443 ssl default_server;
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        # include snippets/snakeoil.conf;
        #
        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE
        # ssl_ciphers HIGH:!aNULL:!MD5;
        # ssl_prefer_server_ciphers on;
        root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;`

**Comment by VirtuBox** [comment]
just add `return 307 https://$host$request_uri;` inside the `server {}` block and use `nginx -t` to make sure there is no error before reloading Nginx with `service nginx reload` or `wo stack reload --nginx`

**Comment by swissky** [comment]
Thank you @VirtuBox, but get still my 301: Permanent redirect :-( 
I think its time to hire a freelancer ;)

**Comment by VirtuBox** [comment]
If you are running WordPress behind a load-balancer, you may have to add the following line in your wp-config.php to force WordPress to use https.

```php
$_SERVER['HTTPS'] = 'on';
```

**Comment by swissky** [comment]
@VirtuBox Thank you again, but same result. 
There are a lot of tutorials like this:  https://www.cloudbooklet.com/setup-https-load-balancing-in-google-cloud-cdn/ but not one for a WordOps setting

**Comment by VirtuBox** [comment]
Have you secure the site with letsencrypt ?

**Comment by swissky** [comment]
Yes

**Comment by VirtuBox** [comment]
So, it's just the file `/etc/nginx/conf.d/force-ssl-yourdomain.tld.conf` the issue (which add the 301 redirection). Remove it or move it outside /etc/nginx and then reload Nginx.

**Comment by swissky** [comment]
Great it works, but now i get get the "Welcome to nginx!" screen ;) 
I probably should get System Admin instead of Front Developer. :-D
