### ISSUE TITLE
Automatic database names tweak

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#206]
I'd like to suggest a tweak to the database name creation routine.

Currently, the database name (as well as the username) is automatically created by removing the dots, truncating on a number of characters, then appending a random string.

My suggestion is to replace the dots with underline characters instead of removing them. The advantage of this method is making more intuitive to a human being to identify which domain a given database belongs to.

Also, when a domain has dashes they are included in the database name. The dashes could be converted to underline too.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`

**Comment by emanweb** [comment]
It would be awesome to be capable of pass the database name and credentials as optional arguments when creating a site. Or that could be done now and I am not aware?
