### ISSUE TITLE
Error creating new Wordpress site (NGINX Reload: Fails)

### ISSUE THREAD

**Issue by neo3k** [WordOps/WordOps#21]
Fails to create WP site in NGINX restart step.

(Congratulations on the WordOps initiative, I hope it has a lot of future).

<img width="568" alt="captura de pantalla 2019-01-23 a las 9 33 34" src="https://user-images.githubusercontent.com/4956589/51597099-5b0cdf80-1ef2-11e9-8549-0d18294e3058.png">

**Comment by cheonmux** [comment]
I have same problem.

**Comment by 11mlab** [comment]
Hello,
please run the following command:

`echo -e '\nmap $http_accept $webp_suffix {\n   default "";\n   "~*webp" ".webp";\n}' > /etc/nginx/conf.d/webp.conf`

VirtuBox and WordOps team are working on a fix about this issue

**Comment by w33zy** [comment]
Had the same issue and @11mlab fix worked

**Comment by o0oBluePhoenixo0o** [comment]
From @11mlab , it means create a "webp.conf" since the WO engine doesn't create the default file for nginx. Another way to do it is 

`cd \etc\nginx\conf.d\
sudo nano webp.conf`

Then type in the following (default settings) and Ctrl + X to save. After that, try to create the site again
```
map $http_accept $webp_suffix {
   default "";
   "~*webp" ".webp";
}
```

**Comment by VirtuBox** [comment]
Issue has been fixed with the PR https://github.com/WordOps/WordOps/pull/24
