### ISSUE TITLE
PHP edge version

### ISSUE THREAD

**Issue by tdtgit** [WordOps/WordOps#212]
Long time no see,

I would like to suggest adding PHP edge version (currently PHP 7.4.0, not much edge) so people can test their site on the newest one more frequently and sooner.

Maybe combine with the staging site #99 is nice to have.

**Comment by tdtgit** [comment]
Oops. I see your PR to support PHP 7.4. But I think living at the edge version with full of Nginx mainline, MariaDB 10.3 and more :)

**Comment by VirtuBox** [comment]
Hello @tdtgit,
I will probably add support for my script to compile the latest Nginx mainline release in WordOps, but I'm not going to build debian packages for Nginx mainline releases, because I haven't be able to fully automate debian packaging and mainline release lifecycle is too short.

**Comment by tdtgit** [comment]
Thinking to close this issue as it's too old and not in critical roadmap.
