### ISSUE TITLE
v3.11.1 [NGINX] Warn - nginx: [warn] could not build optimal variables_hash...

### ISSUE THREAD

**Issue by andremacola** [WordOps/WordOps#216]
After v3.11.1 update I'm receiving this message on `nginx -t && service nginx reload`

```nginx: [warn] could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size```

I think this is related to the new `webp.conf`

**Comment by VirtuBox** [comment]
Hello @andremacola,
thanks for your report, I will check how to fix this without creating conflict with extensions like ngxblocker.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
