### ISSUE TITLE
"sudo wo site cd" not working

### ISSUE THREAD

**Issue by abbaselmas** [WordOps/WordOps#217]
Currently on 3.11.1 and "sudo wo site cd" command doesnt chaning my directory.

**Comment by VirtuBox** [comment]
Hello @abbaselmas, issue has been fixed in commit d536f57cd98c9b6cc4cf7ef30fe38db59dbf02c1, it will be available in the next release.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
