### ISSUE TITLE
Site with proxy should include X-Forwarded-Proto header in vhost config

### ISSUE THREAD

**Issue by VoidMonk** [WordOps/WordOps#218]
Hi,

When a new site is created with proxy routing, such as:

`wo site create yoursite.tld --proxy=127.0.0.1:2368`

It adds some proxy headers to the nginx vhost config, but doesn't add one important one:

`proxy_set_header X-Forwarded-Proto $scheme;`

It's a standard header for reliable proxy routing. Without this header, Nodejs (Express in particular) can go in a redirection loop.

I hope you can consider adding it in a future update.

Thank you!

---

System Information

- [x] `lsb_release -a`
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

- [x] `wo info`
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1
PHP 7.2 is not installed

PHP (7.4.0):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.3.20-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             11
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [x] `nginx -V`
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019 (running with OpenSSL 1.1.1  11 Sep 2018)
TLS SNI support enabled

- [x] `wo -v`
WordOps v3.11.1

- [x] `wp cli info --allow-root`
OS:     Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.0
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

- [x] `node -v`
v10.17.0

**Comment by VirtuBox** [comment]
Hello @VoidMonk,
thanks for your suggestion, I have update WordOps virtualhost template to include the config file `/etc/nginx/proxy_params` which include X-Forwarded-Proto : 

```nginx
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
