### ISSUE TITLE
wo stack restart php7 

### ISSUE THREAD

**Issue by ddur** [WordOps/WordOps#22]
I think this line, and more below, requires change. Code checks only for old platforms, 
https://github.com/WordOps/WordOps/blob/54059de0e7ef04321d195a472f4c155a6d0b92ba/wo/cli/plugins/stack_services.py#L55
https://github.com/WordOps/WordOps/blob/54059de0e7ef04321d195a472f4c155a6d0b92ba/wo/cli/plugins/stack_services.py#L132

etc ....

Although, I think there is no need to check platforms there at all.
If service is not installed, command will log error (or fail?), no matter on what platform.

Btw, similar to issue reported here, a long time ago.
https://github.com/EasyEngine/easyengine/issues/844

**Comment by VirtuBox** [comment]
Issue fixed with PR https://github.com/WordOps/WordOps/pull/26
