### ISSUE TITLE
Error create new site

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#220]
System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

- [ ] `wo -v`
WordOps v3.11.2
Copyright (c) 2019 WordOps.

Running pre-update checks       [KO]
NGINX configuration check failed.
root@teste:~# nginx -t
nginx: [emerg] no port in upstream "php74" in /etc/nginx/conf.d/stub_status.conf:47
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by VirtuBox** [comment]
Hello @juanpvh,
please run `wo stack upgrade --nginx` and let me know if you still have this issue

**Comment by juanpvh** [comment]
ok @VirtuBox, now website creation is working

**Comment by FillHK** [comment]
Adding repository for NGINX, please wait...
Updating APT cache              [OK]
Applying Nginx configuration templates
Testing Nginx configuration     [KO]
Testing Nginx configuration     [KO]
Configuring APT Packages        [OK]
