### ISSUE TITLE
Password reset is not working

### ISSUE THREAD

**Issue by techgarageblog** [WordOps/WordOps#223]
Hi, i try to set a new password with 
`wo site update --password`

I know the my Username "Name Surname" is right but i get all the time the notification 
`Invalid WordPress user "name surname" for site.`

I try it with a "-" in the middle but it doesn`t work.

**Comment by VirtuBox** [comment]
Hello @techgarageblog,

i will take a look on this, but username including space are not standard in WordPress, so I'm not surprised it doesn't work when trying to reset password with WordOps

**Comment by techgarageblog** [comment]
Thank you. The problem was i set up my full name, when i setup WordOps ;)

**Comment by VirtuBox** [comment]
You can change it at anytime in the file `~/.gitconfig`.

**Comment by techgarageblog** [comment]
Easy, actually i need a solotion to reset the pasword ;)

**Comment by techgarageblog** [comment]
Have you found a solution? Unfortunately the password reset mails do not arrive either. Must configure every installation with Mailgun. Currently the backend (22222) doesn't want to swallow the login data either, otherwise I would have changed the password in the database.

**Comment by dingman** [comment]
@techgarageblog did you try updating the password using wpcli? I've done it numerous times recently, with success.

https://developer.wordpress.org/cli/commands/user/update/
