### ISSUE TITLE
Feature Request - OpenLiteSpeed

### ISSUE THREAD

**Issue by kymc** [WordOps/WordOps#224]
Any thoughts on introducing OpenLiteSpeed - looks like the performance is there?

---

Installation:

https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-openlitespeed-ubuntu-1804

Performance:

https://www.cyberhosting.org/2019/06/13/openlitespeed-vs-nginx/
https://blog.litespeedtech.com/2019/11/25/http3-litespeed-vs-nginx/

Trouble in NGINX world:

https://arstechnica.com/information-technology/2019/12/russian-media-group-rambler-attempting-to-hold-nginx-hostage/
https://www.ft.com/content/6b687b80-1dbd-11ea-97df-cc63de1d73f4

**Comment by nsgoyat** [comment]
Hey @kymc 
I was thinking to create the same feature request about a few weeks back but I thought to test it out myself.

The OpenLiteSpeed is optimized by default, we hardly need to tweak any Server Level settings when we use it's LS Cache plugin with WordPress. On the other hand, NGINX by default isn't optimized for WordPress and that's where WordOps comes to add the missing part.

I compared OpenLiteSpeed with NGINX (through WordOps) and I found that it still beats NGINX in terms of SysBenchmarks like File I/O, Requests per Second, etc but the margin isn't that great which we have seen in www.cyberhosting.org tests.

However, WordPress load time is similar in both cases. I use LS Cache on one site and Autoptimize+NGINX Helper on the WordOps based site and the load time was almost the same.

But what makes me worry about using OpenLiteSpeed is its stability. As it's not yet adopted by many hosting companies and programmers yet so we really have less support compared to OpenLiteSpeed.

Recently, I recommend WordOps to one of my friends who have been using OpenLiteSpeed for 6 Months. After his own tests, he moved approximately 30 sites from OpenLiteSpeed to WordOps recently.

I have shared this thread's link with him and asked him to share his opinion about OpenLiteSpeed VS NGINX. However, the Russian News about NGINX is seriously a concern and we may need to work on an alternative already just in case.

I am not a developer myself self but I think it will be a lot of work for @VirtuBox to implement a new Web Server and rewrite the WO Framework and configurations.

**Comment by VirtuBox** [comment]
Hello @kymc,

We are not planning to work with another web server than Nginx at the moment.
Mostly because Nginx is highly versatile. In WordOps it provide the ability to use several caching systems including full-page cache with Redis.
With OpenLiteSpeed, we will only be able to use LSCache.

**Comment by stevefloyd** [comment]
Thanks for suggesting this @kymc, I agree it would be a great to have the CLI tools of WordOps with the performance improvements of Litespeed servers. I hope the WordOps team considers implementing more flexibility like this.

**Comment by philbraun** [comment]
> With OpenLiteSpeed, we will only be able to use LSCache.
Just a quick commentary: unless I'm not understanding something correctly, this is not quite correct. There's no problem at all using PHP-based caches like WPRocket or Cache Enabler with OLS. LSCache simply is the option most/best integrated, like fastCGI with NGiNX.
