### ISSUE TITLE
Don`t get Mails with GCP

### ISSUE THREAD

**Issue by swissky** [WordOps/WordOps#225]
Hi, I'm not getting any system mail same from WordPress. (Password reset)
I know that Google Cloud has blocked port 25. Now I would like to use Mailgun for the complete mail communication. 
Which Mail Service is installed? 
Postfix seems to be popular and offers many instructions for Mailgun.

**Comment by morganhvidt** [comment]
I just use the Mailjet API keys in the WordPress plugin. Everything is sent via the API and not by the servers ports. It works really well on GCP for me.

Why not do the same with Mailgun? https://kinsta.com/knowledgebase/mailgun-wordpress/

**Comment by dingman** [comment]
@swissky WordOps does not support Mail services, which in and of itself is a good thing. It's not core to the functionality of WordOps. As Morgan suggested, use a mail service like MailGun or MailJet.

Feel free to close this if it's resolved.
