### ISSUE TITLE
upstream.mustache definitions missing dot for >= php73

### ISSUE THREAD

**Issue by samkatakouzinos** [WordOps/WordOps#230]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

<details><summary>System Information</summary>

- [x] `lsb_release -a`
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

- [x] `wo info`
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1

PHP (7.2.26-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.7/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.7/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.7/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.7/dist-packages/wo/cli/plugins/info.py", line 395, in default
    self.info_php73()
  File "/usr/local/lib/python3.7/dist-packages/wo/cli/plugins/info.py", line 182, in info_php73
    www_ping_path = wconfig['ping.path']
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'ping.path'

- [x] `nginx -V`
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

- [x] `wo -v`
WordOps v3.11.2
Copyright (c) 2019 WordOps.

- [x] `wp cli info --allow-root`
OS:     Linux 4.19.0 #1 SMP Wed May 15 09:45:34 MSK 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.1
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /run/php
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0

- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`
Here the link to provide in your github issue : https://transfer.vtbox.net/zhz8Y/wordops.txt

</details>

upstream.mustache 

definitions >= php73 do not have dot between major and minor numbers
This produces 502 Bad Gateway

Below snippet correctly works
```
# PHP 7.4 upstream with load-balancing on two unix sockets
upstream php74 {
    least_conn;

#    server unix:/var/run/php/php74-fpm.sock;
#    server unix:/var/run/php/php74-two-fpm.sock;

    server unix:/var/run/php/php7.4-fpm.sock;
    server unix:/var/run/php/php7.4-two-fpm.sock;

    keepalive 5;
}
```

*.sock files under /var/run/php >= 7.3 have dot between major and minor numbers.

**Comment by vasiler** [comment]
![Screenshot_20200103-200022_ES File Explorer Pro](https://user-images.githubusercontent.com/40354554/71740060-dea1b100-2e63-11ea-9588-553902c23543.jpg)
That's not true.

**Comment by samkatakouzinos** [comment]
Hmmm… How come your sock files don't have dots like mine? 

![WinSCP_AVdfIgLPr5](https://user-images.githubusercontent.com/1305871/71740499-85ac3a00-2eb0-11ea-807b-5e12aefba32d.png)

**Comment by vasiler** [comment]
I installed php using wo stack install --php73 and wo stack install --php74. Have you used any other method?

**Comment by samkatakouzinos** [comment]
Yes I used the following method;
apt install php7.3-fpm php7.4-fpm

**Comment by samkatakouzinos** [comment]
I did the following; 
```
apt remove php7.3* php7.4*
wo stack remove --php74
wo stack remove --php73
wo stack install --php74
wo stack install --php73
```

The sock files now match the directives;
![WinSCP_HY9oECCNoP](https://user-images.githubusercontent.com/1305871/71755915-2c103380-2ee1-11ea-8377-65e6684f5f52.png)
