### ISSUE TITLE
There is a mismatch between HTTPS indicated on the server and client

### ISSUE THREAD

**Issue by khuyennguyen7007** [WordOps/WordOps#231]
After install WordOps, I access to phpMyAdmin and receive an error: `There is a mismatch between HTTPS indicated on the server and client`. In the console, an error message with content: `Refused to apply style from 'xxx' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

System Information

- [x] `lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```
- [x] `wo info`
```
NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 

PHP (7.2.26-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

MySQL (10.3.21-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```
- [x] `nginx -V`
```
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019 (running with OpenSSL 1.1.1b  26 Feb 2019)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-yZZjue/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_brotli
```
- [x] `wo -v`
```
WordOps v3.11.2
Copyright (c) 2019 WordOps.
```
- [x] `wp cli info --allow-root`
```
OS:	Linux 5.0.0-37-generic #40-Ubuntu SMP Thu Nov 14 00:14:01 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.2
PHP version:	7.2.26-1+ubuntu19.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.2/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```
After investigated, I founded that pma folder is empty. I fixed that by run command `wo stack upgrade --phpmyadmin`. But I can't figure out why it's happen. When I run `wo stack install`, no error display.

**Comment by HesselTjeerdsma** [comment]
This should be a relatively easy fix by adding the following header in the nginx config file for PMA. 
`proxy_set_header X-Forwarded-Proto https;` Since nginx will always ssl terminate requests to the secure page, it should not be a security issue.

**Comment by HesselTjeerdsma** [comment]
This would only fix the https error, but the main problem is that the .scss are not compiled and thus there are no css files. I fixed this by running:
`npm install --ignore-scripts --no-package-lock && npm run css-compile` and then `composer install`

**Comment by HesselTjeerdsma** [comment]
Final comment here, since phpmyadmin v5.0 (and since there is no version check in place for wordops) uses yarn to compile the scss file, this step should be implemented in the install script. I will make pull-request to fix this ASAP

**Comment by VirtuBox** [comment]
Hello @HesselTjeerdsma,
thanks for investigating on this. Do you think it would be easier to download directly the phpmyadmin realase archive instead of the development version ?
I just noticed there was a permanent link to download the latest phpmyadmin version from a script, which come with pre-compiled assets : https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz

**Comment by HesselTjeerdsma** [comment]
Yes, that would be much easier. I tried including yarn + sass to compile
the scss and in install the packages in a fork, but this was overly
complicated. Using a archive with precompiled assets would be a more
elegant solution indeed!


On Feb 4, 2020 at 13:45, VirtuBox <notifications@github.com> wrote:

Hello @HesselTjeerdsma <https://github.com/HesselTjeerdsma>,
thanks for investigating on this. Do you think it would be easier to
download directly the phpmyadmin realase archive instead of the development
version ?
I just noticed there was a permanent link to download the latest phpmyadmin
version from a script, which come with pre-compiled assets :
https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/WordOps/WordOps/issues/231?email_source=notifications&email_token=ACWTE4J5A3YI7HZEJU2YN23RBFPNNA5CNFSM4KC25FJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKXP3TI#issuecomment-581893581>,
or unsubscribe

**Comment by Slapbox** [comment]
Suddenly seeing this error after upgrading from `3.12.2` to `3.13.2`
