### ISSUE TITLE
Update site tld 

### ISSUE THREAD

**Issue by sanketch** [WordOps/WordOps#233]
Is there an update command option to change the site's domain? I tried updating the domain (site + home URL) on wordpress settings, and changed the nginx configuration under server name. But I am still unable to get it working. Any pointers?

**Comment by tersor** [comment]
@sanketch no command for this yet.
See also #199

**Comment by VirtuBox** [comment]
Hello @sanketch, 
This feature will be available available soon. It's already listed in the project [roadmap](https://github.com/WordOps/WordOps/projects/2).
