### ISSUE TITLE
Check for remote MySQL server

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#234]
Per our conversation on the [forums](https://community.wordops.net/d/320-error-when-creating-a-new-site)

Requesting that there be a check in place when creating a new site, purging a stack --mysql, and could be other places, that the check verify if a remote mysql server has been configured first.

**Comment by VirtuBox** [comment]
Hello @dingman,
fix was already pushed to the repository yesterday (https://github.com/WordOps/WordOps/commit/9a5b3e3368709a5a21205218a0e493f9841d9249), it will be available in the next release.

**Comment by dingman** [comment]
@VirtuBox here is a similar issue when dealing with remote MySQL servers

```
root@ip-172-00-00-00:/var/www/domain.net/htdocs/wp-content# wo info
...
MySQL (10.3.21-MariaDB) on localhost:

port                             3306
wait_timeout                     28800
interactive_timeout              28800
max_used_connections             31
datadir                          /rdsdbdata/db/
socket                           /tmp/mysql.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
root@ip-172-00-00-00:/var/www/domain.net/htdocs/wp-content# wo stack purge --mysql
MariaDB is not installed
```

**Comment by dingman** [comment]
@VirtuBox the issue seems to persist still.

I installed a fresh copy of WO and configured /etc/mysql/conf.d/my.cnf with the external DB. Then ran the install

```
ubuntu@ip-172-31-50-16:~$ wo site create domain.net --php74 --wp
Adding repository for MySQL, please wait...
Updating apt-cache              [OK]
Installing APT packages         [OK]
Tuning MariaDB configuration
Stop  : mysql     [OK]
Start : mysql     [OK]
Running pre-update checks       [OK]
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             [Done]
Configuring WordPress           [OK]
Installing WordPress            [OK]
Installing plugin nginx-helper  [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
```

**Comment by VirtuBox** [comment]
Hello @dingman,
have you installed the `--mysqlclient` stack ? 
otherwise, WordOps will not be able to check MySQL remote server connection and will install MySQL stack : https://docs.wordops.net/how-to/remote-mysql-server/

**Comment by dingman** [comment]
@VirtuBox yes I did.

It works as expected in 3.11.2, however in 3.11.4 (maybe 3.11.3, not sure), it fails.

Each time in >=3.11.3, it overwrites the [client] settings in my.cnf

**Comment by dingman** [comment]
Also, it could be misleading to users, showing that this is on "localhost" when running "wo info"

```
MySQL (10.3.21-MariaDB) on localhost:

port                             3306
wait_timeout                     28800
interactive_timeout              28800
max_used_connections             8
datadir                          /rdsdbdata/db/
socket                           /tmp/mysql.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
```

Might be helpful to note that there is no local MySQL running and that it's a remote server

**Comment by VirtuBox** [comment]
Issue has been fixed in the latest release.
