### ISSUE TITLE
Feature Request: Use existing PHP version installed

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#235]
I only have --php74 installed on my host.

When I created a new site, like below, it installed php72, even though I didn't want it to.

```
root@ip-172:~# wo site create mydomain.com --wp --vhostonly
Adding repository for PHP, please wait...
Updating apt-cache              [OK]
Installing APT packages         [OK]
Configuring php7.2-fpm
Restarting php7.2-fpm           [OK]
Running pre-update checks       [OK]
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             [Done]
Configuring WordPress           [OK]
Installing WordPress            [OK]
Installing plugin nginx-helper  [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Successfully created site http://mydomain.com

```

The idea is that WordOps would detect that php74 is the only version installed and use that as the default. Another idea, would be to be able change the "default" for PHP versions to be a specific version instead of the provided 7.2. Such as wo set php --php74 and it would default to php74 instead of 72.

**Comment by vasiler** [comment]
Use flag --php74 when you create a site. You can remove php7.2 using `wo stack remove --php72` or `wo stack purge --php72` if you don't use php 7.2.

**Comment by dingman** [comment]
Correct, that's what I did. It's simply annoying that it would install php72 when I purposely don't have it installed in the first place. Being able to set a default would make it a better user experience, than having to remember every single time.

**Comment by vasiler** [comment]
It's an idee a newer to older checker when you create a site and php flag is not present:
-check if php7.4 is installed - then use php 7.4, else
-check if php7.3 is installed - then use php 7.3 else
use php 7.2

**Comment by michacassola** [comment]
![image](https://user-images.githubusercontent.com/19753510/72006250-81d13c80-324f-11ea-87f8-2727247dcfed.png)

**Comment by michacassola** [comment]
![image](https://media.giphy.com/media/vCGxbll1ySKdi/source.gif)

**Comment by VirtuBox** [comment]
Hello @dingman, 
if the solution seems to be simple, the implementation isn't. 
Because WordOps use a dedicated function to detect what php version it should use when creating a site, and another one to check if packages are installed depending on this previous choice. 
So checking at the same time what php packages are installed and what php version should be used will add a lot of complexity without making it easier to understand IMHO.
And for previous EasyEngine users, it will probably create a confusion because if only PHP 7.4 is installed and you want to create a PHP 7.2 site, you will have to add the `--php72` flag, when it was not required previously.

**Comment by garrettcam** [comment]
perhaps having a default php version 72, 73 or 74 in wo.conf could be a way forward. 
This way those who want to set a default php version can, while it could come shipped with php72 for previous EasyEngine users.
I note that 22222 has php72 hard coded in the nginx conf, this could use the default setting from wo.conf file.

**Comment by dingman** [comment]
That sounds like a viable interim solution, I like it

**Comment by VirtuBox** [comment]
I'm going to set the default php version to PHP 7.3 soon because it's the current stable PHP release, 
but it will require a little bit more time to refactor php version management in WordOps because we are still using functions from EasyEngine v3 previously used only to handle PHP 5.6 & 7.0.
