### ISSUE TITLE
Feature Request: Host override when issuing SSL, or allow self-signed cert

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#236]
I am migrating a production site from its original hosting environment, and the site is already running on SSL.

However, when I'm importing the content through the UpDraft plugin (among other plugins I've tested), it updates my domain to use SSL. And the domain is not setup for SSL yet because the domain hasn't yet moved.

I also can't use Cloudflare DNS, since the IP address is still pointing to the current hosting environment.

While uploading the content, it now times out because it's redirect all traffic to https://domain.com which isn't being listened to by nginx because SSL is disabled. I also can't enable SSL for it.

What I'm looking for, is a temporary way to either enable LE on the new staging area for the domain while I'm prepping it before the DNS change, or a way to enable self-signed cert which would at least let nginx be listening on SSL for it. Want to avoid any custom editing of nginx files for consistency and ease of use.

**Comment by VirtuBox** [comment]
Hello @dingman,
Let's Encrypt DNS API validation do not require to point the domain to the server IP. That's the main benefits of this challenge. 
So you should be able to issue your certificate on the new server, even if the site is still running on the previous hosting environnement.

**Comment by dingman** [comment]
@VirtuBox that makes sense. I would rather use an API Token though, instead of an API Key, so I can limit the permissions of what this can do. Is there a way to configure WO to use a Token instead of a global API Key?

**Comment by VirtuBox** [comment]
You can use the API Token instead of the API Key, just use : 
```bash
export CF_Token="sdfsdfsdfljlbjkljlkjsdfoiwje"
export CF_Account_ID="xxxxxxxxxxxxx"
```
instead of 
```bash
export CF_Key="sdfsdfsdfljlbjkljlkjsdfoiwje"
export CF_Email="xxxx@sss.com"
```
