### ISSUE TITLE
Command wo secure --port

### ISSUE THREAD

**Issue by LotusJeff** [WordOps/WordOps#239]
In wo/cli/plugins/secure.py makes changes to line 5 in the /etc/nginx/sites-available/22222 file. The line is:

 ` listen {port} default_server ssl http2;`

The update should also make an update to line 11:

`error_page 497 =200 https://$host:22222$request_uri;`

minor fix.

**Comment by VirtuBox** [comment]
Hello @LotusJeff,

thanks for your report. I will update the template to fix this issue.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`.
