### ISSUE TITLE
Feature Request: W3 Total Cache (W3TC) native support

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#241]
I've been testing a new setup using W3TC and have been extremely happy with it's integration with Redis. I find it's easier to manage since there is regular garbage collection and a tool to manage the redis cache.

I am requesting that you add back, native support and optimization for W3TC please.

Thank you

**Comment by nemfoz** [comment]
I agree with this. Especially with websites that have strong use of the REST API, W3TC handles it better.
