### ISSUE TITLE
Bug: WO installs php and redis, even when using remote redis server

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#245]
I updated my site tonight from nocaching WP, to --wpredis, and it automatically installed php72 and a redis server. Even though I have a remote server configured in upstream.conf

```
root@ip-172-:/etc/nginx/conf.d# wo site update domain.net --wpredis
Adding repository for PHP, please wait...
Adding repository for Redis, please wait...
Updating apt-cache              [OK]
Installing APT packages         [OK]
Configuring php7.2-fpm
Restarting php7.2-fpm           [OK]
Tuning Redis configuration      [OK]
Restarting redis-server         [OK]
Running pre-update checks       [OK]
Backup location : /var/www/domain.net/backup/19Jan2020-01-36-05
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Setting plugin nginx-helper     [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
```

**Comment by VirtuBox** [comment]
Hello @dingman,
yes, if WordOps check if there is already a MySQL server available, it doesn't check if there is a remote redis-server available. And I do not have a solution to identify and check a remote redis-server at the moment.

**Comment by dingman** [comment]
@VirtuBox as suggested in the forums by someone, there is a config option in upstream.conf that you can set remote Redis server. Can you check to see if value there exists already before installing Redis server?
