### ISSUE TITLE
Feature Request: NGINX Geolocation

### ISSUE THREAD

**Issue by cfelicio** [WordOps/WordOps#247]
Matomo supports fast geolocation with NGINX: https://matomo.org/docs/geo-locate/

But it requires the geoip2 module to be compiled on NGINX: https://github.com/leev/ngx_http_geoip2_module/blob/master/README.md#installing

Any chance this can be added to WordOps at some point?

**Comment by VirtuBox** [comment]
Hello @cfelicio, 
I will have to build a new Nginx debian package as soon as the next Nginx stable release is published, 
so it should not be a problem to add the geoip2 module.
I will keep you update when I will start working on the new Nginx debian package.

**Comment by tersor** [comment]
I was investigating traffic stats with geolocation, and became aware of the need for the geoip2 module. Adding this module would be very nice.
