### ISSUE TITLE
update failed tried reinstalling now, wo: command not found

### ISSUE THREAD

**Issue by Absorb13** [WordOps/WordOps#250]
And worried there is more broken I am not aware of yet.
All started with wo update error
URL can't contain control characters. '/WordOps/WordOps/master /install' (found at least ' ')
Poked around a bit then reran the local install script. 
wo: command not found

went to wordops site for troubleshooting.

ran wget -qO wo wops.cc && sudo bash wo

wo: command not found

Tried to source
source /etc/bash_completion.d/wo_auto.rc
wo: command not found

reboot
wo: command not found

sudo rm /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo
directory doesnt exist

This seems like a silly issue but I don't know why I cannot get back to normal functionality.
Any insight greatly appreciated and thank you for this awesome software where can I donate?

System Information

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

wo: command not found

nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

wo: command not found

OS:	Linux 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.2
php.ini used:	/etc/php/7.4/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/home/wayne
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

https://transfer.vtbox.net/7WaUV/wordops.txt

> Welcome to WordOps install/update script v3.11.4
> 
> Installing wo dependencies	[OK]
> Installing WordOps	[KO]
> Running post-install steps	[OK]
> wo: line 755: wo: command not found
> WordOps (wo) installed successfully

**Comment by Absorb13** [comment]
> :/usr/local/bin$ ls
> 
> activate-global-python-argcomplete  KernelUpdate.desktop         python-argcomplete-check-easy-install-script
> chardetect                          KernelUpdateScriptGenerator  python-argcomplete-tcsh
> composer                            pip                          register-python-argcomplete
> distro                              pip3                         wheel
> easy_install                        pip3.5                       wp
> easy_install-3.5                    pystache
> KernelUpdateChecker                 pystache-test

wo executive missing?

**Comment by VirtuBox** [comment]
Hello @Absorb13,
after rebooting, you should be able to reinstall WordOps but if `wo` executable doesn't exist, the command `sudo rm /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo` will not work (`&&` only perform next command if the previous one was successful).

But to make sure there isn't another problem, can you try the following command ?  
```bash
sudo python3 -m pip install -U wordops
```

**Comment by Absorb13** [comment]
Thank you so much for the help.

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9kjmg52v/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8ltu0t22-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-9kjmg52v/psutil/
You are using pip version 8.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

pip won't update.

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
ImportError: No module named 'pip._internal'

**Comment by Absorb13** [comment]
I managed to get it working.

Had to reinstall pip with easyinstall
and then
sudo apt-get --reinstall install libc6 libc6-dev
and your suggestion worked.

Thank you so much for your hard work.
