### ISSUE TITLE
Upgrading stacks led to 502 Bad Gateway

### ISSUE THREAD

**Issue by majiix** [WordOps/WordOps#252]
Hi,
I just ran `wo stack upgrade` and got this message:

```
Updating APT cache              [OK]
Adding repository for NGINX, please wait...
Oops Something went wrong!!
Check the WordOps log for more details `tail /var/log/wo/wordops.log` and please try again...
```

after running `tail /var/log/wo/wordops.log` i got this:

```
dpkg: error processing package php7.3-fpm (--configure):
 installed php7.3-fpm package post-installation script subprocess returned error exit status 126
Processing triggers for systemd (237-3ubuntu10.33) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Errors were encountered while processing:
 php7.3-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)
2020-02-01 19:08:37,470 (INFO) wo : Oops Something went wrong!!
2020-02-01 19:08:37,470 (ERROR) wo : Check the WordOps log for more details `tail /var/log/wo/wordops.log` and please try again...
```

What is the problem and what should i do? Please help

**Comment by majiix** [comment]
Something is wrong with php7.3-fpm and the latest update.

**Comment by geckoseo** [comment]
> Something is wrong with php7.3-fpm and the latest update.

Same. With 7.3 in use all links in the WO Dashboard aside from Nginx VTS lead to 503 "Bad Gateway".

**Comment by rsmith4321** [comment]
I'm actually having the same problem, I'm getting 502 Bad Gateway after the update.

**Comment by Slapbox** [comment]
Very possibly this issue is caused by https://github.com/WordOps/WordOps/issues/256

I was seeing the same issues, checked my Nginx logs, saw the upstream was MIA, and upon further investigation found that the sockets that are requested are not the same name as the socket files that are present on the filesystem. I had to symlink them.
