### ISSUE TITLE
Feature Request: add nginx header to listen for HTTP_CF_CONNECTING_IP

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#253]
I discovered that Amazon ELB modifies the header from Cloudflare, so it passes over "HTTP_CF_CONNECTING_IP" instead of "CF-Connecting-IP"

I am requesting that this field also be added as a real_ip_header in cloudflare.conf

**Comment by dingman** [comment]
This seems like a viable solution to resolve the need for multiple headers

https://www.getpagespeed.com/server-setup/nginx/how-to-use-multiple-real-ip-headers-with-nginx

**Comment by dingman** [comment]
Running into similar issues with fail2ban, seems like both nginx and fail2ban could use another hook due to Amazon ELB modifying the header key

**Comment by VirtuBox** [comment]
Hello @dingman,
For such simple changes in WordOps templates, that would be great to create a pull request with the requested modifications, so I will just have to test it before merging it. 
Otherwise, I will probably not work on this in the next few weeks because I'm currently refactoring the  php stack management in WordOps.

**Comment by dingman** [comment]
Looks like it might be a bit more complicated, but I'll keep at it. I've never submitted a PR before, but I'll also try my hand at my first.

**Comment by VirtuBox** [comment]
Here the related template file : https://github.com/WordOps/WordOps/blob/master/wo/cli/templates/cloudflare.mustache

You can edit it directly from GitHub and it will automatically fork the repository to give you the ability to open a pull request.

**Comment by dingman** [comment]
We can actually close this.

After speaking with the fine folks in #nginx on freenode, they conveyed that I needed to add the Amazon LB as a "set_real_ip_from" source. So I grabbed my internal IP from my VPC and set that at the top of cloudflare.conf and now it's working as desired.

**Comment by dingman** [comment]
Again, we can close this, here is the solution I found for the problem I was having: https://www.jonathan.vc/tech/2020/02/cloudflare-amazon-load-balancer-nginx-fail2ban

**Comment by dingman** [comment]
@VirtuBox I think best if we close this, it's not necessary as I found out.
