### ISSUE TITLE
Error:"wo: command not found"  after WO Update

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#255]
Hello @VirtuBox ,

After update Wordops to version v3.11.4, it will show:" wo: command not found" when using any wordops command line.

In this case, both both of the following command lines will not work either:
```
sudo rm /usr/local/bin/wo
sudo rm /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo

```
and it will show: 
`rm: cannot remove '/usr/local/bin/wo': No such file or directory`

For detailed information about this issue, please check both the following url on your official site:

https://chat.wordops.net/channel/general?msg=aJDQ2CiunkTCETkN9
https://community.wordops.net/d/191-error-after-wo-update

Please check the System Information below:

- [ ] `lsb_release -a`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
- [ ] `wo info`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# wo info
wo: command not found
- [ ] `nginx -V`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# nginx -V
nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-xSli4x/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-xSli4x/nginx-1.16.1/debian/modules/ngx_brotli
- [ ] `wo -v`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# wo -v
wo: command not found
- [ ] `wp cli info --allow-root`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# wp cli info --allow-root
OS:     Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.2
PHP version:    7.2.27-6+ubuntu18.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.2/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
root@ubuntu-s-2vcpu-4gb-lon1-01:~# curl -sL git.io/fjAp3 | sudo -E bash -

Here the link to provide in your github issue : https://transfer.vtbox.net/YS3Hi/wordops.txt

**Comment by alexlii1971** [comment]
Hello @VirtuBox ,

Just did a fresh install on Mac Parallels Virtual machine with Ubuntu 16.04, and it seems same issue, please check the screenshot:

http://prntscr.com/r2yqr2

In this case, I can not install Wordops actually.

**Comment by alexlii1971** [comment]
Same issue if GitHub repository used by command line:

```
git clone https://github.com/WordOps/WordOps.git
cd WordOps/
sudo bash install
```
Please check the screenshot:
http://prntscr.com/r2z02j

**Comment by ryan-wong** [comment]
Any update on this @VirtuBox? 
/usr/local/bin/wo file doesn't exist

**Comment by bobwol** [comment]
Still running this issue with wo 3.11.4 and Ubuntu 18.04

Any way to install wo manually on /usr/local/bin/, that solve this issue?

**Comment by VirtuBox** [comment]
Hello, I'm working on this issue.
At the moment, you can use the following command to fix this issue : 

```bash
sudo python3 -m pip install -I wordops
```

**Comment by bobwol** [comment]
great!

**Comment by terpelajar** [comment]
Hello, I'm working on this issue.
At the moment, you can use the following command to fix this issue :
`sudo rm -f /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo`
