### ISSUE TITLE
All php suddenly missing from stack

### ISSUE THREAD

**Issue by mbahgugel-tech** [WordOps/WordOps#266]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
==================================

I just move from EE to WO about 3 month ago...and I like it very well and all goes smoothly. I have about 13 wordpress blog installed and I'm very happy that all running well. Until today, I got report from my web stats that my blog is currently down and I have checked from vps monitor that everything is ok (running).
When I check my wo stats, there just only mysql is running but all php (72,73,74) is all gone...

Please help...I'm newbie to this and  I don't have a backup for all my sites :((

**Comment by vikas5914** [comment]
@mbahgugel-tech Pleases run the following command and post the result:

- [ ] lsb_release -a
- [ ] wo info
- [ ] nginx -V
- [ ] wo -v
- [ ] wp cli info --allow-root
- [ ] curl -sL git.io/fjAp3 | sudo -E bash -
