### ISSUE TITLE
Query parameters missing when caching with wpsc

### ISSUE THREAD

**Issue by gormv** [WordOps/WordOps#267]
When running with WPSC caching, $_REQUEST is not populated, those breaking all cached content that passes a query parameter.

I assume it's broken by the ref #330 but I don't understand how passing query string parameters could break WooCommerce? Could it be a misunderstanding and that it's missing $is_args before $args?

````
$ more /etc/nginx/common/wpsc-php73.conf 
 WPSC NGINX CONFIGURATION - WO v3.9.7
# DO NOT MODIFY, ALL CHANGES WILL BE LOST AFTER AN WordOps (wo) UPDATE
# $cache_uri variable set in /etc/nginx/conf.d/map-wp.conf

# Use cached or actual file if they exists, Otherwise pass request to WordPress
location / {
  # If we add index.php?$args its break WooCommerce like plugins
  # Ref: #330
  try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php;
}
location ~ \.php$ {
  try_files $uri =404;
  include fastcgi_params;
  fastcgi_pass php73;
  # Following line is needed by WP Super Cache plugin
  fastcgi_param SERVER_NAME $http_host;
}

$ more /etc/nginx/common/php73.conf 
# PHP NGINX CONFIGURATION - WO v3.9.7
# DO NOT MODIFY, ALL CHANGES WILL BE LOST AFTER AN WordOps (wo) UPDATE
location / {
  try_files $uri $uri/ /index.php$is_args$args;
}
location ~ \.php$ {
  try_files $uri =404;
  include fastcgi_params;
  fastcgi_pass php73;
  add_header "vary" "Accept-Encoding, Cookie";
}

**Comment by Richzendy** [comment]
The same problem here, any query param on url is not working with wp-supercache, i need to switch to wpfc my site to get this working.

**Comment by gormv** [comment]
@Richzendy I don't recall exactly, as I ended the project, but I did some benching and ended running with  --wpfc

If you have a large site or need more speed, then I would investigate --wpredis as well.

But speed I got was much better than with any (free) plugin.

**Comment by stodorovic** [comment]
Yes, it's missing `$is_args$args`. Correct rules should be almost same as for wp-rocket:

```
try_files /wp-content/cache/supercache/$http_host/$cache_uri/index${mobile_prefix}${https_prefix}.html /wp-content/cache/supercache/$http_host/$cache_uri/index${https_prefix}.html $uri $uri/ /index.php$is_args$args;
```

I'm using them last few months and I didn't see any issues. I'll try to create PR when I catch a spare time.
