### ISSUE TITLE
Certificate not found. Deployment canceled when issuing LetsEncrypt cert

### ISSUE THREAD

**Issue by CobblerSalad** [WordOps/WordOps#273]
This use to work a few months ago. If I create a new subdomain and try to issue a letsencrypt certificate to it (wo site create sub.domain.com --le --dns=dns_cf) the logs show it is created sucessfully, shows where the cert is located (/etc/letsencrypt/config/sub.domain.com_ecc/sub.domain.com.cer) but then errors out with Certificate not found. Deployment canceled.

System Information

- [Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco ] `lsb_release -a`

- [NGINX (1.16.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 7.2 is not installed

MySQL (10.3.22-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             1
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf ] `wo info`

- [nginx version: nginx/1.16.1 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-yZZjue/nginx-1.16.1=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_v2_hpack_enc --with-http_auth_request_module --with-openssl-opt='enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --without-http_memcached_module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-echo --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/memc-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/HttpRedisModule --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/nginx-module-vts --add-module=/build/nginx-yZZjue/nginx-1.16.1/debian/modules/ngx_brotli ] `nginx -V`
- [WordOps v3.11.4 ] `wo -v`
- [OS:     Linux 5.3.10-1-pve #1 SMP PVE 5.3.10-1 (Thu, 14 Nov 2019 10:43:13 +0100) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.3
PHP version:    7.3.14-1+ubuntu19.04.1+deb.sury.org+1
php.ini used:   /etc/php/7.3/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /etc/letsencrypt/live
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0 ] `wp cli info --allow-root`
- [https://transfer.vtbox.net/fUZt2/wordops.txt ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by VirtuBox** [comment]
Hello @CobblerSalad, 
thanks for your report, I'm going to investigate on this issue.

**Comment by CobblerSalad** [comment]
If it helps at all, here's what I've been doing to fix it (using nextcloud as an example). It seems to only happen on new subdomains I create.

cd /var/www/nextcloud.domain.com/conf/nginx/

mkdir /etc/letsencrypt/live/nextcloud.domain.com/

cp /etc/letsencrypt/config/nextcloud.domain.com_ecc/ca.cer /etc/letsencrypt/live/nextcloud.domain.com/ca.pem
cp /etc/letsencrypt/config/nextcloud.domain.com_ecc/nextcloud.domain.com.key /etc/letsencrypt/live/nextcloud.domain.com/key.pem
cp /etc/letsencrypt/config/nextcloud.domain.com_ecc/fullchain.cer /etc/letsencrypt/live/nextcloud.domain.com/fullchain.pem

nano ssl.conf

listen 443 ssl http2;
listen [::]:443 ssl http2;
ssl_certificate /etc/letsencrypt/live/nextcloud.domain.com/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/nextcloud.domain.com/key.pem;
ssl_trusted_certificate /etc/letsencrypt/live/nextcloud.domain.com/ca.pem;
ssl_stapling_verify on;

**Comment by janiosarmento** [comment]
For some reason I can't understand, it seems `acme.sh` is not generating the `cert.pem` file, which WO expects in a certain place, in order to deploy the certificate (and to check cert validity too).

A server of mine with 41 domains had 13 facing such an issue, and when I try to issue and install the certificates manually there are `domain.com.cer`, `domain.com.key`, `ca.cer` and `fullchain.cer` files, no `.pem`.

**Comment by janiosarmento** [comment]
As an improvised patch I'm using the script below, based on @CobblerSalad's valuable information. It is not meant for usage but on emergencies, of course, but it may save some lifes while the issue does not get covered by WO itself.

```bash
D=$1

woQuery(){
   DB="/var/lib/wo/dbase.db"
   sqlite3 "$DB" "$1"
}

if [ ! -z $D ] ; then
    mkdir -p /etc/letsencrypt/live/$D/

    cp /etc/letsencrypt/config/${D}_ecc/ca.cer /etc/letsencrypt/live/${D}/ca.pem
    cp /etc/letsencrypt/config/${D}_ecc/${D}.key /etc/letsencrypt/live/${D}/key.pem
    cp /etc/letsencrypt/config/${D}_ecc/fullchain.cer /etc/letsencrypt/live/${D}/fullchain.pem  
    cp /etc/letsencrypt/config/${D}_ecc/fullchain.cer /etc/letsencrypt/live/${D}/cert.pem  

    woQuery "update sites set is_ssl=1 where sitename='${D}'"

    echo "
listen 443 ssl http2;
listen [::]:443 ssl http2;
ssl_certificate /etc/letsencrypt/live/${D}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${D}/key.pem;
ssl_trusted_certificate /etc/letsencrypt/live/${D}/ca.pem;
ssl_stapling_verify on;
    " > /var/www/${D}/conf/nginx/ssl.conf

    service nginx reload
fi
```

The script is meant to be run by root user; I never tried it with sudo, but it should work, I guess.

**Comment by joeyblake** [comment]
I am having the same issue. Running WordOps v3.12.2 I have migrated from EasyEngine, so perhaps that has something to do with it.

It seems that the _ecc directory is created in "config"
`/etc/letsencrypt/config/nextcloud.domain.com_ecc/`

But the script is looking for the certificates in "renewal"
`/etc/letsencrypt/renewal/nextcloud.domain.com_ecc/`

I copied the entire nextcloud.domain.com_ecc directory into the "renewal" directory 

`cp -r /etc/letsencrypt/config/nextcloud.domain.com_ecc /etc/letsencrypt/renewal/nextcloud.domain.com_ecc`

and can successfully run

`wo site update nextcloud.domain.com --le`

**Comment by Sl1nkman** [comment]
I have been experiencing this on all domains
Server config:
 20.04.2 LTS (GNU/Linux 5.4.0-1036-gcp x86_64)
 
 Using the Acme.sh version 2.9.0 due to this [bug ]( https://community.wordops.net/d/1025-your-domain-is-properly-configured-but-acmesh-was-unable-to-issue-certificate -- 
 )

 The script above does help with little modification

**Comment by Sl1nkman** [comment]
When trying to update the SSL on a site:
sudo wo site update microphonewindshields.com -le --force

Result:
Certificate type : domain
Validation mode : Webroot challenge
Issuing SSL cert with acme.sh   [OK]
Certificate not found. Deployment canceled

Log Data:
[Fri Dec 10 07:34:19 UTC 2021] Your cert is in  /etc/letsencrypt/config/microphonewindshields.com_ecc/microphonewindshields.com.cer
[Fri Dec 10 07:34:19 UTC 2021] Your cert key is in  /etc/letsencrypt/config/microphonewindshields.com_ecc/microphonewindshields.com.key
[Fri Dec 10 07:34:19 UTC 2021] The intermediate CA cert is in  /etc/letsencrypt/config/microphonewindshields.com_ecc/ca.cer
[Fri Dec 10 07:34:19 UTC 2021] And the full chain certs is there:  /etc/letsencrypt/config/microphonewindshields.com_ecc/fullchain.cer
,
Command Error: ^[[0m
^[[32m2021-12-10 07:34:19,902 (INFO) wo : ^[[92mIssuing SSL cert with acme.sh^[[0m
^[[31m2021-12-10 07:34:19,902 (ERROR) wo : ^[[91mCertificate not found. Deployment canceled^[[0m

I am currently still using this bash script

#!/bin/bash
read D

woQuery(){
   DB="/var/lib/wo/dbase.db"
   sqlite3 "$DB" "$1"
}

if [ ! -z $D ] ; then
    mkdir -p /etc/letsencrypt/live/$D/

    cp /etc/letsencrypt/config/${D}_ecc/ca.cer /etc/letsencrypt/live/${D}/ca.pem
    cp /etc/letsencrypt/config/${D}_ecc/${D}.key /etc/letsencrypt/live/${D}/key.pem
    cp /etc/letsencrypt/config/${D}_ecc/fullchain.cer /etc/letsencrypt/live/${D}/fullchain.pem  
    cp /etc/letsencrypt/config/${D}_ecc/fullchain.cer /etc/letsencrypt/live/${D}/cert.pem  

    woQuery "update sites set is_ssl=1 where sitename='${D}'"

    echo "
listen 443 ssl http2;
listen [::]:443 ssl http2;
ssl_certificate /etc/letsencrypt/live/${D}/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/${D}/key.pem;
ssl_trusted_certificate /etc/letsencrypt/live/${D}/ca.pem;
ssl_stapling_verify on;
    " > /var/www/${D}/conf/nginx/ssl.conf

    service nginx reload
fi

This successfully sets up the ssl that WO is currently failing to do

**Comment by Sl1nkman** [comment]
@VirtuBox 
I have been experiencing this issue since Jun 22 2021

Is there any way I can assist you in troubleshooting this issue?

**Comment by inspiredearth** [comment]
I'm also having this issue. On an existing site. Certificate failed to update automatically (after around a year of it being fine). When trying to update it myself, I get the `Certificate not found. Deployment canceled` error, after the certificate is successfully generated. So WordOps aborts and doesn't take the steps necessary to finish the SSL configuration.

**Comment by wcatz** [comment]
Seem to be running into this on 32 bit arm container with subdomain. 403 forbidden. Certs generated but not utilized.

**Comment by alexdhika** [comment]
simple, you just need add this row to /etc/letsencrypt/config/account.conf

`CERT_HOME='/etc/letsencrypt/renewal'`
