### ISSUE TITLE
Improve documentation: How to disable css/js nginx cache while developing

### ISSUE THREAD

**Issue by crystaler4** [WordOps/WordOps#277]
Hi,
this is tip how to disable css/js nginx cache while developing. Open in terminal `nano /etc/nginx/site-available/example.com` and place right before last `}` this code:

```
location ~* \.(css|js)$ {
    expires 0;
    break;
}
```
then using console restart nginx:
`nginx -t`
`wo stack restart`

**Comment by crystaler4** [comment]
Ok, it is not working anymore. [Code](https://github.com/WordOps/WordOps/issues/277#issue-612040232) simply stop working. Strange but ok. What is my setup:

In `/etc/nginx/site-available/example.com` I have replaced line 

`include common/locations-wo.conf;`
with
`include common/locations-wo-dev.conf;`

while `common/locations-wo-dev.conf` was changed `Cache css & js files` to:

```
# Cache css & js files
location ~* \.(?:css(\.map)?|js(\.map)?)$ {
    more_set_headers 'Access-Control-Allow-Origin : *';
    more_set_headers  "Cache-Control : no-cache";
    access_log off;
    log_not_found off;
    expires -1;
}

```
1. I have set disable cache in [Chrome and Firefox](https://nicholasbering.ca/tools/2016/10/09/devtools-disable-caching/). 

2. I'm reloading Chrome "[Empty cache and hard reload](https://stackoverflow.com/a/52275910)" way. 

3. I use `time()` function at the end of `https://www.example.com/wp-content/themes/theme/style.css?ver=1588615637`

Changes are uploaded to server, I can see them over the console but it sill takes time while they appear in both browsers.

This f. caching is slowing me down, I am desperate.

**Comment by crystaler4** [comment]
This is response header of edited style.css:

access-control-allow-origin: *
**cache-control: max-age=2592000**
content-encoding: gzip
content-type: text/css
date: Mon, 04 May 2020 19:01:12 GMT
**etag: W/"5eb06606-3ed6"**
expires: Wed, 03 Jun 2020 19:01:12 GMT
last-modified: Mon, 04 May 2020 18:59:18 GMT
referrer-policy: no-referrer, strict-origin-when-cross-origin
server: nginx
status: 200
vary: Accept-Encoding
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block

These are my current `Cache css & js files` directives:

```
# Cache css & js files
location ~* \.(?:css(\.map)?|js(\.map)?)$ {
    sendfile off;
    more_set_headers 'Access-Control-Allow-Origin : *';
    more_set_headers  "Cache-Control : no-cache";
    access_log off;
    log_not_found off;
    expires -1;
        if_modified_since off;
        expires off;
        etag off;

}
```
Despite directives for css, `etag` + `cache-control` are still present.

**Comment by crystaler4** [comment]
After 3 hours of digging I finally found it is f***ing [provider](https://refreshyourcache.com/en/cache/). When I connect over my mobile phone Nginx with such configuration (`Cache css & js files`) works as expected. 

**So back to original request:** Please create some documentation (or I will do it - where?) how to disable css/js cache while developing.

**Comment by dingman** [comment]
All documentation is open source, feel free to submit a PR.

https://docs.wordops.net/

Click on the "edit" icon in the middle of the screen.

I do suggest you don't include any vulgar language in the documentation, as that wouldn't be accepted.

**Comment by crystaler4** [comment]
> Click on the "edit" icon in the middle of the screen.

I will do it when I will find reason why is caching still on. The provider-track turned out to be incorrect, caching is still there. Need to do more test (proxy, linx, different desktop, operating system).

> I do suggest you don't include any vulgar language in the documentation, as that wouldn't be accepted.

Yes, of course. I was angry yesterday.
