### ISSUE TITLE
wo systemd service failing

### ISSUE THREAD

**Issue by devbhosale** [WordOps/WordOps#278]
WO systemd service fails to start.

I had the same issue referred here:
https://github.com/WordOps/WordOps/issues/255

I ended up installing using pip solution in above issue URL.

![image](https://user-images.githubusercontent.com/520223/81603640-ad4e6a00-939c-11ea-8485-7df5e06b5f7d.png)

System Information

- [ ] `lsb_release -a`
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

- [ ] `wo info`
sudo wo info

NGINX (1.18.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1

PHP (7.2.30-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
https://transfer.vtbox.net/CBJXL/wordops.txt

**Comment by VirtuBox** [comment]
Hello @devbhosale,
thanks for your report. I already pushed a fix and it will be available in the next few days with the next stable release.
