### ISSUE TITLE
Error Page Wordops

### ISSUE THREAD

**Issue by DrinkoLee** [WordOps/WordOps#281]
Hello friends, good night, I have a problem ... all my sites overnight presented this error, can someone help me?
https://prnt.sc/sge7zq

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ x] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by vikas5914** [comment]
I think you need to remove apache from your server

**Comment by DrinkoLee** [comment]
I did that apparently it solved and another problem appears.

So I went to look at the terminal and tried the restart command, and 'msql is not installed' appeared, so I asked myself, but how was everything normal until yesterday?

so i went to install mysql again and it gives an error, can someone help me? he asks to go to the log and I went to the log and asks to execute the command "You can run 'apt-get -f install' to fix these:" I ran the command and it still didn't work

1. https://prnt.sc/sg6j76
2. https://prnt.sc/sg6luv
3. https://prnt.sc/sg6mh5
