### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1463: invalid continuation byte

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#284]
I've found a very rare bug on WO, related to Let's Encrypt.

The symptom: any operation related to LE raises:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 1463: invalid continuation byte`

This is a fatal error, and it is impossible to do any LE operations anymore.

Digging into the issue I discovered that this condition only happens on systems with locale define to Portuguese (or any other which uses accented characters in names of days of the week).

WO saves a CSV containing information about the certificates installed on the server:

`/var/lib/wo/cert.csv`

The problem occurs when a cert is issued on a saturday ("sábado" in Portuguese), and the sequence `sáb` is saved in the CSV.

WO saves the file without forcing utf-8 encoding, but when it tries to read the CSV it forces decoding to utf-8, and such a  mismatch raises the error.

**Comment by VirtuBox** [comment]
Hello @janiosarmento,
thanks for your report, I will fix this by forcing utf-8 when writing CSV file.

**Comment by rslonik** [comment]
Got this error today.

`/etc/letsencrypt/acme.sh --list --listraw` prints ISO-8859 encoded to `/var/lib/wo/cert.csv` as @janiosarmento previously spotted:

`site.com|"ec-384"|no|ter mai 19 03:00:20 UTC 2020|s�b jul 18 03:00:20 UTC 2020`

Then `/usr/local/lib/python3.6/dist-packages/wo/core/acme.py` (line 214) tries to read as UTF-8 and fails.

Changing from `utf-8` to `iso-8859-1` in this file is a workaround.

**Comment by rslonik** [comment]
Que zica, meu safari não sei pq não tava mostrando erro. Mas consegui reproduzir no Chrome. Aí foi um parto pra descobrir o problema, que no fim das contas era a autorização com senha, o servidor do certificado não conseguia confirmar o endereço por isso. Agora está ok, finalmente.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
