### ISSUE TITLE
Suggestion: command line options for database name, credentials and WP table prefix

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#286]
I'd like to suggest a feature that would allow automation of backups (restorations actually) and make migrations much easier: CLI options to define database name, database username, database password and WordPress table prefix.

something like:

```bash
wo site create example.com --wpredis --php74 --le \
  --db-name=example_com_fe6d \
  --db-username=examplecodsmlKw \
  --db-password=dYThYzzM1mTDZJ3hgG2ZYMMk
````

Thanks!

**Comment by tersor** [comment]
I prefer to use the database root user for backup gymnastics. This way you do not have to worry about per site db credentials.

Another option is to use wp cli.

**Comment by janiosarmento** [comment]
@tersor, I appreciate that you share your point of view, but I'm afraid our needs are not equal, and I really need to be able to recreate the domain with exactly the same database credentials when restoring it.
