### ISSUE TITLE
Robots.txt not editable via Hook Filter "robots_txt"

### ISSUE THREAD

**Issue by Overflow992** [WordOps/WordOps#289]
hi, I have a multi-domain site so I wanted to have a robots.txt file for each sub-domain, but I noticed that using the Wordpress filter "robots_txt" did not work, this is due to the fact that Wordops retrieves the contents of the robots.txt file from the file "/etc/nginx/common/wpcommon-php73.conf"

So I tried to understand why it didn't call my function for edit Robots.txt:

```
add_filter('robots_txt', 'addToRoboText');

function addToRoboText($robotext) {
    $additions = "#New Text in Robots";
    return $robotext . $additions;
}
```

and I saw that the cause was in particular in this line of code:

```
location = /robots.txt {
# Some WordPress plugin gererate robots.txt file
# Refer #340 issue
try_files $uri $uri/ /index.php?$args @robots;
    access_log off;
    log_not_found off;
}
```

I replaced the line `try_files $uri $uri/ /index.php?$args @robots;` with `try_files $uri $uri/ /index.php?$args;`

Now when call the Hook filter `robots_txt` the content of robots.txt changes dynamically.

I would like you to take a look at this problem and see if the modified code creates problems in other areas, in this case you should try to improve the code

**Comment by alexdhika** [comment]
Up

**Comment by flschaves** [comment]
@VirtuBox this is still an issue.
