### ISSUE TITLE
Unable to activate --ngxblocker

### ISSUE THREAD

**Issue by Snadex** [WordOps/WordOps#291]
Hello everyone,
I just provisioned new Ubuntu 18.04 with the latest WordOps.

When creating the site, I added the flag --ngxblocker, which I believe did not enabled it,
and later on when I tried to update it, here is the result:

wo site update THEDOMAIN.TLD --ngxblocker

```
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 138, in default
    self.doupdatesite(pargs)
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 802, in doupdatesite
    if 'wo_db_name' in data.keys() and not data['wp']:
KeyError: 'wp'
```

Any ideas what can cause this, and how can be resolved?

Thank you :)

System Information

- [x] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

- [x] `wo info`

NGINX (1.18.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 7.2 is not installed

PHP (7.3.18-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

MySQL (10.3.23-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             6
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [x] `nginx -V`
nginx version: nginx/1.18.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1g  21 Apr 2020 (running with OpenSSL 1.1.1  11 Sep 2018)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-W7QLqg/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-echo --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/memc-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/HttpRedisModule --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/nginx-module-vts --add-module=/build/nginx-W7QLqg/nginx-1.18.0/debian/modules/ngx_brotli

- [x] `wo -v`
WordOps v3.12.2
Copyright (c) 2019 WordOps.

- [x] `wp cli info --allow-root`
OS:	Linux 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.18-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0

- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`
https://transfer.vtbox.net/mWAUC/wordops.txt

**Comment by janiosarmento** [comment]
Despite the error message, the update occurs. You may confirm it by looking at the files in the domain `conf` directory.

**Comment by Slapbox** [comment]
Same issue, except we can't disable it, which is a substantial issue for us because we need to run one of the tools that it blocks to check our links are all working after pushing a new version of our site.

**We upgraded WordOps a couple weeks ago.  I don't know for sure that the upgrade is what triggered the issue, but I can say for sure that it worked a few weeks ago on an older version.**

`wo site update oursite.com --ngxblocker=off` results in error:

```
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/plugins/site_update.py", line 138, in default
    self.doupdatesite(pargs)
  File "/usr/local/lib/python3.5/dist-packages/wo/cli/plugins/site_update.py", line 802, in doupdatesite
    if 'wo_db_name' in data.keys() and not data['wp']:
KeyError: 'wp'
```


System Information

- [x] `lsb_release -a`

```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
```

- [x] `wo info`

```


NGINX (1.18.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (7.2.31-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.4.6):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.3.23-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             7
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

```

- [x] `nginx -V`

```
nginx version: nginx/1.18.0 (WordOps Nginx-wo)
```

- [x] `wo -v`

```
WordOps v3.12.2
Copyright (c) 2019 WordOps.
```

- [x] `wp cli info --allow-root`

```
OS:     Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1+deb9u1 (2020-06-07) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.6
php.ini used:   /etc/php/7.4/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/log/nginx
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.4.0
```


- [x] `curl -sL git.io/fjAp3 | sudo -E bash -` https://transfer.vtbox.net/WKDLh/wordops.txt

@VirtuBox any ideas about this issue? Thanks for WordOps, we love it!

**Comment by patilsandeep911** [comment]
I have the exact same issue. We get same error while switching ngxblocker on or off. But the testing it after switching on works. for example:

as per [https://awesomeopensource.com/project/mitchellkrogza/nginx-ultimate-bad-bot-blocker]

# curl -I https://example.com -e http://100dollars-seo.com
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

This thing works.

**Comment by Slapbox** [comment]
@patilsandeep911 are you able to turn it off once it's on? It remains stuck on for us.

**Comment by sebastienvercammen** [comment]
Exact same issue as everyone above. Enabling/disabling via `update` triggers this error. `ngxblocker` does still get enabled/disabled.

**Comment by drdogbot7** [comment]
Same issue with a different error message. The command does still enable ngxblocker.

```bash
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Cannot update [THEDOMAIN.TLD], Invalid Options
```

Ubuntu 20.04.6 LTS
Wordops v3.18.0
