### ISSUE TITLE
How to disable open_basedir?

### ISSUE THREAD

**Issue by edneycarpinteiro** [WordOps/WordOps#292]
Hi everyone,

Please, I need to disable the open_basedir in pnp, but I don't get find it in my server with Wordops installation.

When I try to migrate my WordPress site through Duplicator plugin, a notice about the issue appears on the screen, and the archive fails.

I will be very grateful if somebody help me!

Best regards,
Edney

**Comment by tersor** [comment]
Hello.

Depending on what php version your site(s) run on, I would take a look at these config files:

```
grep -l "open_basedir" /etc/php/*/fpm/pool.d/*.conf
```

**Comment by edneycarpinteiro** [comment]
Hi, @tersor !
Thanks for your help! But, forgive me for my ignorance, should I add this code to a any file or would it be a WordOps command line?
Thank you again!
Regards

**Comment by dingman** [comment]
@edneycarpinteiro please kindly use the support forums for support questions, 

https://community.wordops.net/
