### ISSUE TITLE
mysql remote

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#295]
server01 = wordops with mysqlclient
server02 = mysqlserver

when creating a wordpress site on server01 wo does not identify that there is mysqlclient and installs mysqlserver replacing all configuration already done.

wo = v3.12.2

**Comment by dingman** [comment]
Hi @juanpvh 

Please kindly ask for support in the community forum.

You can find the solution here: https://community.wordops.net/d/482-wordops-with-a-remote-mysql-server

I personally use this for all sites and don't have any issues.

**Comment by juanpvh** [comment]
no friend, the problem is not in my configuration, when a website is created it installs mysql replacing the mysqlclient configs

**Comment by dingman** [comment]
Again, since this is not a bug, please open a thread on the community forum first. This is not the correct place for support.
