### ISSUE TITLE
wo site update example.com -le=wildcard --dns=dns_cf doesn't update wildcard ssl but only normal ssl

### ISSUE THREAD

**Issue by netherstar** [WordOps/WordOps#296]
i found a issue
`wo site update example.com -le=wildcard --dns=dns_cf` 
doesn't update wildcard ssl but only normal ssl
```
wo -v
WordOps v3.11.0
```

**Comment by VirtuBox** [comment]
Hello @netherstar, 
is the issue still exist with the latest WordOps release ?

**Comment by ibrahimhajjaj** [comment]
@VirtuBox  Yes It's

**Comment by jtnydv** [comment]
Facing the same issue
