### ISSUE TITLE
Laravel Support

### ISSUE THREAD

**Issue by miloszorica** [WordOps/WordOps#297]
Is it on a roadmap? I mean, implementing it would be fairly trivial.

**Comment by dingman** [comment]
I'm not aware of it being on the roadmap. This would easily turn into a rabbit trail though, of many people requesting different things.

You could fork this project into your own as well if you wanted to better support Laravel.

I use Laravel within WordOps already and it works great.

**Comment by janiosarmento** [comment]
Honest comment: I don't understand what people mean by "Laravel Support". Is it that WO would download and install the libraries? Or what?

**Comment by VirtuBox** [comment]
Hello @miloszorica,
Laravel should work with WordOps out-of-the-box. You just have to create a site with the flag `--mysql` before deploying laravel with composer : `sudo -u www-data -H composer create-project --prefer-dist laravel/laravel /var/www/yousite.tld/htdocs`.
The only change to make is editing your vhost to set the the root directory to /var/www/yoursite.tld/htdocs/public. You can use `wo site edit yoursite.tld`  to do so.

**Comment by vikas5914** [comment]
There is one thing. by default Laravel `.env` file has 127.0.0.1 as the Mysql host.  And the user-created with `--mysql` flag does not have permission to access via 127.0.0.1.  So you have to change the host to "localhost" in `.env`
