### ISSUE TITLE
[Feature Request] SuiteCRM app configuration

### ISSUE THREAD

**Issue by michacassola** [WordOps/WordOps#298]
Please add SuiteCRM to the Apps configuration.
https://suitecrm.com/join-the-project/always-open-source/
https://docs.suitecrm.com/admin/installation-guide/downloading-installing/
https://suitecrm.com/download/

**Comment by VirtuBox** [comment]
Hello @michacassola,
I'm working on adding custom templates support into WordOps. This way, all WordOps users will be able to build their own templates and use them to host any App with WordOps. 
So, it will be pretty easy to build a template for SuiteCRM. 
I will keep you updated about this feature release date.

**Comment by michacassola** [comment]
@VirtuBox Very relieved you are here! Thank you so much!
Looking forward to writing/making my own templates! Let me know if you need any assistance in this direction!
