### ISSUE TITLE
Postfix breaks any unattended deploy

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#3]
I'm an egress from EasyEngine, and I use it on 99% of my servers (currently 200+ servers).

I've developed a deploy script for new servers, which — among other stuff — installs EasyEngine.

Current WO installer, however, breaks any unattended install because at the very first steps it installs Postfix and a dialog (two, actually) pops up screen asking for server usage (Smart Host, Internet, and so on), and for Postfix username.

Would it be possible not to install Postfix by default, allowing late installation using `wo stack install --postfix` or `--all` command just like old EE did?

Thanks for the great job!

**Comment by janiosarmento** [comment]
Of course I can `sed` the setup script and remove the string `postfix` from it before running; it will solve my problem.

**Comment by jeroenops** [comment]
We ditched Postfix for now, going to implement [OpenSMTPd](https://www.opensmtpd.org).
