### ISSUE TITLE
Easy question: function responsible for the `wo site cd`

### ISSUE THREAD

**Issue by AdsonCicilioti** [WordOps/WordOps#306]
Hello guys!

First of all congratulations on this amazing tool.
I was intrigued about the construction of the features of this tool, especially the `wo site cd` that takes the main shell to the oo site directory.

Could you please show me what exactly does this function do? I don't know the python language, so I'm having a hard time finding it.

**Comment by renatofrota** [comment]
See [cd function at wo/cli/plugins/site.py](https://github.com/WordOps/WordOps/blob/e82985a7d0858ce1192fcb609cf6299ced24c977/wo/cli/plugins/site.py#L222).

It uses [getSiteInfo](https://github.com/WordOps/WordOps/blob/e82985a7d0858ce1192fcb609cf6299ced24c977/wo/cli/plugins/sitedb.py#L29) to read the website's directory in WO internal db, then WO's internal [chdir function](https://github.com/WordOps/WordOps/blob/e82985a7d0858ce1192fcb609cf6299ced24c977/wo/core/fileutils.py#L138) which calls `os.chdir` (Python function to change working directory) and, finally, raises a `subprocess.call(['/bin/bash'])` on that dir.

**Comment by AdsonCicilioti** [comment]
Thx @renatofrota !

I'm trying made a similar function with pure ShellScript, but isn't possible because works only on subprocess. In this case i must request a third-party solution.
