### ISSUE TITLE
Install custom php extensions

### ISSUE THREAD

**Issue by roshanjonah** [WordOps/WordOps#309]
I was wondering if anyone knew a easy safe way to configure and install PHP Extensions - I am specifically looking for PCNTL php extension which is not there in php 7.2 which I am using. Any help would be much appreciated 

System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

- [ ] `nginx -V`
nginx version: nginx/1.18.0 (WordOps Nginx-wo)

- [ ] `wo -v`
WordOps v3.12.2

**Comment by tersor** [comment]
@roshanjonah wouldnt it be **much easier** just to upgrade to php7.3 or php7.4?

Also, php7.2 is coming to an end of life in a couple of months.
https://www.php.net/supported-versions.php

**Comment by roshanjonah** [comment]
@tersor First of all, thank you for your reply! Appreciate it.

Yes! I don't mind. Not sure if the app I am using is compatible but should be okay. Is PCNTL available on php7.3 and 7.4 in wordops? If so, I will do it right away!

**Comment by tersor** [comment]
@roshanjonah yes available.

Also, you might want to edit `/etc/php/<php version>/fpm/php.ini` as it seems like some pcntl functions are disabled as default. Take a look at the `disable_functions` line.

**Comment by roshanjonah** [comment]
@tersor Unfortunately, I can't see the ini or the .so file 

<img width="2230" alt="screenshot_239" src="https://user-images.githubusercontent.com/20136098/91175765-66ab3280-e735-11ea-83f0-12c62123f9ba.png">

Any ideas where it may be or why it's not there?

**Comment by tersor** [comment]
Dont know, but is seems enabled:

```
php -i | grep "pcntl support"
pcntl support => enabled
```

**Comment by roshanjonah** [comment]
Yea not sure which version of it it's enabled for. I feel like it's not working with our software

**Comment by tersor** [comment]
1. Check what php version your site is running:

```
wo site info domain.tld
```

2. Edit `/etc/php/<php version>/fpm/php.ini` and comment out or edit the `disable_functions` line.

3. Restart php-fpm:

```
systemctl restart php<php version>-fpm.service
```

4. Test.

**Comment by roshanjonah** [comment]
Yup tried that mate, didn't seem to work. Wish there was a test PHP script we could run to see if its actually making use of those PCNTL extension

**Comment by roshanjonah** [comment]
<img width="1136" alt="screenshot_240" src="https://user-images.githubusercontent.com/20136098/91187090-e3450d80-e743-11ea-9927-9ec6b95a83e3.png">

It's not loaded so surely it won't work I think! @tersor - Its the same result with PHP 7.3 too.
