### ISSUE TITLE
erro cloudflare 520

### ISSUE THREAD

**Issue by wandercrs** [WordOps/WordOps#311]
Pessoal, 

O site está em ambiente de produção, porém está acontecendo os erros constantemente após instalar o WordOps.

version php = 7.4
Empresa da VPS: vps dime

Sempre que estou modificando layout acontece esse tipo erro.

![erro 520](https://user-images.githubusercontent.com/70917300/92414900-b5d96600-f12c-11ea-97aa-f36876af3117.JPG)

**Comment by ibrahimhajjaj** [comment]
Got the same error

**Comment by teuber-dev** [comment]
You can try disable option: Always Online™ in Cloudflare.

**Comment by michacassola** [comment]
I had problems due to redis full page caching for the last few months, maybe try to switch to FastCGI caching.
But my problem also seemed relevant to my environment only, so this is just a hunch.

**Comment by teuber-dev** [comment]
My website use FastCGI, but same error 520.
