### ISSUE TITLE
Please make sure your properly set your DNS API credentials for acme.sh

### ISSUE THREAD

**Issue by ibrahimhajjaj** [WordOps/WordOps#312]
I'm using Cloudflare free plan and when I try to issue a certificate I got this error 

**wo site update x.com -le=clean**

`SSL is not configured for given site
`

**wo site update x.com -le --dns**

```
Certificate type : domain
Validation mode : DNS mode with dns_cf
Issuing SSL cert with acme.sh   [KO]
Please make sure your properly set your DNS API credentials for acme.sh
If you are using sudo, use "sudo -E wo"

```
I'm using this API and I've tried all the SSL/TLS settings at Cloudflare 

![image](https://user-images.githubusercontent.com/23178074/92924359-7ae37500-f441-11ea-83a4-899ad87a095b.png)

![image](https://user-images.githubusercontent.com/23178074/92924459-a9615000-f441-11ea-96e0-a3a5b3267728.png)

nano /etc/letsencrypt/config/account.conf

```
#LOG_FILE="/etc/letsencrypt/config/acme.sh.log"
#LOG_LEVEL=1

AUTO_UPGRADE='1'

#NO_TIMESTAMP=1


CERT_HOME='/etc/letsencrypt/renewal'
UPGRADE_HASH='053f4a9a2e7f74aaec4493f5e9828f229088ab7c'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin'



SAVED_CF_Key='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
SAVED_CF_Email='x@gmail.com'
```

**Comment by zerofill** [comment]
I just started using WordOps, but you shouldn't have to do anything but set Cloudflare to Full (strict). That si what I do with Letsencrypt all the time, on multiple platforms. It also worked fine with domain I just put on wordops.

**Comment by ibrahimhajjaj** [comment]
> I just started using WordOps, but you shouldn't have to do anything but set Cloudflare to Full (strict). That si what I do with Letsencrypt all the time, on multiple platforms. It also worked fine with domain I just put on wordops.

not working as I said I tried all the options

**Comment by vikas5914** [comment]
I suggest you delete the Cloudflare info from the account.conf and export them again and try,

**Comment by ibrahimhajjaj** [comment]
> I suggest you delete the Cloudflare info from the account.conf and export them again and try,

didn't work

**Comment by ibrahimhajjaj** [comment]
```
Certificate type : domain
Validation mode : DNS mode with dns_cf
Issuing SSL cert with acme.sh   [KO]
Please make sure your properly set your DNS API credentials for acme.sh
If you are using sudo, use "sudo -E wo"
2020-09-21 08:22:02,427 (DEBUG) cement.core.foundation : closing the wo application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 138, in default
    self.doupdatesite(pargs)
  File "/usr/local/lib/python3.6/dist-packages/wo/cli/plugins/site_update.py", line 664, in doupdatesite
    self, acme_domains, acmedata):
  File "/usr/local/lib/python3.6/dist-packages/wo/core/acme.py", line 96, in setupletsencrypt
    self, "Please make sure your properly "
  File "/usr/local/lib/python3.6/dist-packages/wo/core/logging.py", line 25, in error
    self.app.close(1)
  File "/usr/local/lib/python3.6/dist-packages/cement/core/foundation.py", line 971, in close
    sys.exit(self.exit_code)
```

**Comment by vikas5914** [comment]
@ibrahimhajjaj How did you set your cf email and key

**Comment by ibrahimhajjaj** [comment]
> @ibrahimhajjaj How did you set your cf email and key

export CF_Key="ddd"
export CF_Email="d@gmail.com"

also, I've tried to do it manually by adding the keys to /etc/letsencrypt/config/account.conf file. and I've confirmed that the keys exist like this 

SAVED_CF_Key='x'
SAVED_CF_Email='x@gmail.com'

@vikas5914

**Comment by ibrahimhajjaj** [comment]
Any update on this issue?

**Comment by vikas5914** [comment]
@ibrahimhajjaj 

Are you using the root user ?

**Comment by ibrahimhajjaj** [comment]
> @ibrahimhajjaj
> 
> Are you using the root user ?

Yes

**Comment by ibrahimhajjaj** [comment]
This problem still exists

**Comment by microram** [comment]
I don't know if this helps anyone, but I copy/pasted the SAVED_CF_Key and SAVED_CF_Email from another working installation into my /etc/letsencrypt/config/account.conf file and now it works. It looked the same but I deleted those lines and pasted them from another working file. Also the location of the lines changed. I put them just below CERT_HOME as they were in the working file. Maybe there was some odd line endings or something weird pulled into the file from the export CF_Key method I initially used to load the keys?

Here is a redacted copy of my account.conf file that did work. 

```
#LOG_FILE="/etc/letsencrypt/config/acme.sh.log"
#LOG_LEVEL=1

AUTO_UPGRADE='1'

#NO_TIMESTAMP=1


CERT_HOME='/etc/letsencrypt/renewal'
SAVED_CF_Key='xx'
SAVED_CF_Email='email@example.com'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
UPGRADE_HASH='xx'

```

**Comment by inspiredearth** [comment]
> This problem still exists

@ibrahimhajjaj Did you ever figure this out? I'm facing what seems like the same issue, and after many hours I've not been able to issue the SSL, which means the site is unusable.

**Comment by ibrahimhajjaj** [comment]
> > This problem still exists
> 
> @ibrahimhajjaj Did you ever figure this out? I'm facing what seems like the same issue, and after many hours I've not been able to issue the SSL, which means the site is unusable.

@inspiredearth  Yeah this problem is actually related to Cloudflare TLD issue. this because you're using a free domain or a new TLD.

**Comment by TheMightyJonez** [comment]
> > > This problem still exists
> > 
> > 
> > @ibrahimhajjaj Did you ever figure this out? I'm facing what seems like the same issue, and after many hours I've not been able to issue the SSL, which means the site is unusable.
> 
> @inspiredearth Yeah this problem is actually related to Cloudflare TLD issue. this because you're using a free domain or a new TLD.

so we cannot issue SSL with Cloudflare free account @ibrahimhajjaj

**Comment by ibrahimhajjaj** [comment]
@TheMightyJonez, Of course, you can issue a certification using this method [https://kb.virtubox.net/knowledgebase/cloudflare-ssl-origin-certificates-nginx/](url)

**Comment by repercussion** [comment]
I checked the wordops logs here: /var/log/wo/wordops.log and it showed: 

```
[Sat 19 Jun 2021 05:19:34 PM UTC] Please update your account with an email address first.
[Sat 19 Jun 2021 05:19:34 PM UTC] acme.sh --register-account -m my@example.com
```

So I did that with the email that matchedd CF_Email, then I was able to generate SSL certs.

**Comment by ceefour** [comment]
@repercussion That's a really good find! I also got it:

```
$ sudo tail -F /var/log/wo/wordops.log
[Thu 15 Jul 2021 08:45:08 PM UTC] Please update your account with an email address first.
[Thu 15 Jul 2021 08:45:08 PM UTC] acme.sh --register-account -m my@example.com
[Thu 15 Jul 2021 08:45:08 PM UTC] See: https://github.com/acmesh-official/acme.sh/wiki/ZeroSSL.com-CA
```

It seems that acme.sh changed the mechanism lately?

Now my TODO is how to run `acme.sh` ?

```
$ sudo -E acme.sh --register-account -m my@gmail.com
sudo: acme.sh: command not found
```

**Comment by microram** [comment]
This  fixed my issue:

`acme.sh --set-default-ca --server letsencrypt`

**Comment by abrcoelho** [comment]
After 3 years this sort of thing still happening on a fresh install and no actual path to solve it... has anyone found the actual solution to get it to work? it seems random...

**Comment by inspiredearth** [comment]
> After 3 years this sort of thing still happening on a fresh install and no actual path to solve it... has anyone found the actual solution to get it to work? it seems random...

As much as I loved WordOps, ultimately the solution for me was to move on from WordOps and instead handle all my stack builds and hosting management through another system that is under active development (lates WO release was Dec 2024, which means it's come to a halt). The solution I went with (which I spend almost zero time problem solving on) does cost me $5 a month for a license (which covers the many servers I have), but to me that's small change compared to the amount of time it saves me tinkering around in WordOps and dealing with its quirks. My time is valuable.

**Comment by aifreedom** [comment]
@inspiredearth Could you shere a bit more about your solution for the certs? Thank you!
