### ISSUE TITLE
How does WordOps stand with HTTP3/quic?

### ISSUE THREAD

**Issue by crystaler4** [WordOps/WordOps#313]
When can we expect WordOps will be able to serve content over "new" superfast HTTP3 / QUIC protocol? Nginx part is already [done](https://www.nginx.com/blog/introducing-technology-preview-nginx-support-for-quic-http-3/).

Is is enabled already? I see the mention only about [HTTP2](https://wordops.net/features/).

`wo site create site.tld --http3`

**Comment by VirtuBox** [comment]
Hello @crystaler4,
I'm already working on adding HTTP/3 QUIC support in (my script)[https://github.com/VirtuBox/nginx-ee] to compile Nginx from source with custom modules (compatible with WordOps).
After that, if it's possible to build a new Nginx package with HTTP/3 support for WordOps, I will also push it on our debian packages repository to make it available with WordOps. 

HTTP/3 QUIC support can only be enabled globally on Nginx, so all sites will support HTTP/2 and HTTP/3.

**Comment by tdtgit** [comment]
Great to see this feature in WordOps as I notice Chrome mainstream that support [`h3-29`](https://quic.nginx.org/) now.

**Comment by sagargulati** [comment]
Has it been implemented?

**Comment by janiosarmento** [comment]
Hey, @VirtuBox , do we have any news regarding http3?

**Comment by jazir555** [comment]
> Hello @crystaler4, I'm already working on adding HTTP/3 QUIC support in (my script)[https://github.com/VirtuBox/nginx-ee] to compile Nginx from source with custom modules (compatible with WordOps). After that, if it's possible to build a new Nginx package with HTTP/3 support for WordOps, I will also push it on our debian packages repository to make it available with WordOps.
> 
> HTTP/3 QUIC support can only be enabled globally on Nginx, so all sites will support HTTP/2 and HTTP/3.

Any word on this?

**Comment by crystaler4** [comment]
> Any word on this?

As @VirtuBox stated, WO use stable Nginx release and currently stable version 1.24 has no http/3 support. Avaiting for 1.25 to become 'stable'. 

[http://nginx.org/en/CHANGES](http://nginx.org/en/CHANGES)
