### ISSUE TITLE
Brotli + WP Redis = CPU usage 100%

### ISSUE THREAD

**Issue by mdotk** [WordOps/WordOps#317]
If you enable Brotli and use WP Redis for your sites, then CPU usage will eventually reach 100%, usually within 24 hours. This has happened to me several times over several months on several different servers.

**Comment by janiosarmento** [comment]
Same to me. I eventually gave up Brotli in Nginx.

Now I use Cloudflare for HTTP3, Brotli and conditional AVIF/WEBP images (using Workers).

**Comment by jeroenops** [comment]
This seems more like a configuration issue (not necessarily on your side). Can you share the specs of the server/VPS running WordOps?

**Comment by mdotk** [comment]
Ubuntu 18+, varying specs 2GB - 8GB RAM @jeroenops Lots of different servers

**Comment by vikas5914** [comment]
@janiosarmento can you provide the Condition image using Workers example. We also use Cloudflare and like do that aswell.

**Comment by janiosarmento** [comment]
@vikas5914 I'm sorry, I didn't see your comment until now.

The Worker code is here:

https://gist.github.com/janiosarmento/c9c47c649d7e276ed286cd402e831ac4

It lacks proper documentation, but I think you can use it as a starter for your own code.
