### ISSUE TITLE
Include support to conditional avif images

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#319]
The AVIF image format is real now, and I think WO could extend the webp conditional serving to avif.

**Comment by dingman** [comment]
Feel free to submit a PR for it.

There doesn't seem to be much browser support for it right now.

https://caniuse.com/avif

**Comment by janiosarmento** [comment]
All Chrmoium based browsers support it, and Firefox has experimental support.

Feel free to not take my word as truth and do your own research.

**Comment by VirtuBox** [comment]
Hello @janiosarmento,

Feature has already been added by @tdtgit in PR #314. It will be available in the next release (probably today).

**Comment by janiosarmento** [comment]
Hello,

Has this been tested with a browser with WEBP support but no AVIF?

I think the `try_files` clause will force the original file to any browser webp cabaple, but not avif capable.

Anyway, I"ll test it as soon as the new release goes public.

**Comment by janiosarmento** [comment]
In line 37 of `wo/cli/templates/avif.mustache` rather than:

`default "";`

it should be something like:

`default ".a-very-improbable-extension";

Otherwise, the `try_files` will never serve a .webp for Safari, for example (it supports WEBP but not AVIF).

I could submit a PR, but I'm a potato regarding Git.

**Comment by tdtgit** [comment]
Hi @janiosarmento,

Thanks for pointing that out. Guest you're right! 👍  I'm updating the PR to address this issues.

**Comment by tdtgit** [comment]
Hi @janiosarmento, can take a look at https://github.com/tdtgit/WordOps/commit/e2dc4bdc27dac6172ebd9ecc6da39dd44c2f08a6. I've standardlize the image suffix code. For this change, if we have new type of image codec in future, it will make it easy to implement.

**Comment by janiosarmento** [comment]
Hi,

I'm not sure if I understood the logic you implemented, but the way I see it, it will try to serve AVIF then original file; or WEBP then original file.

The best should try AVIF, then try WEBP, then original file.

There are cases where AVIF is larger than WEBP, so it should not be generated.

The best approach, IMHO, it would be just changing avif.conf to replace the `""` with a random string as the default extension (for non AVIF browsers).

**Comment by tdtgit** [comment]
Just tested and fail that case. I will try some ways or move back to the original and add the random string as you advised.

**Comment by janiosarmento** [comment]
Thank you @tdtgit

**Comment by tdtgit** [comment]
Hi @janiosarmento, @VirtuBox , I've pushed new PR #322 to address this issue. Please take it to the release too :)

**Comment by janiosarmento** [comment]
@VirtuBox and @tdtgit — I updated WO in two servers of mine, and there is no reference to "avif" in `/etc/nginx` at all.

Is that expected?

![](https://shares.cdnfacil.com.br/2020/10/ssh_25374A48.png)

**Comment by tdtgit** [comment]
No it's not an expected behavior. Tried both new install and update my current server, both have `avif`.

![Screen Shot 2020-10-14 at 23 31 13](https://user-images.githubusercontent.com/4527866/96018371-61d14800-0e75-11eb-9b3f-a44f6854d969.JPG)

**Comment by janiosarmento** [comment]
There is something wrong. My .conf files are in 3.12.2 version (and I don't have .custom form them)

**Comment by buzucan** [comment]
Do you have some bulk convertor for avif? :)

**Comment by janiosarmento** [comment]
@buzucan

I use this tool for generating AVIF:

https://github.com/Kagami/go-avif

I'm going to write a tutorial for WO Docs with a sample script.

The general logic is:

- iterate through all image files
    - for each image file generate the correspondig webp
    - check if the webp is really smaller than the original file
    - if not, delete the webp
    - generate the corresponding AVIF
    - check if it's really smaller than original and webp
    - delete if not

Generating avif, at least with this tool I linked, is not fast. Some images take up to 5min of processing. But the general gain on BW/load times is worth it.

**Comment by tdtgit** [comment]
For my case, [kornelski/cavif-rs](https://github.com/kornelski/cavif-rs) did a really good job. It's better with multicore server, good memory usage (~250MB) and support the transparent images.

**Comment by janiosarmento** [comment]
@tdtgit

I'm just starting to test cavif-rs, to compare with go-avif. :)
