### ISSUE TITLE
`info` subcommand in the table on the beginning of commands documentation

### ISSUE THREAD

**Issue by crystaler4** [WordOps/WordOps#325]
Hi, [here](https://docs.wordops.net/commands/site/
) is missing `info` subcommand in the table on the beginning.

**Comment by tdtgit** [comment]
I've push an PR at https://github.com/WordOps/docs.wordops.net/pull/28 to fix this issue. Please note this repo is for WordOps CLI script and the docs should be posted in https://github.com/WordOps/docs.wordops.net/

**Comment by VirtuBox** [comment]
Hello, 
the issue has been fixed by @tdtgit.
