### ISSUE TITLE
Cache with parameter exceptions

### ISSUE THREAD

**Issue by py2us** [WordOps/WordOps#327]
There are certain GET parameters that are not used on the server side, but on the client/browser side like:

**utm_*** (utm_source, utm_medium, utm_content, utm_campaign) - Google Analytics
**fbclid** - Facebook SDK

In this file it is indicated that if there are parameters in the url, it is not cached. This causes that all visits are not cached (fastcgi or redis).

`/wo/cli/templates/map-wp.mustache`
`# do not cache requests with query strings
map $is_args $query_no_cache {
    default 1;
    "" 0;
}`

Is it possible to add an exception for these parameters? Ignore these parameters, do not pass them to the server, but without redirecting.

Thanks.

**Comment by VirtuBox** [comment]
Hello @py2us,
thanks for this suggestion. I will take a look on this.

**Comment by VirtuBox** [comment]
Hello @py2us,
I have updated Nginx cache mapping rules to force query strings caching when the query strings looks like utm_ or fbclid.
Feature will be available in next release.
