### ISSUE TITLE
The second site resolving the first site

### ISSUE THREAD

**Issue by riyas-rawther** [WordOps/WordOps#328]
- Create a new site  wo site create site1.example.com --wp --php74 --wpredis --letsencrypt

- Create another site  wo site create site2.example.com --wp --php74 --wpredis --letsencrypt
- check the SSL certificate of site1.

- The site2 is actually coming from site1

**Comment by VirtuBox** [comment]
Hello @riyas-rawther,
thanks for your report, I'm going to investigate on this issue

**Comment by VirtuBox** [comment]
Hello @riyas-rawther,
I was not able to reproduce this issue on a fresh install. 
Have you issued a wildcard certificate on this server ?

**Comment by markusvesoen** [comment]
@riyas-rawther - Are you using Cloudflare? We had a similar experience because of Cloudflare HTTPS rewrite rules. Clear CF and setup ssl correctly in CF solved it for us.
