### ISSUE TITLE
Not seeing updated NGINX caching rules

### ISSUE THREAD

**Issue by olegcarguy** [WordOps/WordOps#332]
Hi, just updated to 3.13.1, ran wo stack upgrade but not seeing the updated nginx caching rules from this commit: https://github.com/WordOps/WordOps/pull/329/commits/3d32e02c654a481e0ef469c161bb62a0330dbedb

I'm assuming these changes are supposed to be in the /etc/nginx/conf.d/map-wp-fastcgi-cache.conf file but they are not present there.  Note that I am running a custom version of this file, and have a blank .custom file and also see the .conf.orig file.  Inside of this file the first line comment says 3.13.1 but in this file I'm not seeing these new changes either. Below is the text from the .conf.orig file:

```
# NGINX CONFIGURATION FOR FASTCGI_CACHE EXCEPTION - WordOps 3.13.1
# DO NOT MODIFY, ALL CHANGES WILL BE LOST AFTER AN WordOps (wo) UPDATE

# do not cache xhtml request
map $http_x_requested_with $http_request_no_cache {
    default 0;
    XMLHttpRequest 1;
}

# do not cache requests on cookies
map $http_cookie $cookie_no_cache {
    default 0;
    "~*wordpress_[a-f0-9]+" 1;
    "~*wp-postpass" 1;
    "~*wordpress_logged_in" 1;
    "~*wordpress_no_cache" 1;
    "~*comment_author" 1;
    "~*woocommerce_items_in_cart" 1;
    "~*edd_items_in_cart" 1;
    "~*woocommerce_cart_hash" 1;
    "~*wptouch_switch_toogle" 1;
    "~*comment_author_email_" 1;
    "~*wptouch_switch_toggle" 1;
    "~*edd" 1;
}

# do not cache the following uri
map $request_uri $uri_no_cache {
    default 0;
    "~*/wp-admin/" 1;
    "~*/wp-[a-zA-Z0-9-]+.php" 1;
    "~*/feed/" 1;
    "~*/index.php" 1;
    "~*/[a-z0-9_-]+-sitemap([0-9]+)?.xml" 1;
    "~*/sitemap(_index)?.xml" 1;
    "~*/wp-comments-popup.php" 1;
    "~*/wp-links-opml.php" 1;
    "~*/xmlrpc.php" 1;
    "~*/checkout" 1;
    "~*/edd_action" 1;
    "~*/edd-sl/*" 1;
    "~*/add_to_cart/" 1;
    "~*/cart/" 1;
    "~*/my-account/" 1;
    "~*/checkout/" 1;
    "~*/addons/" 1;
    "~*/wc-api/*" 1;
    "~*/logout/" 1;
    "~*/lost-password/" 1;
    "~*/panier/" 1;
    "~*/mon-compte/" 1;
    "~*/embed" 1;
    "~*/commande/" 1;
    "~*/resetpass/" 1;
}
# mobile_prefix needed for WP-Rocket
map $http_user_agent $mobile_prefix {
    default "";
    "~*iphone" -mobile;
    "~*android" -mobile;
}

# do not cache requests with query strings
map $is_args $query_no_cache {
    default 1;
    "" 0;
}

# if all previous check are passed, $skip_cache = 0
map $http_request_no_cache$cookie_no_cache$uri_no_cache$query_no_cache $skip_cache {
    default 1;
    0000 0;
}

# map $skip_cache with $cache_uri for --wpsc --wpce & --wprocket stack
map $skip_cache $cache_uri {
    0 $request_uri;
    default 'null cache';
}

# http_prefix needed for WP-Rocket
map $https $https_prefix {
    default "";
    on "-https";
}

# needed to proxy web-socket connections
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
```

**Comment by VirtuBox** [comment]
Hello @olegcarguy,
can you run the following command to create a debug log and provide me the link displayed : 
```shell
wo stack upgrade --nginx --force --debug >> debug.log 2>&1 && curl --progress-bar --upload-file ./debug.log https://transfer.vtbox.net/"$(basename debug.log)" && echo ""
```

**Comment by olegcarguy** [comment]
Sure.  No problem.  Here is the link:
https://transfer.vtbox.net/2wc99/debug.log

**Comment by VirtuBox** [comment]
Ok thanks. Can you check the content of `/usr/lib/wo/templates/map-wp.mustache` ?
Is it the same than https://github.com/WordOps/WordOps/blob/master/wo/cli/templates/map-wp.mustache ?

**Comment by olegcarguy** [comment]
Just checked.  No it's not.  It's an old version.  So that explains why
nginx config file hasn't been updated, but why would this mustache file not
be updated?

**Comment by VirtuBox** [comment]
It's a very good question. Have you used `wo update` to update WordOps to the latest release ?
I will update all my servers this evening and check if there is the same issue on some of them.

**Comment by olegcarguy** [comment]
Yes I did run this command.  I tried running it multiple times actually,
but nothing.  Even though the mustache file contents haven't been applied
to the .orig file, the .orig file does state that it's from 3.13.1.  it
just has old data.
