### ISSUE TITLE
Install Composer2 by default. 

### ISSUE THREAD

**Issue by vikas5914** [WordOps/WordOps#333]
Composer 1 is EOL. We should move to Composer 2.

For upgrading to composer 2, 

```
composer selfupdate --2
```

**Comment by VirtuBox** [comment]
Hello @vikas5914,
composer can also be automatically upgraded to the latest version by running `wo stack upgrade` or `wo stack upgrade --composer`.

**Comment by olegcarguy** [comment]
is there a way to exclude composer from being updated while upgrading the rest of the stack?  We have other apps on our server that require 1.x

**Comment by VirtuBox** [comment]
Hello @olegcarguy,
you just have to define the stack your want to upgrade. For example :
```bash
wo stack upgrade --nginx --mysql --phpmyadmin --netdata
```
You can also use `wo maintenance` to only keep your APT packages up-to-date.

**Comment by vikas5914** [comment]
Closing this since its already implemented.
