### ISSUE TITLE
Cannot complete install on Ubuntu 20

### ISSUE THREAD

**Issue by mdotk** [WordOps/WordOps#337]
See this thread https://community.wordops.net/d/726-wordops-install-problem

I have just experienced the problem myself on a new server

Also applies to Ubuntu 18 (checked by me also)

**Comment by Sl1nkman** [comment]
I ran into this issue today as well.
Description of issue:
When running $ wget -qO wo wops.cc && sudo bash wo

OR

$ git clone https://github.com/WordOps/WordOps.git
$ cd WordOps/
$ sudo bash install

The script gets stuck after the dependencies are installed
Installing Wordops... is permenantly displayed,
The user is never prompted for name and email.

Expected result:
WordOps installed and prompted for name and email.


The manual installation works.

**Comment by VirtuBox** [comment]
Hello, 

the issue has been fixed, you can install WordOps with `wget -qO wo wops.cc && sudo bash wo`.
