### ISSUE TITLE
Support to create and manage WordPress staging website

### ISSUE THREAD

**Issue by AnkitaBeniwal** [WordOps/WordOps#339]
Hi, will it be possible to add feature to create and manage WordPress staging website

**Comment by nsgoyat** [comment]
Hey Ankita,
The stagging feature is planned but there is no ETA for this.
![image](https://user-images.githubusercontent.com/36985369/109254305-c3d48d80-7817-11eb-9699-35a779492a16.png)

You can find more about the planned features on this page: https://github.com/WordOps/WordOps/projects/2

**Comment by techieshark** [comment]
Duplicate of https://github.com/WordOps/WordOps/issues/99 yeah?

**Comment by webdados** [comment]
This is dead, right?
