### ISSUE TITLE
after doing wo site create example.com --wpredis nginx doesnt start

### ISSUE THREAD

**Issue by Facer66** [WordOps/WordOps#34]
Hi,

after doing wo site create example.com --wpredis nginx doesnt start

the error it shows: nginx: [emerg] unknown directive "ssl_dyn_rec_enable" in /etc/nginx/nginx.conf:68

thx

**Comment by VirtuBox** [comment]
Hello,

can you give me the output of the command : 

```bash
nginx -V
```

**Comment by Facer66** [comment]
Yep,

output from nginx -V:

nginx version: nginx/1.14.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.0g  2 Nov 2017 (running with OpenSSL 1.1.1b  26 Feb
2019)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2
-fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong
-Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2'
--with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC'
--prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf
--http-log-path=/var/log/nginx/access.log
--error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock
--pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi
--http-proxy-temp-path=/var/lib/nginx/proxy
--http-scgi-temp-path=/var/lib/nginx/scgi
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo'
--with-debug --with-pcre-jit --with-file-aio --with-threads
--with-http_ssl_module --with-http_stub_status_module
--with-http_realip_module --with-http_auth_request_module
--with-http_addition_module --with-http_geoip_module
--with-http_gzip_static_module --with-http_mp4_module --with-http_v2_module
--with-http_sub_module --with-http_xslt_module
--add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module
--add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam
--add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge
--add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo
--add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair
--add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module
--add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module
--add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module
--add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule
--add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module
--add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit
--add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module
--add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts
--add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

**Comment by VirtuBox** [comment]
Hello,

okay, it's because you are still using the previous nginx.conf added by Nginx-wo package and we have made few modifications in this file. 

Just download the new nginx.conf with the command : 

```bash
wget -O /etc/nginx/nginx.conf https://raw.githubusercontent.com/WordOps/nginx-build/master/nginx/debian/conf/nginx.conf
```
And you will be able to reload nginx.

**Comment by Facer66** [comment]
Hello,
BTW I used the install version from here: https://github.com/VirtuBox/wo-nginx-setup

I did what you suggested. Which fixed that problem.
After restarting nginx it failed with the following message: unknown directive "fastcgi_socket_keepalive" in /etc/nginx/conf.d/fastcgi.conf

Thx

**Comment by VirtuBox** [comment]
Hello,

I have just pushed an update to fix this issue on wo-nginx-setup repository.
Just comment the following line in /etc/nginx/conf.d/fastcgi.conf : 
```
fastcgi_socket_keepalive on;
```

**Comment by yotpaul** [comment]
Hey,

Seems like there are more directive issues with the config. I've tried purging nginx and re-installing to be met with:
```
root@vultr:~# tail -n 30 /var/log/wo/wordops.log
Unpacking nginx-wo (1.14.2-8ppa~stable) ...
Processing triggers for ufw (0.35-5) ...
^[[19~Processing triggers for ureadahead (0.100.0-20) ...
Setting up nginx-common (1.14.2-8ppa~stable) ...
Processing triggers for systemd (237-3ubuntu10.15) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up nginx-custom (1.14.2-8ppa~stable) ...
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-03-21 10:14:57 UTC; 17ms ago
  Process: 5003 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
 Main PID: 13148 (code=exited, status=0/SUCCESS)

Mar 21 10:14:57 vultr.guest systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 21 10:14:57 vultr.guest nginx[5003]: nginx: [emerg] no port in upstream "php" in /etc/nginx/common/php.conf:9
Mar 21 10:14:57 vultr.guest nginx[5003]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 21 10:14:57 vultr.guest systemd[1]: nginx.service: Control process exited, code=exited status=1
Mar 21 10:14:57 vultr.guest systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 21 10:14:57 vultr.guest systemd[1]: Failed to start A high performance web server and a reverse proxy server.
dpkg: error processing package nginx-custom (--configure):
 installed nginx-custom package post-installation script subprocess returned error exit status 1
Setting up nginx-wo (1.14.2-8ppa~stable) ...
Errors were encountered while processing:
 nginx-custom
E: Sub-process /usr/bin/dpkg returned an error code (1)
2019-03-21 10:15:00,236 (INFO) wo : Oops Something went wrong!!
2019-03-21 10:15:00,237 (ERROR) wo : Check the WordOps log for more details `tail /var/log/wo/wordops.log` and please try again...
```
(on an unrelated note, I get a lot of 500 issues with the Flarum forum for you guys, can't validate my email)

**Comment by VirtuBox** [comment]
Hello @yotpaul ,
we haven't finished the install/update/migration script yet.
I'm going to open a PR which include a major update to the script.

The issue with email validation on the forum has been fixed.

**Comment by yotpaul** [comment]
> Hello @yotpaul ,
> we haven't finished the install/update/migration script yet.
> I'm going to open a PR which include a major update to the script.
> 
> The issue with email validation on the forum has been fixed.

Thanks for the reply! I should've mentioned this in my previous message, this happened following a WordOps update rather than a fresh install

**Comment by VirtuBox** [comment]
Hello @yotpaul ,
yes we made several changes in the structure during the past few weeks, without having an up-to date install script. That's why we still have to work on the install/update script, to handle migration from EEv3 but also from previous WordOps install.
It require to update all nginx configurations with the new versions, to make sure there isn't any outdated configuration.
I'm already running tests to identity all the possibles issues during migration from EEv3 or WO, and to add the proper directives to fix them in our install script.
It's currently the main task to perform before publishing the stable release.

**Comment by yotpaul** [comment]
Thanks @VirtuBox , looking forward for the fix.
Temporarily fixed the issue by configuring fastcgi_pass to unix:/run/php/php7.3-fpm.sock

**Comment by VirtuBox** [comment]
I have pushed yesterday a first fix to force nginx configuration refresh during WO upgrade. Let me know if there is any issue.
