### ISSUE TITLE
Add option for hexdump to BLOB columns in MySQL

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#340]
Several operations in WO (site update) generate a mysqldump backup. These backups should be made using the option `--hex-blob` to prevent data loss in non-WP sites, or any other using BLOBs.

**Comment by VirtuBox** [comment]
Hello @janiosarmento,
I just pushed a fix for this issue : https://github.com/WordOps/WordOps/commit/7465628d95f2608815f07b1f06eca5832d364d1a
