### ISSUE TITLE
purge fastcgi cache on a multisite 

### ISSUE THREAD

**Issue by mscice** [WordOps/WordOps#342]
Hello just a question.. I have around 5 sites running on a single vps.. if any of the sites purges fastcgi cache via wp-admin... it purges all from /var/run/nginx-cache... 

is there anyway to just purge its current domain multisite only? and will not purge other sites cache?

**Comment by tersor** [comment]
Hello.

Yes, cache on all sites will get purged if the same cache directory is used, and nginx-helper uses `/var/run/nginx-cache/` by default. But you can override this in `wp-config.php`, for example:

```
`define('RT_WP_NGINX_HELPER_CACHE_PATH','/var/run/nginx-cache/domain.tld/');`
```

**Comment by mscice** [comment]
yes but then how do i configure nginx to store domain cache under what directory ?
Right now all sites use /var/run/nginx-cache/ 

Thank you for reply..

**Comment by tersor** [comment]
Yes you need custom nginx config per site, take a look in `/etc/nginx/conf.d/fastcgi.conf` and `/etc/nginx/common/wpfc-php<version>.conf`.

**Comment by mscice** [comment]
thank you once again

maybe would be nice to add such option in future releases ..

**Comment by VirtuBox** [comment]
Hello @mscice,
when you use the `Purge Cache` button in wp-admin, Nginx-helper will purge the whole Nginx fastcgi_cache, but it should not be required if you configure "Purging Conditions" with Nginx-helper. In this case, it will automatically and selectively purge Nginx fastcgi_cache when you create/update an article, add/remove comments etc ...
