### ISSUE TITLE
Can we install it on 64bit ARM architecture?

### ISSUE THREAD

**Issue by sanjayojha** [WordOps/WordOps#346]
When seeing Prerequesites, It mention to use x86_64 architecture?
So is it not possible to use it with 64bit Arm architecture with Ubuntu 20.04?
I am using AWS EC2

**Comment by VirtuBox** [comment]
Hello @sanjayojha,
we are not providing Nginx package on 64 bit ARM yet, so WordOps will not work on EC2 ARM instances.
But i will take a look to see if it's possible to build Nginx package on 64 bit ARM.

**Comment by sanjayojha** [comment]
Thank you!
Will wait for the update.

**Comment by VitorHeringer** [comment]
> Hello @sanjayojha,
> we are not providing Nginx package on 64 bit ARM yet, so WordOps will not work on EC2 ARM instances.
> But i will take a look to see if it's possible to build Nginx package on 64 bit ARM.

Hello! I've tried and it didn't work. I was wondering if WordOps will only work with  "nginx-custom package" or there is a way to make it work with Nginx standard packages?

**Comment by ridgegate** [comment]
@VitorHeringer 

Please use the following commands for ARM64. I was able to run it on Oracle Cloud but I cannot get dashboard to work. Good luck

wget -qO wo wops.cc && sudo bash wo

#Install Nginx for ARM64
wget -qO nginx-ee vtb.cx/nginx-ee
sudo bash nginx-ee
