### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by buzucan** [WordOps/WordOps#348]
Today PHP 8 was released. It will be supported? :)

**Comment by tersor** [comment]
Relevant to this: WordPress core aims for "beta compability" in the 5.6 release, which is currently scheduled for December 8, 2020.

Though, the broad support for php8 in plugins and themes sets the scene for a crazy testing bonanza in the upcoming weeks. Cant wait ;-)

**Comment by VirtuBox** [comment]
Hello, 

yes PHP 8 support will be added soon. I'm just waiting for wp-cli official support of PHP 8 to make sure it will not cause issues when creating/updating WordPress sites.

**Comment by javiercasares** [comment]
WP-CLI / WordPress officially supports PHP 8 since WordPress 5.6. Also, I tested WordPress with Ubuntu 20 and PHP 8 and works perfect (the core and simple plugins). The incompatibilities are on some plugins themes, but _not a problem for WordPress Core_.

**Comment by buzucan** [comment]
uh! Nice! :)

**Comment by javiercasares** [comment]
Also, for anybody who wants, there is an official [Hosting Team](https://make.wordpress.org/hosting/) and we usually update the [Server Environment](https://make.wordpress.org/hosting/handbook/handbook/server-environment/) information.

Also, there is a [Requirements](https://wordpress.org/about/requirements/) page.

And also, there are 2 JSON API to check:
- [WordPress security versions](https://api.wordpress.org/core/stable-check/1.0/)
- [WordPress update / autoupdate and requirements](https://api.wordpress.org/core/version-check/1.7/)
- [WordPress Serve-Happy information](https://api.wordpress.org/core/serve-happy/1.0/?php_version=8.0) (checked PHP 8.0)

Hope this is useful (in that last API you can send the PHP version and the "is_supported" tells you if you can or not use it for the latest WordPress version.

**Comment by janiosarmento** [comment]
Hello, @VirtuBox

Do we have an ETA for PHP 8 support? (Just asking.)

Thanks!

**Comment by harsh8511** [comment]
Hey @VirtuBox  any update on this ?

**Comment by kingkool68** [comment]
Latest update on this: https://twitter.com/Thomas_VirtuBox/status/1383015189004619782?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1383015189004619782%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=

**Comment by Slapbox** [comment]
>> Latest update on this: https://twitter.com/Thomas_VirtuBox/status/1383015189004619782?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1383015189004619782%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=

**The tweet:**
> WordOps is not abandoned, but I haven't worked recently on the project due to a lack of free time. 
I'm not sure I will be able to work on new features soon, but I will publish a maintenance update with PHP 8.0 after Ubuntu Xenial reach its EOL.

Big thanks to @VirtuBox for the great work! Looking forward to PHP8 support whenever it happens.

**Comment by janiosarmento** [comment]
Hey @VirtuBox  — anything planned for the next release, re: PHP8?

**Comment by janiosarmento** [comment]
If someone is interested, I created a "patch" to add rudimentary PHP 8 support to WordOps.

repo: https://github.com/janiosarmento/wo-php8
more info: https://community.wordops.net/d/1197-unofficial-php8-support

**Comment by janiosarmento** [comment]
Hey, @VirtuBox !

I've just seen this commit:

https://github.com/WordOps/WordOps/commit/089ff2c98ffe047813d330996ae3dc1bfbf3f943

Are you taking PHP8 into consideration regarding the new scripts?

**Comment by Slapbox** [comment]
Very excited to see this is marked as completed! I wonder when a version with PHP 8 support will be released?
