### ISSUE TITLE
Feature Request: Varnish

### ISSUE THREAD

**Issue by dingman** [WordOps/WordOps#352]
Having been using WordOps for more than a year now, and seeing the speed of how WPengine configures varnish, I feel like WordOps could benefit from Varnish as well.

**Comment by janiosarmento** [comment]
How would Varnish improve performance?

I've ditched Varnish from my servers years ago. It doesn't even support SSL (you gotta install Hitch in front of Varnish), and everything Varnish does can be done better with Nginx, AFAICT.

Would you please develop a bit more your idea? Probably I'm outdated about this subject.

Thanks!
