### ISSUE TITLE
Location .well-known/ampthml should be whitelisted

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#354]
WO blocks access to any URL starting with a dot, but whitelists specifically `.well-known/acme-challenge/`.

I just faced a new need: `.well-known/amphtml/` should also be whitelisted, and not aliased to a shared location because AMP sites need a published public key in this precise location in order to allow several operations, like cache refresh.

**Comment by VirtuBox** [comment]
Hello @janiosarmento,
thanks for your report. I will add `.well-known/amphtml/` to the whitelist.
