### ISSUE TITLE
Support for WP Cloudflare Super Page Cache plugin

### ISSUE THREAD

**Issue by isaumya** [WordOps/WordOps#357]
Hi WordOps team,
I'm so glad to see this project and knowing how seriously you guys take Cloudflare into account. I can see that you guys already supports multiple WP caching plugins but was wondering if you guys would be interested to add a Cloudflare focused caching plugin in the stack as well.

I'm not sure if you have tried out the **[WP Cloudflare Super Page Cache](https://wordpress.org/plugins/wp-cloudflare-page-cache/)** plugin. If not, I will highly recommend you to try it out. It helps you to unleash the full power of Cloudflare and take advantage of the enormous CDN network to cache not only your static files but also the HTML webpages (first request).

So, once your pages are cached by your nearest CF CDN edge (after receiving the first request), after that time all the requests will be served from your nearest CF CDN pop rather than those requests hitting the server.

The plugin can be used with either CF page rules or Workers.

Moreover, there is a disk-level fallback cache which will help the cached webpages to be served from the disk-level fallback cache for the first request before Cloudflare CDN has already cached it.

There are many more amazing things. I'm sure you guys will love the plugin if you check it out. Hope you guys will love it and consider adding it into your stack. Thanks.

**Comment by janiosarmento** [comment]
You don't need anything special in the server to use this plugin. Just create your blog with `--wp`, install and configure the plugin and profit.

So, what do you expect the stack to do for you in such a case?

**Comment by isaumya** [comment]
Hi @janiosarmento,
Yes in fact nothing special is needed for any of the wp caching plugins to work. But I was wondering you guys can easily integrate the plugin with your stack for easier setup by the user.

Here are the things I think will be very helpful:
1. This plugin automatically generates a `nginx.conf` file inside `/wp-content/wp-cloudflare-super-page-cache/<domain-name>/` so that instead of constantly copy pasting the configs users can easily include this `nginx.conf`  file to the main `nginx.conf` and don't have to do any extra works. Also in future if the user make any settings changes in the plugin which needs to update the nginx config, all the user has to do is to restart nginx and the rules will take effect.
2. The plugin has a fallback cache system for disk-level page caching. So, maybe give users an option to either use the fastcgi cache or this plugin disk cache in the setup tools
3. When using fast CGI cache, inform the users that they do not need to enable fallback cache and also take advantage of the hooks available in the plugin to ensure when the server clears the fast cgi cache it also use the hook to purge that page from cloudflare as well.

These are just few ideas of the top of my head, but I'm sure if you guys think deeper you can build a better one-click integration of this plugin with WordOps.

**Comment by dingman** [comment]
It's not necessarily a bad idea. 

https://docs.wordops.net/commands/site/#cheatsheet

Already an existing list of integrations, adding one for Cloudflare could be nice.

I imagine there are higher priorities for the core team. But someone might want to write this.

**Comment by janiosarmento** [comment]
What kind of integration do you expect WO to do? Just installing the plugin for you? (Since all the configuration must be done inside the plugin interface, due to authentication, domain selection, and son on.)

**Comment by isaumya** [comment]
@janiosarmento the integration means an easy way to include the nginx config file the plugin creates in the WO nginx config and also if a user enables fast cgi cache the system also clears CF cache when the fastcgi cache is purged. Check my above message.
