### ISSUE TITLE
wo stack restart --mysql reports that MySQL is not installed despite it is

### ISSUE THREAD

**Issue by TBarregren** [WordOps/WordOps#360]
How to re-create the bug:

```bash
# wo stack install --mysql
MySQL already installed and alive
MySQLtuner already installed

# wo stack restart --mysql
MySQL is not installed
```

System Information

## `lsb_release -a`

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

## `wo info`

NGINX (1.18.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1
PHP 7.2 is not installed

PHP (7.4.15):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  21
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.5.9-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             3
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

## `nginx -V`

nginx version: nginx/1.18.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1g  21 Apr 2020 (running with OpenSSL 1.1.1j  16 Feb 2021)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-T3TEe9/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/nginx-echo --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/memc-nginx-module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/HttpRedisModule --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/nginx-module-vts --add-module=/build/nginx-T3TEe9/nginx-1.18.0/debian/modules/ngx_brotli

## `wo -v`

WordOps v3.13.2
Copyright (c) 2020 WordOps.

## `wp cli info --allow-root`

N/A. Haven't yet installed WordPress.

## `curl -sL git.io/fjAp3 | sudo -E bash -`

https://transfer.vtbox.net/10XB3D/wordops.txt

**Comment by kauaicreative** [comment]
I was having this issue as well.
`wo info` would return `MySQL is not installed`

I removed my custom settings from `/etc/mysql/conf.d/my.cnf` and now  `wo info` returns MySQL info

**Comment by tharlab** [comment]
same to me, and sometime it return
`ERROR: Connection refused`
