### ISSUE TITLE
Serve static assets with an efficient cache policy

### ISSUE THREAD

**Issue by yogeshbeniwal** [WordOps/WordOps#361]
Currently cache expiry of css and js is set to 30d. However Google pagespeed expect it to be at least 1 year as per https://web.dev/uses-long-cache-ttl/. 

While in WordOps this is already set to max for images and font file formats, consider updating it to at least 1 year for css and js files too.

**Comment by ddur** [comment]
Depends. 
Cached WordPress installation JS/CSS may remain in user browser after WP is updated, and break user experience.
Unless JS/CSS query argument is not ignored by caching.

**Comment by yogeshbeniwal** [comment]
@ddur Configuration quoted at #396 is related to caching in Nginx FastCGI cache. Pull request above is for browser caching on client side, which as per Google recommendation should be 1 year.

**Comment by ddur** [comment]
> @ddur Configuration quoted at #396 is related to caching in Nginx FastCGI cache. Pull request above is for browser caching on client side, which as per Google recommendation should be 1 year.

Yes, you are right, URL&query is actually delivered to browser which will then cache new version immediately after WP update.
