### ISSUE TITLE
nginx-custom : Depends: nginx-common (= 1.18.0-1ppa~stable1~ubuntu20.04.1~ppa1) but 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 is to be installed

### ISSUE THREAD

**Issue by devinjdawson** [WordOps/WordOps#370]
`~$ sudo apt install nginx-wo`

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-custom : Depends: nginx-common (= 1.18.0-1ppa~stable1~ubuntu20.04.1~ppa1) but 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 is to be installed

System Information
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

can not run wo commands without nginx installed

**Comment by vikas5914** [comment]
@devinjdawson  Any reason for installing `nginx-wo` package?

**Comment by devinjdawson** [comment]
i used to run `nginx-ee`, then i installed nginx-wo. i assumed wo was the correct thing to be using.

However, I found the `nginx-ee` installer and that seemed to work partially, but my nginx dependecies within my PPA's are all messed up now. I can not get let's encrypt bot to see nginx.

```
sudo apt install python3-certbot-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-certbot-nginx : Depends: nginx

sudo apt install python3-certbot-nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-certbot-nginx : Depends: nginx
```


```
sudo apt install nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package nginx is a virtual package provided by:
  nginx-light 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 [Not candidate version]
  nginx-full 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 [Not candidate version]
  nginx-extras 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 [Not candidate version]
  nginx-core 1.18.0-6+deb.sury.org+2+ubuntu20.04.1+deb.sury.org+1 [Not candidate version]
  nginx-light 1.18.0-0ubuntu1 [Not candidate version]
  nginx-full 1.18.0-0ubuntu1 [Not candidate version]
  nginx-extras 1.18.0-0ubuntu1 [Not candidate version]
  nginx-core 1.18.0-0ubuntu1 [Not candidate version]
  nginx-light 1.17.10-0ubuntu1 [Not candidate version]
  nginx-full 1.17.10-0ubuntu1 [Not candidate version]
  nginx-extras 1.17.10-0ubuntu1 [Not candidate version]
  nginx-core 1.17.10-0ubuntu1 [Not candidate version]

E: Package 'nginx' has no installation candidate
```
**BUT** 


```
nginx -version
nginx version: nginx/1.19.10 (VirtuBox Nginx-ee)
```

When I look at the ubuntu website, I do not see any builds for nginx on 20.04.2 in the PPAs. TBH, i'm  a little lost at this point

**Comment by inspiredearth** [comment]
Hi @devinjdawson Did you figure out the solution to this? Would love to hear what it was.
