### ISSUE TITLE
EXPKEYSIG virtubox debian10

### ISSUE THREAD

**Issue by mscice** [WordOps/WordOps#380]
Hit:6 https://packages.sury.org/php buster InRelease                                                     
Hit:7 https://repos.insights.digitalocean.com/apt/do-agent main InRelease                
Err:4 http://download.opensuse.org/repositories/home:/virtubox:/WordOps/Debian_10  InRelease
  The following signatures were invalid: EXPKEYSIG 188C9FB063F0247A home:virtubox OBS Project <home:virtubox@build.opensuse.org>
Fetched 4,635 B in 1s (6,401 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/virtubox:/WordOps/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 188C9FB063F0247A home:virtubox OBS Project <home:virtubox@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/virtubox:/WordOps/Debian_10/InRelease  The following signatures were invalid: EXPKEYSIG 188C9FB063F0247A home:virtubox OBS Project <home:virtubox@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done

I'm getting that on a fresh installed wordops after running apt-get update ..

any clue how to fix it?

 
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by mscice** [comment]
seems the key is expired https://download.opensuse.org/repositories/home:virtubox:WordOps/Debian_10/Release.key 


any plans on renewing it ?

**Comment by VirtuBox** [comment]
Hello,

thanks for your report, issue has been fixed : https://community.wordops.net/d/999-how-to-fix-wordops-expired-gpg-keys

**Comment by mscice** [comment]
thank you !
