### ISSUE TITLE
Persistent issue with nginx-wo on raspberry pi 4

### ISSUE THREAD

**Issue by dede34fr-zz** [WordOps/WordOps#383]
Hi,
I've been able to install wordops on rpi4 (4mb) but I've always failed when installing the wo stack or even tried to create the site directly. Same problem related to nginx.  Last try below with Ubuntu 20.04 LTS. See picture enclosed:
![45Otiqgc3a](https://user-images.githubusercontent.com/42569980/120189666-e95aa400-c217-11eb-9d75-e503bcc1fb5e.png)

- [ ] `lsb_release -a`
- [ ] Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

**Comment by tdtgit** [comment]
WordOps is not compatible with Arm arch yet #346

**Comment by dede34fr** [comment]
Tks. Clear. Would be useful to post that on your WordOps home page I think.

**Comment by tdtgit** [comment]
I see some [users say they can setup on RPi4](https://community.wordops.net/d/1063-is-it-possible-to-use-a-different-port-for-my-wordpress-website), maybe you can ask them on their setup, device,...

**Comment by admarty** [comment]
@dede34fr 
Instead of `wo stack install --nginx` you can use `sudo bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --stable`

More details :
[https://github.com/VirtuBox/nginx-ee](url)
