### ISSUE TITLE
Double slashes xmlrpc.php

### ISSUE THREAD

**Issue by tersor** [WordOps/WordOps#385]
Hello.

Our access logs had a high number of requests like this:

```
"POST //xmlrpc.php HTTP/1.1" 200
```

Default nginx behaviour is to merge double slashes, and these requests does not match the [location rule](https://github.com/WordOps/WordOps/blob/master/wo/cli/templates/wpcommon.mustache#L16) for `xmlrpc.php`.

To fix this I added the following in `/etc/nginx/common/locations-wo.conf`:

```
...
merge_slashes off;
location = //xmlrpc.php {
    deny all;
}
```

I would think a more permanent fix in WordOps templates is preferable. See also [this article](https://madebot.com/blocking-bad-bots-in-nginx-from-xmlrpc-php/).

**Comment by tdtgit** [comment]
I not know Nginx will merge doubleslash by default.

What about tripple slash, `////`? If Nginx still match the above rule, I will make a PR

**Comment by tersor** [comment]
> What about tripple slash

Yes, we probably need a regex that [catches multiple slashes](https://stackoverflow.com/a/14867809).
