### ISSUE TITLE
Netdata Username and Password

### ISSUE THREAD

**Issue by pecker99956** [WordOps/WordOps#389]
How to retrieve netdata login username and Password. By Mistake forgot to note down.

**Comment by vikas5914** [comment]
@pecker99956  wo secure --auth

**Comment by pecker99956** [comment]
https://xxx.xxx.xxx.xx:22222/netdata/
Got 502 Bad Gateway

-----

https://xxx.xxx.xxx.xx:22222/

Index of /
../
cache/                                             29-Jun-2021 10:25                   -
fpm/                                               29-Jun-2021 10:25                   -
php/                                               29-Jun-2021 10:25                   -

**Comment by pecker99956** [comment]
Got it.. just try above and forgot to install : wo stack install
