### ISSUE TITLE
Installing netdata stack throws error in AWS Graviton2 (arm64 architecture)

### ISSUE THREAD

**Issue by ceefour** [WordOps/WordOps#393]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

## How to reproduce

1. Launch an t4g.micro or m6g.medium instance in AWS
2. Install WordOps
3. `sudo -E wo stack install --dashboard --netdata`

Expected: Success

But got:

```
# sudo -E wo stack install --netdata
Downloading Netdata              [Done]
Installing Netdata              [OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/stack.py", line 537, in install
    post_pref(self, [], packages)
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/plugins/stack_pref.py", line 1414, in post_pref
    .format(wo_netdata),
UnboundLocalError: local variable 'wo_netdata' referenced before assignment
```

Related to #392

**Comment by admarty** [comment]
> @ceefour the patch you have applied will it also fix the nginx setup for WordOps on ARM64 ?

instead of `wo stack install --nginx` you can use `sudo bash <(wget -O - vtb.cx/nginx-ee || curl -sL vtb.cx/nginx-ee) --stable`

More details :
[https://github.com/VirtuBox/nginx-ee](url)

**Comment by thecancerus** [comment]
the working answer is at https://github.com/WordOps/WordOps/issues/418,

@admarty  thanks, still can this be actually merged with WordOps _stack install_ command? instead of having to type separately?

**Comment by admarty** [comment]
Until now, that's the only way.

`wo stack install` uses this repository to install NGINX [https://build.opensuse.org/package/show/home:virtubox:WordOps/nginx](url) 

The problem is that this repository doesn't have packages for arm64, so we have to build a compatible nginx from source for Wordops.
