### ISSUE TITLE
Feature idea: Dynamic --wpfc cache control

### ISSUE THREAD

**Issue by ddur** [WordOps/WordOps#395]
IMHO, it should be possible to dynamically disable caching per page/post/URL, using [**$sent_http_**_name_](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_sent_http_) from upstream server (PHP) with name "Cache-Control (Nginx variable **$sent_http_**_cache_control_)" and [_value "no-store"_](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control).

If you can, and do it, maybe I will make plugin for WordOps that will selectively (per page, post or URL) set that header from upstream WordPress server.

BTW, same modification maybe can be applied to other cache systems?

**Comment by tersor** [comment]
@ddur 

Take a look at [this article](https://docs.wordops.net/how-to/bypass-fastcgi-cache-on-specific-urls/).

**Comment by ddur** [comment]
@tersor

Thanks for [the article link](https://docs.wordops.net/how-to/bypass-fastcgi-cache-on-specific-urls/).

### Method 1)
Solution is hard-coded. Unmanageable by WordPress user and requires root administrator intervention. Exactly the problem we would like to avoid and resolve.

### Method 2)
That solution is partial as it works on all sub-directories of URL and depends on browser accepting cookies.
As far as I can tell, current WordOps cache configuration detects only **request** (browser) cookies.
Cache is not skipped on first **request** without cookie, only on next **request**, after browser cookie is set.

### Proposed solution
I propose to use $sent_http_cache_control variable which is set by upstream server **response** _Cache-Control_ header. Idea is not to skip cache on browser **request** but to clear & prevent further caching of that URL, whenever **response** header is sent. Regardless & overriding Nginx/WordOps cache configuration. This may even work for CDN cache?

**Comment by ddur** [comment]
Actually, sending Cache-Control: (no-store), either from WordOps/Nginx or from PHP should be handled by any CDN or proxy or reverse-proxy server. I guess that includes --wpfc too.
