### ISSUE TITLE
wo: command not found + wo: error: unrecognized arguments:

### ISSUE THREAD

**Issue by crystaler4** [WordOps/WordOps#398]
first, I installed Wordops on VSP server (KVM) with Ubuntu 20.04, then with Ubuntu 18.04.

In both cases I run into `wo: command not found` and after `sudo -H pip3 uninstall wordops && sudo -H pip3 install wordops` I had `wo: error: unrecognized arguments: sudo wo site create site.com -wp`.

What to do?

System Information:

- [x ] `lsb_release -a`

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

- [ x] `wo info`

usage: wo (sub-commands ...) [options ...] {arguments ...}
wo: error: unrecognized arguments: info

- [x ] `nginx -V`

Command 'nginx' not found, but can be installed with:

apt install nginx-core  
apt install nginx-extras
apt install nginx-full  
apt install nginx-light

- [x ] `wo -v`

WordOps v3.13.2
Copyright (c) 2020 WordOps

- [ x] `wp cli info --allow-root`

/usr/bin/env: ‘php’: No such file or directory

- [x ] `curl -sL git.io/fjAp3 | sudo -E bash -`

Here the link to provide in your github issue : Could not upload empty file

**Comment by harsh8511** [comment]
# python3 -m pip uninstall setuptools==58.0.4

# python3 -m pip install -I setuptools==57.5.0

# sudo rm -f /usr/local/bin/wo && wget -qO wo wops.cc && sudo bash wo

solution from WordOps community
