### ISSUE TITLE
WordOps Future

### ISSUE THREAD

**Issue by panaras10** [WordOps/WordOps#401]
Hi guys,

Is this project abandoned or still actively supported? I'm extremely happy with it but I don't want to build my infrastructure on a soon-to-be deprecated system. According to the project roadmap, the last update was on the 8th of Jan.

Thanks!

**Comment by yazzou** [comment]
Hi 
Maybe a reply to your question 
https://twitter.com/Thomas_VirtuBox/status/1438186054637563910

**Comment by VirtuBox** [comment]
> Hi guys,
> 
> Is this project abandoned or still actively supported? I'm extremely happy with it but I don't want to build my infrastructure on a soon-to-be deprecated system. According to the project roadmap, the last update was on the 8th of Jan.
> 
> Thanks!

Hello @panaras10,
after few months without update, I'm working again on WordOps and a new major release will be available soon.

**Comment by hacen-ai** [comment]
@VirtuBox Thank your for your great work... Can we hope a docker image?

**Comment by justingivens** [comment]
@VirtuBox in what ways could we help?

**Comment by harsh8511** [comment]
> > Hi guys,
> > Is this project abandoned or still actively supported? I'm extremely happy with it but I don't want to build my infrastructure on a soon-to-be deprecated system. According to the project roadmap, the last update was on the 8th of Jan.
> > Thanks!
> 
> Hello @panaras10, after few months without update, I'm working again on WordOps and a new major release will be available soon.

Hey @VirtuBox are still working on this release?

**Comment by backamblock** [comment]
sad to see. now after i spent a whole day to research and decide for wordops over slickstack, just to find out it's no longer of main interest.. damn :D
