### ISSUE TITLE
Wordops is compatible with Debian11 ?

### ISSUE THREAD

**Issue by mscice** [WordOps/WordOps#403]
hello just a quick one.. can wordops be installed on Debian11?

**Comment by buzucan** [comment]
No

**Comment by mscice** [comment]
Thank you for your hard work, if it's not too much to ask can we get 10.6.7 mariadb added?

**Comment by Slapbox** [comment]
Thanks for your great work @VirtuBox! 

With Debian 9 EOL yesterday I'm wondering, any update on this?

**Comment by Slapbox** [comment]
@VirtuBox any update on Debian 11 support? Just a rough eta? Should we expect to see it this year?

**Comment by Slapbox** [comment]
And is there anything users can contribute to help with this? @VirtuBox

**Comment by buzucan** [comment]
now is compatible. :)
