### ISSUE TITLE
Use the flag --force to bypass this check.

### ISSUE THREAD

**Issue by rockydares** [WordOps/WordOps#409]
mydomain.com point to the IP 172.67.xxx.xxx but your server IP is 51.xx.xxx.xxx
Use the flag --force to bypass this check.

How to force? WP site not opening.

**Comment by ridgegate** [comment]
Did you edit your hosts file to point your domain to a specific IP? I had the same issue until I removed the record in hosts file.

**Comment by ravi923615** [comment]
If you are using a Proxy server in between, Like I was using Ezoic DNS as a proxy then it will not work. And the only option you have is to use the Ezoic SSL or whichever proxy you are using. Else you will need to remove all the cache or CDN in between first and then try.
