### ISSUE TITLE
Default Nginx page

### ISSUE THREAD

**Issue by rockydares** [WordOps/WordOps#410]
Default nginx page opens after set up, I have to manually configure nginx to route it to my wordpress directory? I tried to set up an easy wordpress site but it's giving me headache.

**Comment by juanpvh** [comment]
https://docs.wordops.net/getting-started/creating-sites/

**Comment by Matlino** [comment]
Are you by any chance migrating site, so you specified domain (while creating wo site) which is pointing to other IP address?

This was my case. And it was behaving the same way, I could see only the default Nginx page when tried to access the page through IP. And domain was of course still pointed to another server. 

It seems to me that for some reason WP sites cannot be accessed directly by IP address. I don't know if this is a bug or feature and couldn't find the answer by a quick search. Maybe somebody more experienced can explain this.

Anyway, the solution for me was to change local host file, and point my domain to the new server. This way I could access WP and log in using the domain:
https://setapp.com/how-to/edit-mac-hosts-file

**Comment by mikelittle** [comment]
When Nginx gets a request by ip address it will use the configured default server settings. Like
```
server {
    listen 80 default_server;
    listen [::]:80 default_server deferred;
 ...
}
```
With no or an invalid server_name. 

I guess WordOps sets its own panel as the default You would need to make the newly created virtual server for the site the default like
```
server {
    listen 80 default;
    listen [::]:80 default;
    server_name example.com;
     ...
}
```

Which WordOps doesn't do by default.

**Comment by mwt** [comment]
I had this issue as well when I tried to install. I ended up resetting and doing everything manually. The config for the WordPress site when you run:

```bash
wo site create site.tld --wp
```

**does not listen on any port.** I don't know what the deal is, but only the "default" site that nginx preinstalls was listening to a port. This is obviously not intended, but I do not understand the WordOps setup well enough to fix it. Where are the statements to listen to ports 80 and 443 supposed to be loaded from?

If I delete the default site and reload nginx, nginx listens only on port 22222. This is on Ubuntu Focal.

**Comment by vikas5914** [comment]
@mwt , does not listen on any port => From docs.nginx.com: `If the listen directive is not included at all, the “standard” port is 80/tcp`

For the 443 port, once you install SSL using lets-encrypt, It will create a file at `/var/www/<site_name>/conf/nginx/ssl.conf` with the following content, and this will be included in the **server block**. 

```
listen 443 ssl http2;
listen [::]:443 ssl http2;
ssl_certificate     <path to files>/fullchain.pem;
ssl_certificate_key     <path to files>/key.pem;
ssl_trusted_certificate <path to files>/ca.pem;
ssl_stapling_verify on;
```

This answers your question about where ports 80 and 443 are loaded. 

Without enabling letsencrypt, the site will not work. => Can you provide more information here? Screenshot of the error you are getting. the Nginx config from the **sites-available folder**.

**Comment by mwt** [comment]
Hi,

Yes, the directive to listen on port 80 is missing from the configuration until I install LetsEncrypt. As a result, the only port 80 directive that exists is in the `default` site that nginx installs.

To clarify, when you don't install LE, the site does not listen on 443 or 80. It doesn't listen on any port. **The bug is that it does not listen on port 80 as expected.**

When you install LE, it listens on 80,443 but http redirects to https (as expected).

I've reproduced this several times now. The steps are just:

```bash
wget -qO wo wops.cc && sudo bash wo
sudo wo site create site.tld --wp 
```

If you run this command, you will get a file in `/etc/nginx/sites-enabled/site.tld`. the contents of this file will be:

```nginx
server {
    server_name site.tld www.site.tld;
    access_log /var/log/nginx/site.tld.access.log rt_cache;
    error_log /var/log/nginx/site.tld.error.log;
    root /var/www/site.tld/htdocs;
    index index.php index.html index.htm;
    include common/php80.conf;
    include common/wpcommon-php80.conf;
    include common/locations-wo.conf;
    include /var/www/site.tld/conf/nginx/*.conf;
}
```

Note that there is no directive to listen on port 80. So, it will not listen on every interface.

You can test this by running:

```bash
curl -H'Host: site.tld' localhost
```
or

```bash
curl -H'Host: site.tld' $(curl -s ifconfig.me)
```

The result will be the familiar 

```html
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

Without specifying a listen directive, nginx will listen on port 80 of *some* interfaces by default. For example, the following curl command works for me:

```bash
curl -H'Host: site.tld' 127.0.0.2
```

But, in my case, it doesn't listen on any non-loopback interfaces without specifying to listen on port 80.

Let me know if you have issues reproducing.

**Comment by vikas5914** [comment]
@mwt There is something wrong with your server. I checked on a new version, and the result is different. 

I run the command: 
```
wget -qO wo wops.cc && sudo bash wo
sudo wo site create site.tld --wp 
```

and this is my server block from `/etc/nginx/sites-enabled/site.tld`

```
server {


    server_name site.tld www.site.tld;


    access_log /var/log/nginx/site.tld.access.log rt_cache;
    error_log /var/log/nginx/site.tld.error.log;


    root /var/www/site.tld/htdocs;

    index index.php index.html index.htm;


    include common/php80.conf;
    
    include common/wpcommon-php80.conf;
    include common/locations-wo.conf;
    include /var/www/site.tld/conf/nginx/*.conf;

}
```

and running the curl command: 
```
root@ubuntu-s-1vcpu-2gb-sgp1-01:~# curl -H'Host: site.tld' 127.0.0.1
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@ubuntu-s-1vcpu-2gb-sgp1-01:~# 
```

The response is different. If you want I can check your server and debug this issue in detail. Send me server access to `vikas@kapadiya.net`

**Comment by mwt** [comment]
I get the same result. Those two config files are the same as far as I can tell, and running `curl -H'Host: site.tld' 127.0.0.1` also gives me the forbidden page. This is still broken though as I should get the site.

What gave me the default page was `curl -H'Host: site.tld' localhost` which actually maps to `::1` rather that `127.0.0.1`.

This distinction usually doesn't matter. It goes to show just how unpredictable the results of omitting the port 80 listen directive can be. The script should really tell nginx to listen on port 80 in the actual config.

**Comment by vikas5914** [comment]
@mwt again. Nginx server bl,ock by default listens to port 80. I did the test again, but this time with the actual domain. 

So the question is why curl requests are failing. After checking everything found the answer. 

if you check the log files at `/var/log/nginx/error.log` you will see the following errors: 

```log
2022/09/01 17:08:59 [error] 33024#33024: *23 directory index of "/var/www/22222/htdocs/" is forbidden, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "127.0.0.1"
2022/09/01 17:09:06 [error] 33024#33024: *24 directory index of "/var/www/22222/htdocs/" is forbidden, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "127.0.0.1"
2022/09/01 17:11:12 [error] 33024#33024: *25 directory index of "/var/www/22222/htdocs/" is forbidden, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "foo.com"
```

Seems like curl requests are handled by a different server block.  and that host is located at `/etc/nginx/conf.d/stub_status.conf` with following content: 

```nginx
# Stub status NGINX CONFIGURATION
# DO NOT MODIFY, ALL CHANGES WILL BE LOST AFTER AN WordOps (wo) UPDATE
server {
    listen 127.0.0.1:80;
    server_name 127.0.0.1 localhost;
    access_log off;
    log_not_found off;
    root /var/www/22222/htdocs;
    allow 127.0.0.1;
    deny all;
    location ~ /(stub_status|nginx_status) {
        stub_status on;
        allow 127.0.0.1;
        deny all;
        access_log off;
        log_not_found off;
    }
}
```

The above block is the reason for **your 403 errors.** 

Now let's do the following: 
``` shell
mv stub_status.conf stub_status.conf.disable
nginx -t
wo stack restart --nginx
```

Now if you try the `curl -H'Host: site.tld' 127.0.0.1`, you will get the Wordpress website. 
``` HTML
<!DOCTYPE html>
<html lang="en-US">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name='robots' content='max-image-preview:large' />
<title>site.tld &#8211; Just another WordPress site</title>
<link rel='dns-prefetch' href='//s.w.org' />
<link rel="alternate" type="application/rss+xml" title="site.tld &raquo; Feed" href="http://site.tld/feed/" />
<link rel="alternate" type="application/rss+xml" title="site.tld &raquo; Comments Feed" href="http://site.tld/comments/feed/" />
<script>
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"http:\/\/site.tld\/wp-includes\/js\/wp-emoji-release.min.js?ver=6.0.2"}};
/*! This file is auto-generated */
!function(e,a,t){var n,r,o,i=a.createElement("canvas"),p=i.getContext&&i.getContext("2d");function s(e,t){var a=String.fromCharCode,e=(p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,e),0,0),i.toDataURL());return p.clearRect(0,0,i.width,i.height),p.fillText(a.apply(this,t),0,0),e===i.toDataURL()}function c(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(o=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},r=0;r<o.length;r++)t.supports[o[r]]=function(e){if(!p||!p.fillText)return!1;switch(p.textBaseline="top",p.font="600 32px Arial",e){case"flag":return s([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])?!1:!s([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!s([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]);case"emoji":return!s([129777,127995,8205,129778,127999],[129777,127995,8203,129778,127999])}return!1}(o[r]),t.supports.everything=t.supports.everything&&t.supports[o[r]],"flag"!==o[r]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[o[r]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(e=t.source||{}).concatemoji?c(e.concatemoji):e.wpemoji&&e.twemoji&&(c(e.twemoji),c(e.wpemoji)))}(window,document,window._wpemojiSettings);
</script>
<style>
.......
```

On to the `curl -H'Host: site.tld' localhost` => I don't think this is an issue. Majority time we use IPV4 for the server. Websites point to the IP, not the localhost. I have yet to see this causing any issue.

I have been using WordOps for more than 3 years and Before I have using EaysEngine. Both did not have the listen in the server block. Hack even the Nginx documentation doesn't use listen in the server block example. So don't worry about the **listen part in the server example.**

**Comment by KeesCBakker** [comment]
This drove me crazy, as it is still a problem with new installs. A workaround for me was creating a listen nginx config that survives updates:

```sh
#!/usr/bin/env bash
set -euo pipefail

TLD="${1:?usage: $0 <tld> [port]}"
PORT="${2:-80}"

DIR="/var/www/$TLD"
f="$DIR/conf/nginx/listen.conf"

[[ -d "$DIR" ]] || { echo "Site dir not found: $DIR" >&2; exit 1; }
[[ -f "$f" ]] && { echo "OK: $f already exists"; exit 0; }

sudo mkdir -p "$(dirname "$f")"

sudo tee "$f" >/dev/null <<EOF
listen $PORT;
listen [::]:$PORT;
EOF

sudo nginx -t && sudo systemctl reload nginx
echo "OK: created and reloaded"
```
