### ISSUE TITLE
php upstream error 

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#411]
I noticed that the cache was not being read and delivered by nginx, I checked the log at:
/var/log/nginx/*.error.log

2021/12/08 14:26:00 [alert] 4045#4045: *226 write() "/var/run/nginx-cache/2/ba/01a9ae5dc47313d2ff0f079ae0861ba2.0000000431" failed (28: No space left on device) while reading upstream, client: 170.244.86.116, server: sitetld.xyz, request: "GET /sitetld/HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php74-two-fpm. sock:", host: "sitetld.xyz", referrer: "https://www.google.com/"

I verified that tmpfs /run is always full:

root@vultr:~# df -h
Filesystem Size Used Avail Use% Mounted on
udev 447M 0 447M 0% /dev
tmpfs 99M 99M 0 100% /run
/dev/vda1 30G 8.3G 21G 30% /
tmpfs 491M 424K 491M 1% /dev/shm
tmpfs 5.0M 0 5.0M 0% /run/lock
tmpfs 491M 0 491M 0% /sys/fs/cgroup
tmpfs 99M 0 99M 0% /run/user/0

Has anyone had this problem? and how did you solve it?

Linux vultr 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20,04

@VirtuBox

**Comment by tersor** [comment]
This issue is somewhat unrelated to WordOps. 

Anyways, can you run `wo maintenance`?
This will clean up any unused kernels freeing up disk space, which might fix the issue.

If you run into `No space left on device` when running `wo maintenance`, [take a look at this](https://askubuntu.com/questions/89710/how-do-i-free-up-more-space-in-boot).

**Comment by juanpvh** [comment]
you guessed a random response, don't do it.

what would be a problem unrelated to wordops, if not the LEMP stack?

you didn't read what I wrote, problem related to the /run directory

**Comment by janiosarmento** [comment]
@tersor is 100% correct, and you are being nothing but stupid by attacking him.

Also, he gave you exactly what you need to solve your problem.

A script in cron (just a `find -m... -delete`) allows me to automatically clear old files in `/run` so that I don't face this issue.

**Comment by juanpvh** [comment]
@janiosarmento stupid is your comment and you.  kicking "solutions" as a hitting argument.  you are just a child.

**Comment by janiosarmento** [comment]
Okay then. I wish you success.
