### ISSUE TITLE
No error treatment to /opt/cf-update.sh

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#420]
There's a script (`/opt/cf-update.sh`) responsible for refreshing the Cloudflare's IP list in Nginx/WO.

It has been working flawlessly for years, for me. But yesterday Cloudflare rather than serving the lists of IPs delivered an error page just at the moment the script was running (see image attached).

![Captura de Tela 2022-02-11 às 18 22 08](https://user-images.githubusercontent.com/7367281/153721397-0870b40b-d28e-4ce4-aa09-172443e22d8f.png)

I can update the script to add basic validation (I already did it in my servers), but I can't find where, in the repository, it's located to send a proper PR.

**Comment by vikas5914** [comment]
@janiosarmento I found this: https://github.com/WordOps/WordOps/blob/c80bb6466211b68ae4f3ea9c3f45bbb95106e043/wo/cli/templates/cf-update.mustache

and https://github.com/WordOps/WordOps/blob/0525c40912d0b64fcad1edb11cc6f93c424d32e0/wo/cli/plugins/stack_pref.py#L423

**Comment by janiosarmento** [comment]
Thank you, @vikas5914!

I'll work on a fix for the script.
