### ISSUE TITLE
Wordops nginx already installed.

### ISSUE THREAD

**Issue by shyambaseapp** [WordOps/WordOps#424]
WordOps detected a previously installed Nginx package. It may or may not have the required modules. 
If you need help, please create an issue at https://github.com/WordOps/WordOps/issues/ 

Applying Nginx configuration templates
Testing Nginx configuration     [KO]
Testing Nginx configuration     [KO]
Running pre-update checks       [KO]
NGINX configuration check failed.

**Comment by PetyXbron** [comment]
I am having same problem right now

**Comment by PetyXbron** [comment]
**I go further by uninstalling Nginx with `apt-get purge nginx nginx-common nginx-full`**

Then I am getting error with database setup (`pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")`)

**Comment by PetyXbron** [comment]
**@VirtuBox do you know how to fix this error, please?**
Is something wrong with the python?

**Comment by PetyXbron** [comment]
I figured it out. I wasn't entering any password, because I didn't know the command. And I even didn't know it.
I was trying to reset my password and set a new one, but I totally broke the MySQL package so I need to hard reinstall it now.
I am having problems with it. Why it's so complicated to fully reinstall some dependency? 😒

**Comment by PetyXbron** [comment]
I somehow totally uninstalled MySQL! 🎉 
(It was probably by command `sudo apt-get remove --purge mysql.*`)
And I got further again. But I am facing a new issue again. 🙃 
**Now I got a problem with installing WordPress;**
![image](https://user-images.githubusercontent.com/35902119/183503235-935be580-6b1b-4611-95ec-3326d587b505.png)
**This is the debug log:**
![image](https://user-images.githubusercontent.com/35902119/183503693-81af04d9-b3d0-4ef8-b3b3-e079ed0c9634.png)
**I think it's a problem with MySQL again. @VirtuBox do you have any idea, please?**

**Comment by PetyXbron** [comment]
![image](https://user-images.githubusercontent.com/35902119/183505793-f48544a0-7eec-4f38-9e89-34382eb52058.png)

**Comment by PetyXbron** [comment]
After a complete VPS reinstall, I could start the WordOps installation again with a 100% clean system.
**Everything went right.** *(Did I just solve this issue myself without any help?)*
