### ISSUE TITLE
Suggested Feature: Run sites as different user.

### ISSUE THREAD

**Issue by plutocrat** [WordOps/WordOps#425]
I've been running Wordpress and other CMSes on Linux for 20 years or so. I only just discovered WordOps, and like what its doing, but there's one think that niggles at me: the fact that the websites are stored in /var/www/ and owned by www-data. 

I'm coming at this as a person who does a lot of server admin, but generally leaves all the WP work to a developer. The current situation means its very hard to give access to a developer. www-data is not a login account, so you basically need root to be able to update the server. Also you can't run wp-cli as www-data, and need the  --allow-root flag to run it as root, the only other available option. Also, devs need to be really careful to set the file ownership back to www-data. 

My suggestion would be to make a new login,  such as webdev, and put the files in there, with nginx running as the correct user. Developers could then get at the files they need to, run wp-cli, and not have to worry about setting the correct ownership. The developer role could be separated from the systemsadmin rule, with separate logins, separate ssh keys. 

Even better, and perhaps some way in the future, several users could be set up and sites allocated among them, so that different websites could be worked on by different developers.

**Comment by tersor** [comment]
Related to #41.

**Comment by plutocrat** [comment]
Thanks. I didn't see the previous discussion. Perhaps creating a single 'webdev' user and running all sites under that could be the first step towards #41.

**Comment by janiosarmento** [comment]
The site files are already placed under a specific user: `www-data`. I really don't understand what's the point of changing the username only.

**Comment by plutocrat** [comment]
www-data is a system user, without a login. Currently in order to do anything you need to login as root, which is not a great thing security-wise. You also have to be very careful with file ownership and chown everything back to www-data. 
Having a separate user means you can login via ssh as that user, and edit files without any permissions problems. You can run wp-cli correctly. You can separate the functions of server admin and developer: for example I can let a third party developer edit files, without giving away root access to my server.

**Comment by janiosarmento** [comment]
You always can `chroot` a given user to a directory inside `/var/www`.

**Comment by janiosarmento** [comment]
Also:

https://entropie.is/en/blog/bindfs

**Comment by jasomdotnet** [comment]
How to enable www-data as login user

https://easyengine.io/tutorials/linux/setup-sftp/
