### ISSUE TITLE
Constant WP_DEBUG already defined

### ISSUE THREAD

**Issue by exandeer** [WordOps/WordOps#426]
Hello,

On WordOps v3.14.1

I create new website with:
`wo site create www.domain.tld --wp --php74 -le`

Then I install Query Monitor plugin, it says "Constant WP_DEBUG already defined"
Checked the wp-config.php and found two `define( 'WP_DEBUG', false );`

Thank you

**Comment by VirtuBox** [comment]
Hello @exandeer,
thanks for your report, I'm working on it.
