### ISSUE TITLE
Constant WP_DEBUG already defined in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php

### ISSUE THREAD

**Issue by sschemedotcom** [WordOps/WordOps#429]
sudo -u www-data -H wp db clean --yes --path=/var/www/domain.com/htdocs

PHP Warning:  Constant WP_DEBUG already defined in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1277) : eval()'d code on line 91
Success: Tables dropped.

I clean up the data to upload the code to report the error as above

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
