### ISSUE TITLE
Ubuntu Jammy Jellyfish (22.04)

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#430]
Hi there,

Has anyone tried WO on Ubuntu 22.04?

**Comment by VirtuBox** [comment]
Hello @janiosarmento, 
I'm working on it but I still have to publish new Nginx packages.

**Comment by cristian-milea** [comment]
After WordOps 4.0 is available, will there be anything special to do after `sudo do-release-upgrade -d`?

I just tried now, and `wo` stopped working after ubuntu upgrade, had to install it again and run `wo stack install`

**Comment by VirtuBox** [comment]
Ubuntu 22.04 LTS support is now available
