### ISSUE TITLE
Upgrade Mariadb 10.5 stable to 10.6 stable

### ISSUE THREAD

**Issue by andremacola** [WordOps/WordOps#431]
MariaDB 10.6 is the current long-term support stable version and is faster than 10.5

**Comment by VirtuBox** [comment]
Hello @andremacola,
MariaDB upgrade to 10.6 is planned, but I still have to test the upgrade enough to make sure there is no issue.

**Comment by tharlab** [comment]
> Hello @andremacola, MariaDB upgrade to 10.6 is planned, but I still have to test the upgrade enough to make sure there is no issue.

hi is there any option if possible, to choose mariadb version during installation i'm still using 10.5.xx
idont want to upgrade cz it cause database fail, and i have big and alot of table

**Comment by VirtuBox** [comment]
MariaDB 10.6 is now shipped with WordOps
