### ISSUE TITLE
Move to official APT repository for Redis

### ISSUE THREAD

**Issue by yogeshbeniwal** [WordOps/WordOps#433]
Better to move to [official APT repository for Redis](https://redis.io/docs/getting-started/installation/install-redis-on-linux/), Relevant discussion on gap in time for package release and delivery is [here](https://twitter.com/yogeshbeniwal/status/1519637808079466496).

**Comment by VirtuBox** [comment]
Hello @yogeshbeniwal, thanks for your report. It will be done soon.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
