### ISSUE TITLE
Nginx for Arm (Oracle OCI)

### ISSUE THREAD

**Issue by AdsonCicilioti** [WordOps/WordOps#435]
Nginx do not install on Ampera ARM cpu instance from Oracle OCI.

**Comment by Ethical-Cronos** [comment]
If I'm not mistaken, wordops was recently compatible with AWS's ARM architecture, but just rereading the updates again, to be sure

**Comment by AdsonCicilioti** [comment]
Yes @Ethical-Cronos, I've seen that it inserts a PPA for a `nginx-custom` and `nginx-ee`, but somehow the moment the script asks APT to install it finds no candidate and the Stack install fails.

**Comment by ridgegate** [comment]
Look at this post.. I had it working on Oracle OCI but I did not end up using it.

https://github.com/WordOps/WordOps/issues/418
