### ISSUE TITLE
proftpd isn't working

### ISSUE THREAD

**Issue by ibrahimhajjaj** [WordOps/WordOps#437]
I followed the exact steps on this guide for adding an FTP user for a website but it doesn't connect, I've tried to use the server IP and domain name, and also I tried to use this format for the user { User@domain-name.com } but it refuse to connect.

Worth of mention that I got this warning after I added the user 

```
The home directory `/var/www/domain.com/htdocs/' already exists.  Not copying from `/etc/skel'.
adduser: Warning: The home directory `/var/www/domain.com/htdocs/' does not belong to the user you are currently creating.
```

**Comment by harsh8511** [comment]
you can safely ignore the warning, allow this port in firewall and then try

21
49000:50000

**Comment by ibrahimhajjaj** [comment]
@harsh8511 Already tried this and it didn't work...

I've Ingress / tcp:22, 60000-65535

```
Error:	Could not connect to server
Status:	Waiting to retry...
```

**Comment by ibrahimhajjaj** [comment]
@VirtuBox  any help :)
