### ISSUE TITLE
Redis Service is not set to Autostart. 

### ISSUE THREAD

**Issue by ankitsnlq** [WordOps/WordOps#44]
System Information

- [x] lsb_release -a
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

- [x] wo info
wo info 
/bin/sh: 1: Syntax error: "&" unexpected
'Error while getting parameter.'
- [x] nginx -V
nginx -V
nginx version: nginx/1.14.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.0g  2 Nov 2017 (running with OpenSSL 1.1.1b  26 Feb 2019)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

- [x] wo -v
wo -v
WordOps v3.9.4
Copyright (c) 2019 WordOps.

- [x] wp --allow-root info
wp --allow-root info
Warning: No WordPress installation found. If the command 'info' is in a plugin or theme, pass --path=`path/to/wordpress`.
Error: 'info' is not a registered wp command. See 'wp help' for available commands.

On a fresh install of Wordops, I just reboot the system after everything setup, found out that redis was not running after restart. 

```
redis-cli 
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
Then I check system start status, redis service was disabled. 

```
systemctl is-enabled redis-server.service 
disabled
```
I enabled service and after reboot this time redis was running. Could you please set redis service to auto start during wordops setup?

**Comment by nsgoyat** [comment]
+1 for this. Always happens with me so I manually enable redis on system start for all new installations.

**Comment by VirtuBox** [comment]
Hello, I will add a step to check redis service status after install and to make sure systemd service is properly enabled

**Comment by VirtuBox** [comment]
Issue should be fixed with the PR https://github.com/WordOps/WordOps/pull/45
