### ISSUE TITLE
Add /.well-known/traffic-advice file for 404 reduction and, of course, for Chrome Privacy Preserving Prefetch Proxy

### ISSUE THREAD

**Issue by jasomdotnet** [WordOps/WordOps#440]
Hi, first of all - great job with the WordOps!

Now the feature suggestion: 

I have been investigating logs recently and found lot of "404, page not found" requests by "Chrome Privacy Preserving Prefetch Proxy" bot. 

TLTR: Google preloads page for Chrome users which browser thinks user is going to visit next (or what). File under the URL https://www.exampe.com/.well-known/traffic-advice informs this proxy bot how often prefetch and if at all. Something like robots.txt but for users.

I suggest to add file `/var/www/html/.well-known/traffic-advice` with content

```
[{
  "user_agent": "prefetch-proxy",
  "google_prefetch_proxy_eap": {
    "fraction": 1.0
  }
}]
```
and extend `/etc/nginx/common/locations-wo.conf` with the config:
```
# Private Prefetch Proxy
# https://developer.chrome.com/blog/private-prefetch-proxy/
location /.well-known/traffic-advice {
   types { } default_type "application/trafficadvice+json; charset=utf-8";
   alias /var/www/html/.well-known/traffic-advice;
   allow all;
}
```
More info and config test tool [here](https://www.jasom.net/private-prefetch-proxy-well-known-traffic-advice-apache-htaccess-nginx/)

**Comment by VirtuBox** [comment]
Hello @jasomdotnet,
this will be added in the next WordOps release.

**Comment by VirtuBox** [comment]
@jasomdotnet Does I have to create the empty directory `/var/www/html/.well-known/traffic-advice` or it's not required ?

**Comment by jasomdotnet** [comment]
@VirtuBox, I did not get your question 

`traffic-advice` is a text file (text response on the request `example.com/.well-known/traffic-advice`) with the content like 
```
[{
  "user_agent": "prefetch-proxy",
  "google_prefetch_proxy_eap": {
    "fraction": 1.0
  }
}]
```
and with a special mime type achieved by the config
```
# Private Prefetch Proxy
# https://developer.chrome.com/blog/private-prefetch-proxy/
location /.well-known/traffic-advice {
   types { } default_type "application/trafficadvice+json; charset=utf-8";
   alias /var/www/html/.well-known/traffic-advice;
   allow all;
}
```

**Comment by VirtuBox** [comment]
@jasomdotnet okay thanks. I'm going to add it to WordOps.
