### ISSUE TITLE
Wo Stack Upgrade Stuck at Upgrading Netdata Step.

### ISSUE THREAD

**Issue by emanweb** [WordOps/WordOps#447]
After type > wo stack upgrade
WordOps dashboard is not installed
Your sites may be down for few seconds if you are upgrading Nginx, PHP-FPM, MariaDB or Redis
Do you want to continue:[y/N]y
Adding repository for NGINX, please wait...
Updating APT cache              [OK]
Applying Nginx configuration templates
Testing Nginx configuration     [OK]
Restarting Nginx                [OK]
Testing Nginx configuration     [OK]
Restarting Nginx                [OK]
Configuring php7.3-fpm
Restarting php7.3-fpm           [OK]
Configuring php7.4-fpm
Restarting php7.4-fpm           [OK]
Tuning MySQL configuration      [OK]
Restarting mysql                [OK]
Restarting fail2ban             [OK]
Configuring Fail2Ban
Restarting fail2ban             [OK]
Configuring APT Packages        [OK]
Downloading WP-CLI               [Done]
Downloading Netdata              [Done]
Downloading PHPMyAdmin           [Done]
Downloading Adminer              [Done]
Downloading Adminer theme        [Done]
Downloading Composer             [Done]
Downloading MySQLTuner           [Done]
Stop  : netdata   [OK]
Upgrading Netdata               [..]

System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

- [ ] `wo info`
NGINX (1.20.2 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1
PHP 7.2 is not installed

PHP (7.3.33-4):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

PHP (7.4.30):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.5.16-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             5
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] `nginx -V`
nginx version: nginx/1.20.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-ohntSF/nginx-1.20.2=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/headers-more-nginx-module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/nginx-auth-pam --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/nginx-cache-purge --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/nginx-echo --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/nginx-upstream-fair --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/memc-nginx-module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/srcache-nginx-module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/HttpRedisModule --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/redis2-nginx-module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/ngx_devel_kit --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/set-misc-nginx-module --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/nginx-module-vts --add-module=/build/nginx-ohntSF/nginx-1.20.2/debian/modules/ngx_brotli

- [ ] `wo -v`
WordOps v3.14.2
Copyright (c) 2022 WordOps.

- [ ] `wp cli info --allow-root`
OS:     Linux 5.4.0-1063-aws #66~18.04.1-Ubuntu SMP Thu Jan 13 19:45:37 UTC 2022 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.30
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/html
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.6.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`
Here the link to provide in your github issue : https://transfer.vtbox.net/FaVHDJ/wordops.txt

**Comment by VirtuBox** [comment]
Hello @emanweb, thanks for reporting this issue. I'm working on a fix.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`

**Comment by mac-linux-free** [comment]
sadly not...it still hangs on updating netdata.

**Comment by vikas5914** [comment]
@mac-linux-free  Please don't create new issues. This issue will be re-open if it's not fixed. 

Can you provide the logs again?
