### ISSUE TITLE
the "http2_max_field_size" directive is obsolete

### ISSUE THREAD

**Issue by exandeer** [WordOps/WordOps#448]
Hello,

I found this on nginx error.log:

`2022/07/29 08:50:58 [warn] 48527#48527: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/conf.d/tweaks.conf:4`
`2022/07/29 08:50:58 [warn] 48527#48527: the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/conf.d/tweaks.conf:5`

Regards

System Information

- [x] `lsb_release -a`
- [x] `wo info`
- [x] `nginx -V`
- [x] `wo -v`
- [x] `wp cli info --allow-root`
[mysystem.txt](https://github.com/WordOps/WordOps/files/9217368/mysystem.txt)

**Comment by VirtuBox** [comment]
Hello @exandeer, 
this issue has already been fixed but I haven't published a new release to apply it yet.
Regards,
