### ISSUE TITLE
Ability to logout of the web dashboard?

### ISSUE THREAD

**Issue by Nantris** [WordOps/WordOps#449]
Am I overlooking it? Right now my only option seems to be closing/re-opening the browser. 

This might be a viable solution: https://stackoverflow.com/a/19258791

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Nantris** [comment]
Not stale.

**Comment by Nantris** [comment]
As a workaround, I suggest only accessing the web dashboard from a temporary browser session, such as a Guest Mode, Incognito Mode, or Private Mode. The auth will expire when the browser is closed.
