### ISSUE TITLE
Error Fatal Detected.

### ISSUE THREAD

**Issue by Gitteleco** [WordOps/WordOps#451]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

Sorry but I'm a small beginer in the use of the WordOps. Please during the instalation the SSL Lest encrypt show this mensagem. 

STDERR:
fatal: detected dubious ownership in repository at '/var/www/institutopacifici.com/conf/nginx'
To add an exception for this directory, call:

        git config --global --add safe.directory /var/www/institutopacifici.com/conf/nginx

I saw and searching on the internet this link about this issue.   

LINK  https://exerror.com/fatal-detected-dubious-ownership-in-repository/ 

I need one help   

Thank all colaborators.

**Comment by vikas5914** [comment]
@Gitteleco Just run this command and then try again.

` git config --global --add safe.directory /var/www/institutopacifici.com/conf/nginx`
