### ISSUE TITLE
After Update 3.15 WO is dead

### ISSUE THREAD

**Issue by mac-linux-free** [WordOps/WordOps#453]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ Debian GNU/Linux 10 (buster)] `lsb_release -a`
- [ not working ] `wo info`
- [ nginx/1.22.0 (WordOps Nginx-wo) ] `nginx -V`
- [ not working ] `wo -v`
- [ 7.2.34-32+0~20220627.74+debian10~1.gbpc7fa3c ] `wp cli info --allow-root`
- [ https://transfer.vtbox.net/inH4Dg/wordops.txt ] `curl -sL git.io/fjAp3 | sudo -E bash -`

Welcome to WordOps install/update script v3.15.0

Installing wo dependencies	[OK]
Installing WordOps	[OK]
Running post-install steps	[OK]
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.7/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.7/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.7/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.7/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.7/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.7/site-packages/wo/core/variables.py", line 10, in <module>
    from distro import distro, linux_distribution
ImportError: cannot import name 'distro' from 'distro' (/opt/wo/lib/python3.7/site-packages/distro.py)
WordOps (wo) upgrade to v3.15.0 was succesfull!
Changelog is available on https://github.com/WordOps/WordOps/releases/tag/v3.15.0

To upgrade WordOps web stacks, you can use the command:
wo stack upgrade

To update all other packages, you can use the command:
wo maintenance

WordOps Documentation : https://docs.wordops.net
WordOps Community Forum : https://community.wordops.net
WordOps Community Chat : https://chat.wordops.net

Give WordOps a GitHub star : https://github.com/WordOps/WordOps/

**Comment by mac-linux-free** [comment]
please help ... how can i roll back to the old version?

**Comment by janiosarmento** [comment]
@VirtuBox is already aware of the issue.

https://community.wordops.net/d/1522-error-upgrading-wo-to-315

**Comment by mac-linux-free** [comment]
thank you

**Comment by janiosarmento** [comment]
Not sure if you are following the thread I linked above, @mac-linux-free , but the following fixed my server:

```
source /opt/wo/bin/activate
pip install -U distro
deactivate
```

**Comment by mac-linux-free** [comment]
worked.
