### ISSUE TITLE
Use API for the getting the Cloudflare IP

### ISSUE THREAD

**Issue by vikas5914** [WordOps/WordOps#455]
Current WordOps use `https://www.cloudflare.com/ips-v4` for getting the Cloudflare IP. It works fine for the majority time. 

However, recently I have seen an issue with this in the Alibaba cloud. The URL returns the HTML page of Cloudflare checking the browser, breaking the Nginx. 

![image](https://user-images.githubusercontent.com/7912297/189450724-f0194270-4c40-47ac-9f03-4d45202c03ce.png)

Solution: Use the Offical API for getting the IP: https://api.cloudflare.com/client/v4/ips

**Comment by VirtuBox** [comment]
Hello @vikas5914,
thanks for your report. I'm going to look at this.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.
