### ISSUE TITLE
MariaDB not listening on port 3306 with ipv4 while using both ipv4 and ipv6

### ISSUE THREAD

**Issue by yogeshbeniwal** [WordOps/WordOps#456]
While using both ipv4 and ipv6 configuration on server, MariaDB is only listening on ipv6 localhost. Netstat output below

```
tcp6       0      0 ::1:3306                :::*                    LISTEN      33686/mariadbd
```

This has started happening or at least identified after upgrade to v3.15.1.

**Comment by VirtuBox** [comment]
Hello @yogeshbeniwal, 
can you try to run `wo stack upgrade --mariadb` ?

**Comment by yogeshbeniwal** [comment]
@VirtuBox Have tried upgrading already. As per JIRA reference above, this issue is resolved in v10.6. Mariadb version is still 10.5, because of https://github.com/WordOps/WordOps/pull/452/commits/33321de2300f916898a09bc4108d817437913ca0

**Comment by VirtuBox** [comment]
MariaDB version bumped to 10.6 in the latest WordOps release. You can upgrade MariaDB with `wo stack migrate --mariadb`

**Comment by yogeshbeniwal** [comment]
Thank you @VirtuBox. It worked, ideally this should happen automatically when running `wo stack upgrade --mariadb`
