### ISSUE TITLE
Hanging on upgrading netdata

### ISSUE THREAD

**Issue by mac-linux-free** [WordOps/WordOps#457]
sadly not...it still hangs on updating netdata.

_Originally posted by @mac-linux-free in https://github.com/WordOps/WordOps/issues/447#issuecomment-1242711126_

**Comment by VirtuBox** [comment]
Hello @mac-linux-free,
can you try the following command : 
```shell
wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --no-updates --stable-channel --disable-telemetry --reinstall-clean
```

**Comment by TheD1ceMan** [comment]
Had the same issue too. Running that snippet does upgrade netdata but answering a load of prompts is required (do you want to remove the systemd file, do you want to remove the user etc).

Once it's manually updated running wo stack upgrade works fine.

**Comment by VirtuBox** [comment]
Hello,
after investigating on this issue, the proper command is `wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --dont-wait --no-updates --stable-channel --reinstall-even-if-unsafe`. 
I added it to WordOps upgrade process and WordOps will automatically apply it if netdata service isn't running after the usual upgrade command.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
