### ISSUE TITLE
ImportError: cannot import name 'distro' from 'distro' (/opt/wo/lib/python3.8/site-packages/distro.py)

### ISSUE THREAD

**Issue by SametKUM** [WordOps/WordOps#458]
System Information

- [❯ lsb_release -a
LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
] `lsb_release -a`
- [❯ wo info
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.8/site-packages/wo/core/variables.py", line 10, in <module>
    from distro import distro, linux_distribution
ImportError: cannot import name 'distro' from 'distro' (/opt/wo/lib/python3.8/site-packages/distro.py) ] `wo info`
- [❯ nginx -V
nginx version: nginx/1.22.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-i448tB/nginx-1.22.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/nginx-echo --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/memc-nginx-module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/HttpRedisModule --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/nginx-module-vts --add-module=/build/nginx-i448tB/nginx-1.22.0/debian/modules/ngx_brotli ] `nginx -V`
- [❯ wo -v
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/main.py", line 93, in main
    with app:
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 1501, in __enter__
    self.setup()
  File "/opt/wo/lib/python3.8/site-packages/cement/core/foundation.py", line 835, in setup
    __import__(self._meta.bootstrap, globals(), locals(), [], 0)
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/bootstrap.py", line 7, in <module>
    from wo.cli.controllers.base import WOBaseController
  File "/opt/wo/lib/python3.8/site-packages/wo/cli/controllers/base.py", line 5, in <module>
    from wo.core.variables import WOVar
  File "/opt/wo/lib/python3.8/site-packages/wo/core/variables.py", line 10, in <module>
    from distro import distro, linux_distribution
ImportError: cannot import name 'distro' from 'distro' (/opt/wo/lib/python3.8/site-packages/distro.py)
 ] `wo -v`
- [OS:     Linux 5.15.0-1016-gcp #21~20.04.1-Ubuntu SMP Fri Aug 5 12:53:07 UTC 2022 x86_64
Shell:  /usr/bin/zsh
PHP binary:     /usr/bin/php7.4
PHP version:    7.4.30
php.ini used:   /etc/php/7.4/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.6.0
 ] `wp cli info --allow-root`
- [❯ curl -sL git.io/fjAp3 | sudo -E bash -

Here the link to provide in your github issue : https://transfer.vtbox.net/CzMjhS/wordops.txt
 ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by vikas5914** [comment]
This was supposed to fix in yesterday's Hotfix. 

Can you try following: https://github.com/WordOps/WordOps/issues/453#issuecomment-1242431690

**Comment by SametKUM** [comment]
> This was supposed to fix in yesterday's Hotfix.
> 
> Can you try following: [#453 (comment)](https://github.com/WordOps/WordOps/issues/453#issuecomment-1242431690)

Thanks for reply. Problem solved.
