### ISSUE TITLE
wp cli throwing errors

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [WordOps/WordOps#466]
For some reason wp cli is running on PHP 8.1, even though the site I am using it on, has PHP 7.4.x assigned to it. 
PHP 8.x is causing wpcli to abort any operations due to fatal errors. 
How can I set wp cli to use php 7.4.x instead? Like the site it is being used on?
Is this a bug?

- [ ] `wp cli info --allow-root`
- [ ] OS:	Linux 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php8.1
PHP version:	8.1.11
php.ini used:	/etc/php/8.1/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.6.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/www/erlebniskochen.de/htdocs
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.6.0

**Comment by s-a-s-k-i-a** [comment]
Fixed this by using following command  in my shell:
`sudo update-alternatives --set php /usr/bin/php7.4`

**Comment by VirtuBox** [comment]
Hello @s-a-s-k-i-a,
wp-cli 2.7.0 was released today, so it should fix issues with PHP 8.1.
