### ISSUE TITLE
Feature Request: ERPNext installation

### ISSUE THREAD

**Issue by jeremiahg7** [WordOps/WordOps#474]
Not sure if this is even possible, but it would be amazing if we could install ERPNext with a Wordpress installation as a subdomain (ie erpnext.domain.com).  I'd like for both installations to share the same database with the same credentials.  It would be even better if they came with SSO so you could login to either one with the same account.

I'd be willing to pay for this work as well, please let me know if this is something that interests you.

---------------------------

This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by meaziz** [comment]
why would you need that..
ERPNext have it's own managment tool Bench and it's stack and requirement is totally different and much more complex..

Better. yet Frappe offers there own Cloud offering which makes site managment even easier .
