### ISSUE TITLE
Why allow entirety of /var/www/ in open_basedir?

### ISSUE THREAD

**Issue by Nantris** [WordOps/WordOps#476]
Wouldn't it be possible and better to limit it to the PHP `open_basedir` value to the `htdocs` folder for each respective site? Or am I overthinking this?

**Comment by VirtuBox** [comment]
Hello @Slapbox, it would require to rebuild the entire virtualhost system with a dedicated php-fpm pool for each site. This is a planned feature, but without any ETA because I don't know how much time it will require to implement this in WordOps.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Slapbox** [comment]
Not stale.

**Comment by Nantris** [comment]
Not stale.

**Comment by Nantris** [comment]
Not stale.
