### ISSUE TITLE
Recommended way to configure MariaDb?

### ISSUE THREAD

**Issue by Slapbox** [WordOps/WordOps#479]
After upgrading WordOps our MariaDb instance is killed my OOMKiller after a few days. Changes to `my.cnf` no longer seem to have any effect on the applied configuration - so I was wondering how we're supposed to configure values like `key_buffer_size`, etc.

Writing to `/etc/mysql/conf.d/my.cnf`, the changes are ignored

Is the recommended method to create a file in `/etc/mysql/mariadb.conf.d`, or what exactly?

**Comment by Slapbox** [comment]
It seems like _only_ `/etc/my.cnf` is obeyed. I tried editing everywhere else and changes never took effect.

**Comment by VirtuBox** [comment]
Hello @Slapbox,
on MariaDB 10.4 and newer, MariaDB tuning is set in `/etc/mysql/mariadb.conf.d/50-server.cnf`.
You can safely edit this file by creating an empty file `/etc/mysql/mariadb.conf.d/50-server.cnf.custom`. This will prevent the file to be overwritten by WordOps.

**Comment by Slapbox** [comment]
Thanks for your reply @VirtuBox! Is it safe to just use what we settled on yesterday with `/etc/mysql/mariadb.conf.d/99-our.cnf`? Or does that risk being removed?

**Comment by VirtuBox** [comment]
Hello @Slapbox, WordOps will not remove your custom configuration file `/etc/mysql/mariadb.conf.d/99-our.cnf`.
Regards,
