### ISSUE TITLE
[Trivial] How to remove date header?

### ISSUE THREAD

**Issue by Slapbox** [WordOps/WordOps#480]
OWASP ZAP flags this at a low of informational level, I forget which.

By default `date` used to not be exposed, and we had to explicitly set `more_set_headers 'Access-Control-Expose-Headers: date';` to expose it. Now though, `date` header is always sent and even `more_clear_headers "date"` no longer removes it, but I `grep`ed the `/etc/nginx` directory and found nothing setting the `date` header, so I'm a bit confused.

It's not big deal, but I don't like not understanding why things happen on machines I'm responsible for. Any ideas?

**Comment by yogeshbeniwal** [comment]
@Slapbox But what is the risk here, date header shows current time in GMT

![Screenshot](https://github.com/WordOps/WordOps/assets/7325107/e80b8688-c640-49f1-87c2-7096f17f154c)

**Comment by Slapbox** [comment]
Thanks for the reply @yogeshbeniwal. Unfortunately I don't have that information available anymore.
