### ISSUE TITLE
Add PHP 8.2 to WO

### ISSUE THREAD

**Issue by janiosarmento** [WordOps/WordOps#482]
I'm working on adding PHP 8.2 to WO. I'll submit a PR linked to this issue.

**Comment by VirtuBox** [comment]
Hello @janiosarmento,
I have merged your PR in the updating-configuration branch to work on it this week.
Thanks again for your awesome contribution to WordOps project :blush:

**Comment by VirtuBox** [comment]
Thanks for your pull request and your contribution @janiosarmento
