### ISSUE TITLE
⛔️ Critical Bug: WordOps creates wrong Nginx-config for Wildcard-sites when using Cloudflare-Api, causing Wildcard to be unusable ‼️

### ISSUE THREAD

**Issue by Elihey** [WordOps/WordOps#485]
When creating a wildcard site by using Cloudflare-Api the server config files in the Nginx-folder sites-enabled get messed up:
### The wrong config files are missing the * for the wildcard-domain

```
server {
    server_name site.com www.site.com;
```

but they should use the * instead of the www:

```
server {

  server_name site.com *.site.com;

```

**Comment by VirtuBox** [comment]
Hello @Elihey,
It is not a bug, but the current WordOps design. Issuing a Wildcard SSL Certificates doesn't mean you want a wildcard site. It give the ability to use the same SSL certificate on several subdomain sites.
So the easiest in your case is to use `wo site edit site.tld` and to manually add the `*.site.tld` in your server_name.
