### ISSUE TITLE
WO Update v3.9.4.2 to 3.9.4.3

### ISSUE THREAD

**Issue by LotusJeff** [WordOps/WordOps#49]
During the update after the status of Installing WordOps, the following message was presented:

`cp: cannot create regular file '/etc/nginx/common/locations-php72.conf': No such file or directory`

Scenario:  Just installed wo based on instructions on the home page.  immediately ran the wo update command. At this time, I have NOT created any sites so none of the packages have been installed.

I tried running the command again and it restarted the update.  There needs to be a version check. If there is a newer version, run the update. If not, provide a message to the user that you are on the current version.

**Comment by VirtuBox** [comment]
> During the update after the status of Installing WordOps, the following message was presented:
> 
> `cp: cannot create regular file '/etc/nginx/common/locations-php72.conf': No such file or directory`
> 
> Scenario: Just installed wo based on instructions on the home page. immediately ran the wo update command. At this time, I have NOT created any sites so none of the packages have been installed.
> 
> I tried running the command again and it restarted the update. There needs to be a version check. If there is a newer version, run the update. If not, provide a message to the user that you are on the current version.

Hello @LotusJeff, 
wo version check will be enabled as soon as we publish the stable release. But currently, it's easier for us to be able to self-update WordOps even with the same version number.

**Comment by LotusJeff** [comment]
Makes sense
