### ISSUE TITLE
NGINX configuration check failed.

### ISSUE THREAD

**Issue by tringuyen1412** [WordOps/WordOps#492]
Im having trouble in setting VPS
Im setting VPS in order to move my website from old hosting to a VPS
in the Wordpress setting stage, i have a error like this:
NGINX configuration check failed.
Could you help me to complete set up VPS for me
<img width="621" alt="Nginx fail" src="https://user-images.githubusercontent.com/121827329/210273761-d6f85df4-4b9f-432c-b7d4-0b6c3ef0f393.png">

**Comment by yogeshbeniwal** [comment]
You already have nginx installed on VPS, uninstall it before start using WordOps.
