### ISSUE TITLE
404 and 403 errors on clean install - Permissions on /var/www/domain/htdocs

### ISSUE THREAD

**Issue by LotusJeff** [WordOps/WordOps#50]
Clean install of 3.9.4.3
Server: Ubuntu 18.04

Site Command Used:
wo site create domain.com --wpredis --php73 --user=user --pass=password --email=email_address

All /var/www/domain/htdocs directory and sub-directories were set to 750 and files to 640
Nginx needs directories set to 755 and files to 644

Ran the following:
find /var/www/domain.com/htdocs -type d -exec chmod 755 {} \;
find /var/www/domain.com/htdocs -type f -exec chmod 644 {} \;

Everything worked.  I am assuming I will have to do the same for /html and /22222, but I have not gotten that far in my testing.

**Comment by VirtuBox** [comment]
Hello @LotusJeff,

I haven't be able to reproduce this issue on a fresh Ubuntu 18.04 install.
Permissions are 755 for directories, and 644 for files :

```bash
root@wo:/var/www# lh
drwxr-xr-x 755 ./22222
drwxr-x--- 750 ./html
drwxr-xr-x 755 ./site.tld
drwxr-xr-x 755 ./othersite.tld
```

**Comment by LotusJeff** [comment]
I reinstalled and ended up 750/640.  I went through my notes when I hardened the server. I followed the Lynis and CIS recommended guidelines, which recommends changing umask setting in /etc/profile from 022 to 027. This explains the permission differences.  I will retest later tonight.

**Comment by VirtuBox** [comment]
If you set umask to 027, you will have directories with 750 permissions and files with 640.
