### ISSUE TITLE
Consider replacing Nginx with Caddy

### ISSUE THREAD

**Issue by hj-collab** [WordOps/WordOps#502]
Hi.

We have recently migrated all ours servers to Caddy from Nginx after going through a extensive testing of year.

It's as performant as Nginx. Comparing latest version of both but written in memory safer language (Go), have the best native implementation to handle TLS cert operations, saner defaults compared to Nginx outdated default configs (we had to tweak nothing to be honest), http/3 support out of box, config syntax is more readable and their team is helpful.

**Comment by tersor** [comment]
@hj-collab Interresting.

How du you manage cache?

**Comment by sebastienvercammen** [comment]
> They are not compressed on every request like Nginx.

nginx supports [static gzip cache](https://nginx.org/en/docs/http/ngx_http_gzip_static_module.html).

> The ngx_http_gzip_static_module module allows sending precompressed files with the “.gz” filename extension instead of regular files.

It would be cool if WordOps included this by default, maybe even with a wp-cli method or a WP plugin to pregenerate the gzip files on changes.
