### ISSUE TITLE
MySQL & Database Replication Support

### ISSUE THREAD

**Issue by hj-collab** [WordOps/WordOps#503]
Hi,

Another feature request. I found MySQL more friendly for replication technologies for high availability compared to MariaDB. Especially with Auto position for GTID replication and external mysql shell module supporting python and javascript based scripts for replication. 

Are there any plans for high availability/cluster support? Thank you!

**Comment by VirtuBox** [comment]
Hello @hj-collab,
WordOps already allow to use a remote database so it's fully compatible with a MySQL/MariaDB cluster but we are not going to manage MySQL cluster deployment with WordOps.
