### ISSUE TITLE
 2006 MySQL server has gone away 

### ISSUE THREAD

**Issue by wangjiahong** [WordOps/WordOps#506]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information
<img width="852" alt="image" src="https://user-images.githubusercontent.com/14320144/218122857-67cf4127-8394-4cd2-8063-8c660e72c5bf.png">

- [ ] `lsb_release -a`
- [ ] `wo info`
- [ ] `nginx -V`
- [ ] `wo -v`
- [ ] `wp cli info --allow-root`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by VirtuBox** [comment]
Hello @wangjiahong,

The MySQL server has gone away (error 2006) has two main causes and solutions:

- Server timed out and closed the connection. To fix, check that wait_timeout mysql variable in `/etc/mysql/mariadb.conf.d/50-server.cnf` configuration file is large enough, eg wait_timeout = 28800
- Server dropped an incorrect or too large packet. If mysqld gets a packet that is too large or incorrect, it assumes that something has gone wrong with the client and closes the connection. To fix, you can increase the maximal packet size limit max_allowed_packet in `/etc/mysql/mariadb.conf.d/50-server.cnf` file, eg. set max_allowed_packet = 128M, then restart MariaDB.
