### ISSUE TITLE
PHP-FPM cache issue when document root is a symlink (nginx)

### ISSUE THREAD

**Issue by hakimzulkufli** [WordOps/WordOps#508]
Hello. The current nginx config does not play nice with symlink document roots. Whenever the code is updated, nginx still uses the old code as they're already cached in PHP's Opcache. A way to go around this is by reloading PHP-FPM but that could lead to connection drops.

```
# Create a website
wo site create example.com --php74

# symlink htdocs to another folder
ln -s ~/mywebsite /var/www/example.com/htdocs
```

Whenever the code in ~/mywebsite is updated, nginx will still serve the old code from the cache.

Inside `/etc/nginx/common/php74.conf`, I find that the location block does not include the configuration required to make it work properly with symlinked directories.

The following lines (the bottom 2) need to be added:

```
location ~ \.php$ {
  try_files $uri =404;
  include fastcgi_params;
  fastcgi_pass php74;
  fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name; # This
  fastcgi_param DOCUMENT_ROOT $realpath_root; # And this
}
```

For reference, why these two lines are required is explained here: https://serverfault.com/a/848526

My question is, how do I make sure this config stays intact on every update? I know this is probably not the desired behaviour for most use cases so I wanted to extend the location config in the site's config if possible. I tried adding another `location ~ \.php$` block in `/etc/nginx/sites-enabled/example.com.conf` to extend the config but it did not work.

If anyone could help me with this, it would be great.

**Comment by VirtuBox** [comment]
Hello @hakimzulkufli, 
You can protect your custom configuration by creating a file `/etc/nginx/common/php74.conf.custom`. 
This way WordOps will not overwrite it during stack upgrade. 

But be careful with symlinked directories, it could easily become a security breach depending where is the symlinked directory and permissions.
