### ISSUE TITLE
FPM Admin php7.3 redirectoed to 7.2 file names

### ISSUE THREAD

**Issue by LotusJeff** [WordOps/WordOps#51]
Clean install of 3.9.4.3
Server: Ubuntu 18.04

Site Command Used:
wo site create domain.com --wpredis --php73 --user=user --pass=password --email=email_address

Within the admin section domain.com:22222 all the end pages are getting a 502 Bad Gateway error.

The pages are directed to the php7.2 files versus the 7.3 equivalents.

**Comment by VirtuBox** [comment]
Hello @LotusJeff,

WordOps backend on port 22222 is only running on PHP 7.2 (not related to the domain used to access it) , so if you only setup a site running with PHP 7.3, backend will not work properly until you install php7.2. The easiest to install WO's base stacks is to run : 

```bash
wo stack install
```

**Comment by LotusJeff** [comment]
So from a user perspective, the system should install both 7.2 and 7.3. Both are required for the basic functionality to run. 

If the install is not going to install both, then the documentation needs to be updated indicating if you choose to run 7.3, you will also need to install 7.2 for the admin utilities to accessible.

**Comment by VirtuBox** [comment]
You are right. Feel free to use the button "edit" available on the documentation and to open a pull-request with changes you have made. All contributions are welcome.

**Comment by VirtuBox** [comment]
Issue has been fixed with PR https://github.com/WordOps/WordOps/pull/52
