### ISSUE TITLE
nginx location rules block sitemap.xml.gz

### ISSUE THREAD

**Issue by leekung** [WordOps/WordOps#513]
the file common/locations-wo.conf blocks .gz file extension

```shell
# Deny backup extensions & log files and return 403 forbidden
location ~* "\.(old|orig|original|php#|php~|php_bak|save|swo|aspx?|tpl|sh|bash|bak?|cfg|cgi|dll|exe|git|hg|ini|jsp|log|mdb|out|sql|svn|swp|tar|rdf|gz|zip|bz2|7z|pem|asc|conf|dump)$" {
    deny all;
}
```
but the file sitemap.xml.gz is being use for sitemap index

how to exclude this file from being block?

**Comment by juanpvh** [comment]
you can remove the gz from the location field.  I would advise you to use the default sitemap.xml instead of sitemap.xml.gz
