### ISSUE TITLE
Enhancement: Add WordOps version to Dashboard

### ISSUE THREAD

**Issue by GRL570810** [WordOps/WordOps#514]
Whilst the version of WordOps is reported using the wo-v command in an SSH session it would be good to have it reported on the Dashboard as well.

**Comment by juanpvh** [comment]
you can use the wo -v command to check the version of wordops.

**Comment by GRL570810** [comment]
> you can use the wo -v command to check the version of wordops.

Thanks for the heads up on that. It would still be nice to have it reported on the Dashboard though, so I'll change the title & content of the request to just ask for that.

**Comment by VirtuBox** [comment]
> Whilst the version of WordOps is reported using the wo-v command in an SSH session it would be good to have it reported on the Dashboard as well.

That's a good idea. I will have to check how to do it without having to run manually a command, but that's a great idea.

**Comment by GRL570810** [comment]
As a further thought: it would be nice to have a 'check for update' function there as well. I don't think it would need to go as far as launching the update, just advise if a newer version is available.

**Comment by GRL570810** [comment]
@github-actions. Bump. Please don't close this issue.

**Comment by GRL570810** [comment]
@github-actions. Bump. Please don't close this issue.
