### ISSUE TITLE
Enhancement: expose the --locale option of wp core download as an option to wo site create

### ISSUE THREAD

**Issue by GRL570810** [WordOps/WordOps#515]
I wish my sites to be created with one of two locales, neither of which are en_US (I need en_AU or en_NZ). I imagine I am not unique in this requirement; I am sure that there are plenty of folks out there who create sites in a number of alternate languages. As things stand its necessary to edit the config.yml file before creating each new site (and in my case I can't seem to find the right location for the file anyway, so instead I have resorted to editing site_functions.py to add --locale to the call to wp core download). 
Whilst editing that file it occurred to me that a much better solution would be to enhance wo site create to accept a '--wplocale' or similarly named option that allowed specification of the desired locale and pass that through to the wp core download call. Even better still would be to add a locale setting to the [wordpress] section in wo.conf that would be read as the default locale and only change if the command option was provided.

**Comment by juanpvh** [comment]
you can make this change in wordpress itself.  Or use wp-cli to install wordpress with desired language.

**Comment by tersor** [comment]
@GRL570810 You can automate this in a post-install step, as suggested [in the docs](https://docs.wordops.net/how-to/post-install-wp/).

**Comment by GRL570810** [comment]
Thanks for the comments guys about doing it either in the site or in a script post-install. I am in fact already doing this with a script that I provide the locale I want to swap to as a parameter.
However, my point is that I don't believe I should **have** to be doing it that way, which is rather a round-the-houses workaround. It would be a much cleaner approach to allow site create to set the desired language correctly in the first place, rather than enforce en_US. After all, it exposes other things like the WP table prefix already. The locale seems to me to be at least as important as that, if not more so (does anyone even change the table prefix, it's moot if it makes any difference to security?). There have to be more sites out there **not** running en_US that those that do so.
I believe this should still stand as a useful enhancement to the product, which is after all intended to make site management easier for non-gurus of WP, nginx, MySQL etc...

**Comment by GRL570810** [comment]
> @GRL570810 You can automate this in a post-install step, as suggested [in the docs](https://docs.wordops.net/how-to/post-install-wp/).

I have not managed to get the config.yml edit approach described in [https://docs.wordops.net/how-to/wp-language/](https://docs.wordops.net/how-to/wp-language/) work on my system. In any event that only helps if you are always installing the same locale, if you are building sites in a number of possible languages (which I am sure would be common in Europe) then you'd often have to re-edit the file before each site create.

**Comment by GRL570810** [comment]
@github-actions Bump. Please don't close this.

**Comment by GRL570810** [comment]
@github-actions. Bump. Please don't close this issue.
