### ISSUE TITLE
Error with Wordops WordOps v3.16.3

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#516]
Hello,

I encounter errors with latest Wordops, and it would be great if someone can help:

Errors:

1# Mysql will suddently be uninstalled, fortunately, the database is still there, and site can be roll back by switch php version: wo site update --php, and mysql will install back during the process.
2# No matter Nginx Fastcgi Cache or Redis cache, both will show bypass.
3# For now, it will show 502 Bad Gateway at https://mysite.com:22222/netdata/

-------------------

System Information

- [ ] `lsb_release -a`
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

- [ ] `wo info`
wo info

NGINX (1.22.1 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 

PHP (7.2.34-38):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.33-10):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

PHP (7.4.33):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

PHP (8.0.28):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php80-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9180

PHP (8.1.18):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php81-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9181

PHP (8.2.5):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php82-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9182

MySQL (10.6.12-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             4
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] `nginx -V`
nginx version: nginx/1.22.1 (WordOps Nginx-wo)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-QEo1nc/nginx-1.22.1=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/headers-more-nginx-module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/nginx-auth-pam --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/nginx-cache-purge --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/nginx-echo --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/nginx-upstream-fair --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/memc-nginx-module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/srcache-nginx-module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/HttpRedisModule --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/redis2-nginx-module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/ngx_devel_kit --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/set-misc-nginx-module --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/nginx-module-vts --add-module=/build/nginx-QEo1nc/nginx-1.22.1/debian/modules/ngx_brotli

- [ ] `wo -v`

 wo -v
WordOps v3.16.3
Copyright (c) 2023 WordOps.

- [ ] `wp cli info --allow-root`

wp cli info --allow-root
OS:     Linux 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.2
PHP version:    8.2.5
php.ini used:   /etc/php/8.2/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.7.1

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

Here the link to provide in your github issue : https://transfer.vtbox.net/24mDI6/wordops.txt

---------------------------------

**Comment by VirtuBox** [comment]
Hello @alexlii1971,
have you run `wo stack migrate --mariadb` ?

**Comment by alexlii1971** [comment]
Yes, I did.

Actually, I tried several times in following way by following up the document at https://docs.wordops.net/commands/stack/#stack-upgrade

wo stack upgrade --all
Wo stack upgrade --MySQL

Then, run wo stack migrate --mariadb

Thanks, and please let me know if you need more details.

**Comment by VirtuBox** [comment]
Hello @alexlii1971, 
I will update the documentation because you should not run `wo stack migrate --mariadb` if you are already using MariaDB 10.6, and it's look like there is a bug because WordOps should tell you you are already running the latest supported MariaDB release. I will take a look on this. Thanks for your report.

**Comment by alexlii1971** [comment]
In this case, netdata will show like this:

https://prnt.sc/C03aXPSW6DRv

Click "see all",  show: 502 Bad Gateway
https://prnt.sc/XAzWYHHj2Qj4

**Comment by alexlii1971** [comment]
Hello,  I am quite new with phpRedisAdmin, there is only one main site of multisite of my WordPress, but there is a list of phpRedisAdmin, please check the screenshot:  https://prnt.sc/tasN5PlAXvQf 

 Is this expected? if not, how should I fix it, please?  

Thanks

**Comment by alexlii1971** [comment]
Hello,

https://github.com/WordOps/WordOps/issues/516#issuecomment-1527493495

Here is what I did  and tried to repair the database at https://community.wordops.net/d/1877-msql-will-shutdown-if-lots-of-product-page-are-accessed-

but it does not work, any suggestion to fix the issue please?

Thanks

**Comment by alexlii1971** [comment]
Hello @VirtuBox 

I just noted that Mysql will get down if concurrent-connections reach to around 20.

and it will show as `Error Establishing a Database Connection`

Usually, it should be show as time out.

Really expect a method to fix the issue.

Thanks

**Comment by alexlii1971** [comment]
Hello @VirtuBox 

I tried a lot, and even created a new site and imported the database, but the issue is still there, sometimes it will show as below:

`service mysql status
● mariadb.service - MariaDB 10.6.14 database server
     Loaded: loaded (/lib/systemd/system/mariadb.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/mariadb.service.d
             └─limits.conf, migrated-from-my.cnf-settings.conf
     Active: active (running) since Mon 2023-07-17 03:33:50 UTC; 1 day 4h ago
       Docs: man:mariadbd(8)
             https://mariadb.com/kb/en/library/systemd/
    Process: 33022 ExecStartPre=/usr/bin/install -m 755 -o mysql -g root -d /var/run/mysqld (code=exited, status=0/SUCCESS)
    Process: 33023 ExecStartPre=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
    Process: 33025 ExecStartPre=/bin/sh -c [ ! -e /usr/bin/galera_recovery ] && VAR= ||   VAR=`cd /usr/bin/..; /usr/bin/galera_recovery`; [ $? -eq 0 ]   && systemctl set-environment _>
    Process: 33200 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
    Process: 33202 ExecStartPost=/etc/mysql/debian-start (code=exited, status=0/SUCCESS)
   Main PID: 33184 (mariadbd)
     Status: "Taking your SQL requests now..."
      Tasks: 20 (limit: 9477)
     Memory: 1.8G
        CPU: 3h 23min 17.178s
     CGroup: /system.slice/mariadb.service
             └─33184 /usr/sbin/mariadbd

Jul 17 03:33:50 SF-mysite-2 mariadbd[33184]: 2023-07-17  3:33:50 0 [Note] Server socket created on IP: '127.0.0.1'.
Jul 17 03:33:50 SF-mysite-2 mariadbd[33184]: 2023-07-17  3:33:50 0 [Note] /usr/sbin/mariadbd: ready for connections.
Jul 17 03:33:50 SF-mysite-2 mariadbd[33184]: Version: '10.6.14-MariaDB-1:10.6.14+maria~ubu2204-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
Jul 17 03:33:50 SF-mysite-2 systemd[1]: Started MariaDB 10.6.14 database server.
Jul 17 03:33:50 SF-mysite-2 mariadbd[33184]: 2023-07-17  3:33:50 0 [Note] InnoDB: Buffer pool(s) load completed at 230717  3:33:50
Jul 17 06:38:40 SF-mysite-2 mariadbd[33184]: 2023-07-17  6:38:40 2900 [Warning] Aborted connection 2900 to db: 'mysite_com_AtxdyVmk' user: 'mysitecomqBPY' host: 'localhost' (Got an>
Jul 17 07:21:04 SF-mysite-2 mariadbd[33184]: 2023-07-17  7:21:04 3475 [Warning] Aborted connection 3475 to db: 'mysite_com_AtxdyVmk' user: 'mysitecomqBPY' host: 'localhost' (Got an>
Jul 17 10:04:23 SF-mysite-2 mariadbd[33184]: 2023-07-17 10:04:23 5744 [Warning] Aborted connection 5744 to db: 'mysite_com_AtxdyVmk' user: 'mysitecomqBPY' host: 'localhost' (Got an>
Jul 17 10:19:23 SF-mysite-2 mariadbd[33184]: 2023-07-17 10:19:23 6112 [Warning] Aborted connection 6112 to db: 'mysite_com_AtxdyVmk' user: 'mysitecomqBPY' host: 'localhost' (Got an>
Jul 17 22:40:18 SF-mysite-2 mariadbd[33184]: 2023-07-17 22:40:18 16593 [Warning] Access denied for user 'username_here'@'localhost' (using password: YES)`


Anyway to fix the issue? really expect your guiding.

Thanks

**Comment by alexlii1971** [comment]
max_allowed_packet	= 512M

It seems fixed.
