### ISSUE TITLE
Feature request: allow dynamic modules --with-compat

### ISSUE THREAD

**Issue by zelik888** [WordOps/WordOps#519]
I want to add maxmind geoip2 via dynamic modules but wordops nginx isn't compiled with --with-compat so I need to completely recompile nginx with all the modules etc. to match what wordops provides. I understand the issues with updates, etc. but would it be bad to allow dynamic modules and perhaps warn users during an update for the need to recompile?

**Comment by Ethical-Cronos** [comment]
Use https://github.com/VirtuBox/nginx-ee it is wordops compatible and allows additional modules @VirtuBox  correct me if i am wrong

**Comment by zelik888** [comment]
I have looked at nginx-ee and it will require a lot of modules to make it match the default wordops setup. Just hoping to have --with-compat added to allow easier extension of features for nginx
