### ISSUE TITLE
Debian 12 Bookworm Support

### ISSUE THREAD

**Issue by J-Prince** [WordOps/WordOps#535]
Hello,

I was wondering if I could install WordOps on Debian 12 or do I need to wait for official support first?

Thank you!

**Comment by vitovt** [comment]
vote here

I've installed wordops by `bash wo --force`
but when try `wo site` see error:
```
  File "/opt/wo/lib/python3.11/site-packages/wo/core/variables.py", line 146, in WOVar
    .format(wo_deb_repo))
            ^^^^^^^^^^^
NameError: name 'wo_deb_repo' is not defined
```

**Comment by vikas5914** [comment]
@vitovt If you check http://download.opensuse.org/repositories/home:/virtubox:/WordOps/, you will see no package for Debian 12. You will have to wait until it's created for Debian 12. Also, it requires some code changes in the WO as well.

**Comment by euhost** [comment]
@vikas5914 
fyi, debian 12 packages were added on July 2nd already. 

would be great to see debian 12 support added. Thanks for your time.

**Comment by VirtuBox** [comment]
Hello, I'm working on it. Debian 12 support should be available soon.
