### ISSUE TITLE
Nginx log

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#546]
Hello,

```
wo -v
WordOps v3.16.3
Copyright (c) 2023 WordOps.


```
When two sites were created on one server, then delete one, and only one site is left on server.
When try `wo site list`, there is only one site.

But, when try `wo log reset`, it will show:

`Resetting MySQL slow_query_log database table
Resetting file /var/log/nginx/22222.error.log
Resetting file /var/log/nginx/**site_one**.com.error.log
Resetting file /var/log/nginx/error.log
Resetting file /var/log/nginx/**site_two**.net.error.log
Resetting file /var/log/nginx/22222.access.log
Resetting file /var/log/nginx/**site_one**.com.access.log
Resetting file /var/log/nginx/**site_two**.net.access.log
Resetting file /var/log/php/8.0/slow.log
Resetting file /var/log/php/8.2/slow.log
Resetting file /var/log/php/7.3/slow.log
Resetting file /var/log/php/7.4/slow.log
Resetting file /var/log/php/8.1/slow.log
Resetting file /var/log/php7.3-fpm.log
Resetting file /var/log/php8.1-fpm.log
Resetting file /var/log/php8.2-fpm.log
Resetting file /var/log/php7.4-fpm.log
Resetting file /var/log/php8.0-fpm.log
Resetting file /var/log/mysql/mariadb-slow.log`

Obviously, there are two site logs.

So, Is there a bug please?

-----------------------

**Comment by juanpvh** [comment]
when you delete a site the log files are not deleted.

**Comment by VirtuBox** [comment]
Hello @alexlii1971 and @juanpvh,
thanks for your reports, i'm going to take a look on this.
