### ISSUE TITLE
Could we have SSL config as a .mustache template?

### ISSUE THREAD

**Issue by JPaulMora** [WordOps/WordOps#549]
https://github.com/WordOps/WordOps/blob/dfe70060eb5cc570aa809f040582cfc0b7a4c252/wo/core/acme.py#L147

Hi, I have a special setup where my server has multiple IPs. Currently every time I create a site I have to manually change the template to add `listen <myip>:443` _or_ I have to change this line on the file every time wordops gets updated.

Thanks in advance.

**Comment by VirtuBox** [comment]
Hello @JPaulMora, 
yes, I will add the ssl.conf as a mustache template.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
