### ISSUE TITLE
Unable to install Certificate

### ISSUE THREAD

**Issue by vibhi19** [WordOps/WordOps#55]
This issue tracker is only for issues related to WordOps.
Please use <https://community.wordops.net> for support questions.

I am trying to install wordpress on subdomain 

I am not using the same server where my main domain is being pointed
i point my subdomain to new server ip and it shows

"Please make sure that your site is pointed to
same server on which you are running Let's Encrypt Client
 to allow it to verify the site automatically."
 

System Information

- [ ] lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

- [ ] wo info
NGINX (1.14.2 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1

PHP (7.2.17-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.4-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

MySQL (10.3.14-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             2
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] nginx -V
nginx version: nginx/1.14.2 (WordOps Nginx-wo)
built with OpenSSL 1.1.0g  2 Nov 2017
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli
- [ ] wo -v
WordOps v3.9.4
- [ ] wp cli info --allow-rootOS:     Linux 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php7.3
PHP version:    7.3.4-1+ubuntu18.04.1+deb.sury.org+3
php.ini used:   /etc/php/7.3/cli/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.1.0

**Comment by vikas5914** [comment]
@vibhi19 Please provide the command that you use for Let's Encrypt.

**Comment by vibhi19** [comment]
Everything seems to work as i use HSTS on cloudflare so i cant visit my site in HTTP i tried using page rules to turnoff ssl but that doesnt help 

wo site create example.com  --wpredis --php73 --letsencrypt

this cmd i used nothing else

**Comment by vikas5914** [comment]
@vibhi19  If your server is behind the Cloudflare (the yellow colour on Cloudflare), Then I don't think the command will work. 

if it's not behind the Cloudflare, please try with the command with subdomain option like this: 

```
wo site create shop.example.com --wpredis --php73 --letsencrypt=subdomain
```

**Comment by vibhi19** [comment]
> @vibhi19 If your server is behind the Cloudflare (the yellow colour on Cloudflare), Then I don't think the command will work.
> 
> if it's not behind the Cloudflare, please try with the command with subdomain option like this:
> 
> ```
> wo site create shop.example.com --wpredis --php73 --letsencrypt=subdomain
> ```

its behind the cloudflare but as of  on now i turned off there proxy

I already installed on the server how i can only install letsencrypt

**Comment by vikas5914** [comment]
if you already created the site, you can run this command: 

```
wo site update shop.example.com  --letsencrypt=subdomain
```

**Comment by vibhi19** [comment]
> if you already created the site, you can run this command:
> 
> ```
> wo site update shop.example.com  --letsencrypt=subdomain
> ```

Worked Thanks for the help 

How i am going to renew the ssl cert?

**Comment by vikas5914** [comment]
WordOps automatically add a cronjob to auto-renew all lets encrypted SSL certificate. 

OR 

you can manually re-run the update command again to do it. 

Note:  If you enable Cloudflare on the site, the renewal process will not work.

**Comment by vibhi19** [comment]
Thank You for the help
