### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by vibhi19** [WordOps/WordOps#56]
I installed wordpress with redis cache Php 7.3. using for selling with woo 

When i enable redis object cache i have seen alot of issue in admin dashboard eg Deactivating Plugin doesn't take effect. it also has browser cache issue too.

**Comment by VirtuBox** [comment]
Hello @vibhi19,
if you have issues with redis-object-cache plugin, you can flush the cache from the plugin settings interface, and then disable it (or remove it). You will still have full-page cache with redis, but not object-cache anymore.

**Comment by vibhi19** [comment]
Hello @VirtuBox 

Thank you for reply but why it object cache creating issue with admin dashboard i would like to get an fix for it

and is there any changes i have to make to use woo com with object cache

**Comment by VirtuBox** [comment]
Hello @vibhi19,

After running few tests on a VM, I haven't be able to reproduce this issue. 
But I have noticed something which is maybe related to your issue, the variable WP_CACHE_KEY_SALT is set twice in the wp-config.php. Try to remove the longer one (WP_CACHE_KEY_SALT should look like `yoursite.tld`).

**Comment by vibhi19** [comment]
> Hello @vibhi19,
> 
> After running few tests on a VM, I haven't be able to reproduce this issue.
> But I have noticed something which is maybe related to your issue, the variable WP_CACHE_KEY_SALT is set twice in the wp-config.php. Try to remove the longer one (WP_CACHE_KEY_SALT should look like `yoursite.tld`).

Thanks i removed that

although there was these issue I used w3total cache and turn of caching for wp admin and used browser caching which update the cache in browser

One thing should i use database cache and object cache both or stick to object cache only

**Comment by VirtuBox** [comment]
We do not use w3tc at all in our configurations, so I'm not able to help with this plugin.
Full-page cache and object-cache should be more than enough.

**Comment by vibhi19** [comment]
> We do not use w3tc at all in our configurations, so I'm not able to help with this plugin.
> Full-page cache and object-cache should be more than enough.

Thanks for the help
