### ISSUE TITLE
How to move back to ee?

### ISSUE THREAD

**Issue by eddr** [WordOps/WordOps#57]
Hi

Any clue how to go back?
I want to go with ee v4, but ee is not recognized anymore and so I can't migrate easily. Any word?

Thanks

**Comment by VirtuBox** [comment]
Hello,

you should be able to reinstall EasyEngine v3 by running the previous installer :

```bash
wget -qO ee https://raw.githubusercontent.com/EasyEngine/easyengine/develop-v3/install && sudo bash ee
```
Then, you will have to copy wo database : 

```bash
sudo cp -f /var/lib/wo/dbase.db /var/lib/ee/ee.db
```
After that, you can try to run ee v4 installer again, but I cannot tell you if that will be enough or not.

**Comment by eddr** [comment]
Thanks VB!
