### ISSUE TITLE
wo site update --phpXx doesn't do anything to vhost config

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [WordOps/WordOps#570]
Hello yall!
I noticed this on all of my wordops Servers: 
When running a site update command to switch php versions, wordops doesn't change anything in the nginx config files regarding pulled php versions for that particular vhost. It just stays the same.
For instance (with live feedback) I am doing this on any server:
1.)
_wo site info subdomain.tld.de_
**terminal feedback:**
Information about subdomain.tld.de (subdomain):

Nginx configuration	 wp basic (enabled) 
PHP Version		 7.4

SSL			 enabled
SSL PROVIDER		 Lets Encrypt
SSL EXPIRY DATE		 39

access_log		 /var/www/subdomain.tld.de/logs/access.log
error_log		 /var/www/subdomain.tld.de/logs/error.log
Webroot			 /var/www/ssubdomain.tld.de

DB_NAME			 subdomain_tld_de_jIbcLMRa
DB_USER			 äldkgjädlksjfälsakdjfäl
DB_PASS			 somepassword

2.) Then I run:
_wo site update subdomain.tld.de --php81_
**terminal feedback:**
Running pre-update checks       [OK]
Backup location : /var/www/subdomain.tld.de/backup/04Sep2023-14-13-51
Backing up database 		[Done]
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Successfully updated site http://subdomain.tld.de

3.) Now I check again running wo site info command and the php version ist still 7.4 whilst it should be 8.1
I also checked directly in the site available nginx config files, and its the same there: php 74 is being referenced instead of wanted 8.1

As mentioned I noticed this behaviour some time ago and am manually modifying the nginx config files since then to be able to upgrade php on my sites.. quite tiresome.

I am always using Ubuntu distros. Mostly Ubuntu 20.04.6

Thanks
Saskia

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
