### ISSUE TITLE
Remove Anemometer Package - Potential Vulnerability

### ISSUE THREAD

**Issue by MichalisDBA** [WordOps/WordOps#575]
Please remove `Anemometer` package from `--utils` flag.

The project is abandoned and has a serious SQL injection vulnerability

https://github.com/box/Anemometer/issues/210

**Comment by VirtuBox** [comment]
Hello @MichalisDBA,

thanks for your report, I will remove it asap.

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
