### ISSUE TITLE
Issuer certificate not found

### ISSUE THREAD

**Issue by tersor** [WordOps/WordOps#58]
I get a nginx warning on a fresh WO install when running `nginx -t`:

```
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/var/www/22222/cert/22222.crt"
```

System information: https://gist.github.com/b3c084ea588dda7d3b62e6ed38408435

Any ideas?

**Comment by VirtuBox** [comment]
Hello,
This is due to the self-signed certificate used to secure WordOps backend and OCSP stapling enabled in Nginx configuration.
I'm working on the command `wo secure` to provide the ability to issue a valid certificate with letsencrypt instead of a self-signed.

**Comment by VirtuBox** [comment]
Issue has been fixed with PR https://github.com/WordOps/WordOps/pull/119
The first ssl certificate issued on the server will be used to secure WordOps backend with a valide certificate
