### ISSUE TITLE
[Suggestion]Redis compatible cache alternative

### ISSUE THREAD

**Issue by rafalohaki** [WordOps/WordOps#580]
https://github.com/dragonflydb/dragonfly
Dragonfly
Fully compatible with Redis and Memcached APIs, Dragonfly requires no code changes to adopt. Compared to legacy in-memory datastores, Dragonfly delivers 25X more throughput, higher cache hit rates with lower tail latency, and can run on up to 80% less resources for the same sized workload.

**Comment by rafalohaki** [comment]
oof

**Comment by janiosarmento** [comment]
If at least it had APT packages available... 

I would never install Docker on my servers only for a service that a) is not essential; and b) there are alternatives that do not require Docker to cleanly install and run.

**Comment by vikas5914** [comment]
Actually I am going to try this. We have dedicated server for Redis only so having docker for that server is not a issue for us. Lets see if it works well with Laravel.

**Comment by rafalohaki** [comment]
> If at least it had APT packages available...
> 
> I would never install Docker on my servers only for a service that a) is not essential; and b) there are alternatives that do not require Docker to cleanly install and run.

WordOps on docker would huge too

**Comment by vikas5914** [comment]
> > If at least it had APT packages available...
> > I would never install Docker on my servers only for a service that a) is not essential; and b) there are alternatives that do not require Docker to cleanly install and run.
> 
> WordOps on docker would be huge too, security reasons btw

The only reason WordOps got started because Easy Engine moved to Docker.

**Comment by rafalohaki** [comment]
feels like easy engine is abandoned and not as optimized as wordops. they even have Debian 7 and 8, Ubuntu 12.04, 14.04 and 16.04 in their requirements(not higher), thats why i asked about docker version. i didnt knew it started because of docker, sry.

**Comment by samkatakouzinos** [comment]
> If at least it had APT packages available...
> 
> I would never install Docker on my servers only for a service that a) is not essential; and b) there are alternatives that do not require Docker to cleanly install and run.

Well, it does have packages but not in apt so can go ahead without docker installation.
- https://github.com/dragonflydb/dragonfly/releases/tag/v1.13.0
- https://www.dragonflydb.io/docs/getting-started/binary
