### ISSUE TITLE
Was Ngxblocker removed from wordops?

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#583]
Hello,

When I run the command:

wo site update mysite.com --ngxblocker=off
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Cannot update mysite.com, Invalid Options

Was Ngxblocker removed from wordops?

**Comment by VirtuBox** [comment]
> Hello,
> 
> When I run the command:
> 
> wo site update mysite.com --ngxblocker=off Testing Nginx configuration [OK] Reloading Nginx [OK] Cannot update mysite.com, Invalid Options
> 
> Was Ngxblocker removed from wordops?

Hello @alexlii1971, no, it's look like a bug.

**Comment by andremacola** [comment]
Can't Install either

```bash
root@xxx /var/www$ wo stack install --ngxblocker                                                                                                                                                                                                      
Downloading ngxblocker           [Done]
Testing Nginx configuration     [KO]
```
