### ISSUE TITLE
Following #549 can we have a .mustache template for /etc/nginx/conf.d/force-ssl-?.com.conf 

### ISSUE THREAD

**Issue by JPaulMora** [WordOps/WordOps#587]
Thanks, this is the only thing missing to have a very customizable setup.

**Comment by VirtuBox** [comment]
Hello @JPaulMora,

yes sure.

**Comment by ajohnclark** [comment]
![image](https://github.com/WordOps/WordOps/assets/1261459/a2da8e43-281e-41a2-a3a7-3d2c3ce7cd4a)

Was this added in recent update? Seems to be causing issues here in latest update if so.

**Comment by janiosarmento** [comment]
I think it should be `{{domains}}` instead of `{domains}` (double brace, not single). I'm going to run some tests here to make sure, but if someone else can confirm this is the case, better.

**Comment by janiosarmento** [comment]
I can confirm the problem are the single braces in the template file.

**Comment by ajohnclark** [comment]
Command was "sudo -E wo site create ex.com --wpredis --php82 --letsencrypt=wildcard --dns=dns_cf --hsts --user=admin" if that helps too.

**Comment by janiosarmento** [comment]
I just created a pull request to fix this. Now it's up to @VirtuBox to accept it and create a maintenance release to address this bug.

**Comment by VirtuBox** [comment]
A new release will be available in the next few minutes. Thank you @janiosarmento for your PR.

**Comment by JPaulMora** [comment]
Thanks a lot, where should I put my ssl.mustache for this to work?

**Comment by janiosarmento** [comment]
You only have to update WordOps to latest version.
