### ISSUE TITLE
Third Party SSL?

### ISSUE THREAD

**Issue by Jonathan-Garber** [WordOps/WordOps#59]
Does WordOps allow third-part SSL certs? I am only seeing Let's Encrypt commands?

**Comment by VirtuBox** [comment]
Hello @Jonathan-Garber,
third-party SSL certs are allowed but have to be installed manually by creating the config file `ssl.conf` in `/var/www/yourdomain.tld/conf/nginx` with the following content : 

```nginx
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    ssl_certificate /path/to/your/cert/fullchain.pem;
    ssl_certificate_key     /path/to/your/cert/key.pem;
```

**Comment by Jonathan-Garber** [comment]
Similar to what I was doing in EE. I would do a self-signed cert, then just replace the files with my real cert.

**Comment by Jonathan-Garber** [comment]
The above directions were helpful. Here is my current configs. Everything appears to be working as expected. Do you see any issues here that I am not seeing?

**my.tld**
```
server {
    listen 80;
    listen [::]:80;
    server_name my.tld www.my.tld;
    return 301 https://my.tld$request_uri;
}

server{
    server_name my.tld;

    access_log /var/log/nginx/my.tld.access.log rt_cache_redis;
    error_log /var/log/nginx/my.tld.error.log;


    root /var/www/my.tld/htdocs;

    index index.php index.html index.htm;


    include  common/redis-php72.conf;

    include common/wpcommon-php72.conf;
    include common/locations-wo.conf;
    include /var/www/my.tld/conf/nginx/*.conf;

}
```

**ssl.conf**
```
listen 443 ssl http2;
listen [::]:443 ssl http2;
ssl_certificate /var/www/my.tld/ssl/116th.crt;
ssl_certificate_key /var/www/my.tld/ssl/116th.key;
ssl_stapling on;
ssl_stapling_verify on;
ssl_trusted_certificate /var/www/my.tld/ssl/116th-ca.crt;
```

**Comment by VirtuBox** [comment]
Hello,
everything seems to be ok. But you should maybe use my.tld as well as www.my.tld in your server block listening on port 443, because in your example, https://www.my.tld will redirect to another vhost.

**Comment by Jonathan-Garber** [comment]
Ah, indeed. I overlooked that. Ive been heavily testing EasyEngine,
Webinoly, and WordOps for the past 5 days. Eyes are bit tired of looking at
the screen. Thanks for the information and assistance.
