### ISSUE TITLE
File has unexpected size 

### ISSUE THREAD

**Issue by Ethical-Cronos** [WordOps/WordOps#602]
I'm trying to make new installations and it seems to me that there is an error in all of them, I test in different environments and the same error continues

E: Failed to fetch http://provo-mirror.opensuse.org/repositories/home%3A/virtubox%3A/WordOps/Debian_11/amd64/nginx-custom_1.24.0-1ppa~stable_amd64.deb  File has unexpected size (679880 != 679896). Mirror sync in progress? [IP: 91.193.113.70 80]
   Hashes of expected file:
    - SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - SHA1:xxxxxxxxxxxxxxxxxxxxxxxxxxx [weak]
    - MD5Sum:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[weak]
    - Filesize:679896 [weak]

I tested on debian: 

- 10
- 11
- 12

**Comment by Ethical-Cronos** [comment]
not be obsolete

**Comment by vkartk** [comment]
```
$ tail /var/log/wo/wordops.log
Fetched 96.5 MB in 12s (7932 kB/s)
E: Failed to fetch http://mirror.aardsoft.fi/opensuse/repositories/home%3A/virtubox%3A/WordOps/Debian_12/amd64/nginx-custom_1.26.1-1ppa~stable_amd64.deb  File has unexpected size (741488 != 740948). Mirror sync in progress? [IP: 95.216.238.135 80]
   Hashes of expected file:
    - SHA256:3f398548be350b7630aee6dfd3caec323f2b45c15a55f66ad84537c2e841f2d7
    - SHA1:84f9add77f2dfb5fcadb878391ecb4c07aaaa67a [weak]
    - MD5Sum:a7458001b5f3a32efcbb85649cb38dd1 [weak]
    - Filesize:740948 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
2024-07-01 06:18:47,933 (INFO) wo : Oops Something went wrong!!
2024-07-01 06:18:47,933 (ERROR) wo : Check the WordOps log for more details `tail /var/log/wo/wordops.log` and please try again...
```

**Comment by vkartk** [comment]
@Ethical-Cronos  Workaround 

 Manually downloading the package using `wget` and then installing it with `dpkg`. 

1. **Download the package using wget**:
   ```bash
   wget http://mirror.aardsoft.fi/opensuse/repositories/home%3A/virtubox%3A/WordOps/Debian_12/amd64/nginx-custom_1.26.1-1ppa~stable_amd64.deb
   ```

2. **Install the package using dpkg**:
   ```bash
   sudo dpkg -i nginx-custom_1.26.1-1ppa~stable_amd64.deb
   ```

This approach bypasses the issue with the mismatched file size during the automatic download process. If you encounter any dependency issues while installing the package with `dpkg`, you can resolve them by running:
```bash
sudo apt-get install -f
```

This should fix any missing dependencies and complete the installation.

---

And then run

```bash
sudo wo stack install
```
