### ISSUE TITLE
Unable to update or install latest php

### ISSUE THREAD

**Issue by thrijith** [WordOps/WordOps#609]
This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

```
╰─➤ wo stack install --php83

Adding repository for PHP, please wait...
Whoops, something went wrong... [..]
Check the WordOps log for more details tail /var/log/wo/wordops.log and please try again...

╰─➤ tail /var/log/wo/wordops.log
2024-01-11 16:41:42,724 (DEBUG) wo.core.logging : Setting apt_packages variable for PHP 8.3
2024-01-11 16:41:44,084 (DEBUG) wo.core.logging : Calling pre_pref
2024-01-11 16:41:44,085 (DEBUG) wo.core.logging : Adding ppa for PHP
2024-01-11 16:41:44,085 (INFO) wo : Adding repository for PHP, please wait...
2024-01-11 16:41:44,086 (DEBUG) wo.core.logging : ppa_author = ondrej
2024-01-11 16:41:44,086 (DEBUG) wo.core.logging : ppa_package = php
2024-01-11 16:41:44,086 (DEBUG) wo.core.logging : ppa already added
2024-01-11 16:41:44,086 (INFO) wo : Updating apt-cache
2024-01-11 16:41:48,818 (INFO) wo : Whoops, something went wrong...
2024-01-11 16:41:48,819 (ERROR) wo : Check the WordOps log for more details tail /var/log/wo/wordops.log and please try again...
```

Reported in https://community.wordops.net/d/1967-unable-to-update-php-

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information

- [x] `lsb_release -a`

> No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

- [x] `wo info`

> NGINX (1.24.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1

PHP (7.2.30-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.17-1):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

PHP (7.4.12):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php74-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9174

MySQL (10.3.22-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             25
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [x] `nginx -V`

> nginx version: nginx/1.24.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.1d  10 Sep 2019

- [x] `wo -v`

> WordOps v3.19.1
Copyright (c) 2024 WordOps.

- [x] `wp cli info --allow-root`

> OS:	Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64
Shell:	/usr/bin/zsh
PHP binary:	/usr/bin/php7.4
PHP version:	7.4.12
php.ini used:	/etc/php/7.4/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
SQL modes:	STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/root
WP-CLI packages dir:	/root/.wp-cli/packages/
WP-CLI cache dir:	/root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.9.0

- [x] `curl -sL git.io/fjAp3 | sudo -E bash -`

https://transfer.vtbox.net/QJn0p3/wordops.txt

**Comment by VirtuBox** [comment]
Hello @thrijith,
Ubuntu 18.04 LTS is EOL (End Of Life) and not supported anymore because PHP repositories are only available for active/supported Debian/Ubuntu releases. Even manually, you will not be able to install PHP 8.3 anymore : https://endoflife.date/ubuntu

I highly recommend you to setup a new server with Ubuntu 22.04 LTS and to migrate your sites to avoid security issues.
