### ISSUE TITLE
Issue regarding logging sensitive information

### ISSUE THREAD

**Issue by nevercodecorrect** [WordOps/WordOps#610]
Hello,
While playing with the tool, I noticed that sensitive information like wordpress password will be logged which could be a potential security issue described in [CWE-200](https://cwe.mitre.org/data/definitions/200.html). The problematic code is located in [here](https://github.com/WordOps/WordOps/blob/ecf20192c7853925e2cb3f8c8378cd0d86ca0d62/wo/cli/plugins/site_backup.py#L259), I am wondering if this is an intended behavior.

**Comment by VirtuBox** [comment]
Hello @nevercodecorrect,
I agree the python classes name are not really good, but in this example, `Log.info` will display credentials to the user but with `log=False` to not keep those credentials in `/var/log/wo/wordops.log`.
Let me know if it's still a security issue.
