### ISSUE TITLE
Nginx -t gives me errors and website is crashing

### ISSUE THREAD

**Issue by saitarunsareddy** [WordOps/WordOps#616]
nginx -t
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2024/02/01 08:09:58 [warn] 53484#53484: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2024/02/01 08:09:58 [emerg] 53484#53484: open() "/etc/nginx/conf.d/botblocker-nginx-settings.conf" failed (13: Permission denied) in /etc/nginx/nginx.conf:101
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by vikas5914** [comment]
@saitarunsareddy Are you doing this using the root user?
