### ISSUE TITLE
Failed create site on Digitalocean

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#622]
Hello,

On new server, and fresh installation, we encouter the following errors:

root@Test:~# export DO_API_KEY="dop_v1_735635f218d564ef66e74e0a788f3ba698f1f92073dd025557ae6ae26393e67884"
root@Test:~# sudo -E wo site create mysite.net --wpsubdomain --wpfc --php82 --ngxblocker --letsencrypt=wildcard --dns=dns_dgon

Running pre-update checks       [OK]
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/site_create.py", line 399, in default
    wo_wp_creds = setupwordpress(self, data, vhostonly)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/site_functions.py", line 288, in setupwordpress
    data = setupdatabase(self, data)
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/site_functions.py", line 200, in setupdatabase
    WOMysql.execute(self, "create database `{0}`"
  File "/opt/wo/lib/python3.10/site-packages/wo/core/mysql.py", line 71, in execute
    connection = WOMysql.connect(self)
  File "/opt/wo/lib/python3.10/site-packages/wo/core/mysql.py", line 37, in connect
    connection = pymysql.connect(read_default_file='~/.my.cnf')
  File "/opt/wo/lib/python3.10/site-packages/pymysql/connections.py", line 358, in __init__
    self.connect()
  File "/opt/wo/lib/python3.10/site-packages/pymysql/connections.py", line 664, in connect
    self._request_authentication()
  File "/opt/wo/lib/python3.10/site-packages/pymysql/connections.py", line 954, in _request_authentication
    auth_packet = self._read_packet()
  File "/opt/wo/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/opt/wo/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/wo/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1698, "Access denied for user 'root'@'localhost'")

- [ ] `lsb_release -a`
root@Test:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

- [ ] `wo info`
wo info

NGINX (1.24.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1 
PHP 7.2 is not installed
Traceback (most recent call last):
  File "/usr/local/bin/wo", line 8, in <module>
    sys.exit(main())
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/main.py", line 102, in main
    app.run()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/info.py", line 664, in default
    self.info_php73()
  File "/opt/wo/lib/python3.10/site-packages/wo/cli/plugins/info.py", line 181, in info_php73
    www_ping_path = wconfig['ping.path']
  File "/usr/lib/python3.10/configparser.py", line 1259, in __getitem__
    raise KeyError(key)
KeyError: 'ping.path'

- [ ] `nginx -V`
root@Test:~# nginx -V
nginx version: nginx/1.24.0 (WordOps Nginx-wo)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-YgM00t/nginx-1.24.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-echo --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/memc-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/HttpRedisModule --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-module-vts --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_brotli

- [ ] `wo -v`

root@Test:~# wo -v
WordOps v3.19.1
Copyright (c) 2024 WordOps.
- [ ] `wp cli info --allow-root`

root@Test:~# wp cli info --allow-root
OS:     Linux 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.3
PHP version:    8.3.3-1+ubuntu22.04.1+deb.sury.org+1
php.ini used:   /etc/php/8.3/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.11.7-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

SQL modes:      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.10.0

- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

root@Test:~# curl -sL git.io/fjAp3 | sudo -E bash -

Here the link to provide in your github issue : https://transfer.vtbox.net/blXmR6/wordops.txt

**Comment by alexlii1971** [comment]
However, I tried the following way, and it succeced:


git clone https://github.com/WordOps/WordOps.git
cd WordOps/
sudo bash install


then, cd..

then, run:
DO_API_KEY="dop_v1_735635f218d564ef66e74e0a788f3ba698f1f92073dd025557ae6ae26393e67884"
root@Test:# sudo -E wo site create mysite.net --wpsubdomain --wpfc --php82 --ngxblocker --letsencrypt=wildcard --dns=dns_dgon

**Comment by alexlii1971** [comment]
wo site delete mysite.net --force

then reinstall by remove --ngxblocker

root@Test:~# export DO_API_KEY="dop_v1_735635f218d564f6674e0a7838f3ba698f1f92073dd025557ae6ae26393e67884"
root@Test:~# sudo -E wo site create mysite.net --wpsubdomain --wpfc --php82 --letsencrypt=wildcard --dns=dns_dgon

Same issue

**Comment by alexlii1971** [comment]
tried various way, ALL failed, and even the following one:

root@Test:~# export DO_API_KEY="dop_v1_735635f218d564f6674e0a7838f3ba698f1f92073dd025557ae6ae26393e67884"
root@Test:~# sudo -E wo site create mysite.net --wp --letsencrypt=wildcard --dns=dns_dgon
Running pre-update checks       [OK]
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             [Done]
Configuring WordPress           [OK]
Installing WordPress            [OK]
Installing plugin nginx-helper  [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
WordPress admin user : alex
WordPress admin password : gBx1C34a8z2W43oldSV0PLUAGIsF
Successfully created site http://inlady.net
Certificate type : wildcard
Validation mode : DNS mode with dns_dgon
Issuing SSL cert with acme.sh   [OK]
Deploying SSL cert              [OK]
Securing WordOps backend with current cert
Adding HTTPS redirection        [OK]
Updating site url with https    [OK]
Testing Nginx configuration     [OK]
Reloading Nginx                 [OK]
Congratulations! Successfully Configured SSL on https://mysite.net
root@Test:~# 
root@Test:~# 
root@Test:~# wo clean --all
Cleaning NGINX FastCGI cache
Testing Nginx configuration     [OK]
Restarting Nginx                [OK]
Cleaning opcache
Cleaning Redis cache

**Comment by psfnet** [comment]
Having the same problem on VPS Contabo Debian 12.
Attempts on Debian 11, 12 and Ubuntu 22.04 lts.
Is it possible to use an earlier version of Wordops?

**Comment by kingkool68** [comment]
I get this error when I run `sudo wo site create test-server.local --php`

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='v4.wordops.eu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff9f5cb340>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

It looks like https://v4.wordops.eu/ refuses to connect just like https://wordops.net/. I guess we need @VirtuBox to fix those sites before WordOps starts working again.

**Comment by alexlii1971** [comment]
Yes, the website url is not reachable at https://wordops.net/

server_ip = requests.get('http://v4.wordops.eu/')

According to the log, it is not reachable...

Unfortuantely, there is no response from @VirtuBox by now.

**Comment by VirtuBox** [comment]
Issue has been fixed, sorry for the delay
