### ISSUE TITLE
variables_hash_max_size and variables_hash_bucket_size missing?

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#629]
Hello,

We got the following errors on server log:

2024/04/03 07:59:30 [warn] 15212#15212: could not build optimal variables_hash, you should increase either variables_hash_max_size: 1024 or variables_hash_bucket_size: 64; ignoring variables_hash_bucket_size

I checked Nignx conf, and also checked by Nginx -T, there are no both variables_hash_max_size and variables_hash_bucket_size.

Or, maybe there is some custom conf somewhere, or those two value missing?

If yes, how should I set these two value please?

Thanks

**Comment by VirtuBox** [comment]
Hello @alexlii1971, 
can you check if there is a file /etc/nginx/conf.d/variables-hash.conf ?

**Comment by alexlii1971** [comment]
Sorry for later response, yes, it show:

  GNU nano 6.2       /etc/nginx/conf.d/variables-hash.conf                 
variables_hash_max_size 8192;
variables_hash_bucket_size 4096;
