### ISSUE TITLE
Question upon query cache

### ISSUE THREAD

**Issue by alexlii1971** [WordOps/WordOps#631]
Hello,

Here is the Mysql version:

mysql -V
mysql  Ver 15.1 Distrib 10.6.17-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

and 

The query cache is deprecated as of MySQL 5.7.20 and has been removed since MySQL 8.0, and it seems that it officially suggest using innodb_buffer_pool_size but not query_cache.

However, I still see query_cache in conf file.

Any comments please?

Thanks

**Comment by VirtuBox** [comment]
Hello @alexlii1971,
WordOps do not install MySQL but MariaDB instead, and MariaDB still support this feature.
Anyway in WordOps, query_cache and query_cache_size are set to `0` to disable this feature.
If you want to learn more about why we are disabling it : https://mysqlquicksand.wordpress.com/2020/05/08/10-reasons-why-mysql-query-cache-should-be-switched-off/
