### ISSUE TITLE
Nginx keep crashing after updated wordops to v3.20.0

### ISSUE THREAD

**Issue by dutuka** [WordOps/WordOps#636]
Hello,
after updating wordops to v3.20.0 Nginx keeps crashing every 2 minutes. I check nginx error.log and found these alerts:

`2024/04/22 20:21:59 [alert] 14851#14851: *13 open socket #52 left in connection 9
2024/04/22 20:21:59 [alert] 14851#14851: aborting
2024/04/22 20:24:37 [error] 15433#15433: *23 directory index of "/var/www/22222/htdocs/" is forbidden, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "127.0.0.1"`

Thanks for any help.

This issue tracker is only for issues directly related to WordOps.
Please use <https://community.wordops.net> for support questions.

If you feel the issue is a WordOps specific issue, please attach the output of the following commands.

System Information
- nginx error.log
`2024/04/22 20:21:59 [alert] 14851#14851: *13 open socket #52 left in connection 9
2024/04/22 20:21:59 [alert] 14851#14851: aborting
2024/04/22 20:24:37 [error] 15433#15433: *23 directory index of "/var/www/22222/htdocs/" is forbidden, client: 127.0.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", host: "127.0.0.1"`
- [ ] `lsb_release -a`
`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
`
- [ ] `wo info`
`NGINX (1.24.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 ::1
PHP 7.2 is not installed

PHP (8.2.18):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php82-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9182

PHP (8.3.6):

user
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php83-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9183

MySQL (10.6.17-MariaDB) on localhost:

port                             3306
wait_timeout                     60
interactive_timeout              28800
max_used_connections             6
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf
`
- [ ] `nginx -V`
`nginx version: nginx/1.24.0 (WordOps Nginx-wo)
built with OpenSSL 3.0.2 15 Mar 2022
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -ffile-prefix-map=/build/nginx-YgM00t/nginx-1.24.0=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fPIC -flto -ffat-lto-objects -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -fPIC -flto -ffat-lto-objects' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-openssl-opt='zlib enable-ec_nistp_64_gcc_128 enable-tls1_3 no-ssl3-method -fPIC' --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_sub_module --with-http_xslt_module --without-http_memcached_module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/headers-more-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-cache-purge --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-echo --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_http_substitutions_filter_module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/memc-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/srcache-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/HttpRedisModule --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/redis2-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_devel_kit --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/set-misc-nginx-module --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/nginx-module-vts --add-module=/build/nginx-YgM00t/nginx-1.24.0/debian/modules/ngx_brotli
`
- [ ] `wo -v`
`WordOps v3.20.0`
- [ ] `wp cli info --allow-root`
`OS:     Linux 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64
Shell:  /usr/sbin/nologin
PHP binary:     /usr/bin/php8.3
PHP version:    8.3.6
php.ini used:   /etc/php/8.3/cli/php.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.6.17-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:    /var/www/.wp-cli/packages/
WP-CLI cache dir:       /var/www/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.10.0
`
- [ ] `curl -sL git.io/fjAp3 | sudo -E bash -`

**Comment by dutuka** [comment]
I restore my server from a backup with wordops v3.19.1 running and nginx works without issue. Wordops v3.20.0 causes nginx crashing with error: *13 open socket #52 left in connection 9, at least on my server.

**Comment by servicepipe** [comment]
![screenshot-24](https://github.com/WordOps/WordOps/assets/83685365/e4e9faef-a70f-40af-a986-d53601615f4f)

wordops.log

![screenshot-25](https://github.com/WordOps/WordOps/assets/83685365/c1fb8789-8078-40bf-b62e-fbb293927e58)
