### ISSUE TITLE
Please fix issue: Query parameters missing when caching with wpsc

### ISSUE THREAD

**Issue by viidev25** [WordOps/WordOps#639]
Hello,

From this closed issue: https://github.com/WordOps/WordOps/issues/267

It still not fixed in recent release version. It will make Woocommerce break when load report page, also wp-json can not process parameter.

$ more /etc/nginx/common/wpsc-php82.conf 

location / {
  try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php;
}

==> please change  try_files /wp-content/cache/supercache/$http_host/$cache_uri/index.html $uri $uri/ /index.php; 

to

try_files /wp-content/cache/supercache/$http_host/$cache_uri/index${mobile_prefix}${https_prefix}.html /wp-content/cache/supercache/$http_host/$cache_uri/index${https_prefix}.html $uri $uri/ /index.php$is_args$args;

**Comment by VirtuBox** [comment]
Issue has been fixed in the last release.

Please update WordOps with the command `wo update`
