### ISSUE TITLE
very resourceful

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#64]
Using DigitalOcean server and vultr.com from 1cpu / 1gb ram- ubuntu 18.04lts.
wordOps consumes enough resource to get the server crashing.
the installation time is much longer, until the moment of print installing nginx-ee was already in 35 minutes.

[image](https://uploaddeimagens.com.br/imagens/recurso-png-7680986c-912a-48c2-9384-df87c5be4b83)

running travis-ci the installation took place well in 14 minutes.

**Comment by VirtuBox** [comment]
Hello @juanpvh,
I will investigate on this issue, but on our side travis-ci do not take longer than 8 minutes to install all WordOps stacks and to create 26 sites : https://travis-ci.org/WordOps/WordOps/builds/522008143
