### ISSUE TITLE
Http2.pro error: "ALPN: No ALPN, No NPN"

### ISSUE THREAD

**Issue by jazir555** [WordOps/WordOps#640]
https://http2.pro/

"ALPN: No ALPN, No NPN
This server does not support any of the protocol negotiation methods. Unless the client explicitly makes an HTTP/2 request, HTTP/2 will not be used by default, and may require additional round trips."

Http2 is enabled via WordOPs, but due to to the lack of the inclusion of these protocol negotiation methods http2 is not actually being used? Additional roundtrips would mean additional unnecessary network latency. Is this something you can fix @VirtuBox?

**Comment by VirtuBox** [comment]
Hello @jazir555,
I'm not sure this tool is working properly because I haven't be able to have ALPN enabled on any site.

**Comment by VirtuBox** [comment]
https://tools.keycdn.com/http2-test seems to work properly
