### ISSUE TITLE
problems with codes/commads 

### ISSUE THREAD

**Issue by Thiagobrazilian** [WordOps/WordOps#642]
![print 16](https://github.com/WordOps/WordOps/assets/168855216/b2891be4-c5e2-4a99-9f84-98499b685716)

these commands not being recognized by prompt commad and putty. Could someone help me please?

**Comment by rickyhewitt** [comment]
Hi!

If you could paste the output of these commands, it may help to gather further information:

1. `which wo`
2. `cat /var/log/wo/install.log`

**Comment by VirtuBox** [comment]
Hello @Thiagobrazilian,
there is something wrong with your WordOps install. It's seems WordOps is not installed at all.
