### ISSUE TITLE
Weird 301 redirection to my old domain

### ISSUE THREAD

**Issue by allenvino1** [WordOps/WordOps#652]
I Changed my domain using the steps here https://github.com/WordOps/WordOps/issues/199. But after the change im having a weird 301 redirect to my old domain. 

What i did already
- Cleaned and removed cache
- used wp to update db to new url
- disabled all plugins

![image](https://github.com/WordOps/WordOps/assets/17024847/d36654f8-149a-479d-8ed8-e23f8eb4ef2b)

**Comment by allenvino1** [comment]
Im guessing this has something todo with x-redirect-by?

**Comment by VirtuBox** [comment]
Hello @allenvino1, 
Yes the header `x-redirected-by: WordPress` mean it's a WordPress redirection. 
What is the output of the following commands ? 

```shell
wp option get home
wp option get siteurl
```

Is your WordPress a multisite ?

**Comment by allenvino1** [comment]
@VirtuBox thanks for the response! I was able to resolve it problem with wp search and replace
