### ISSUE TITLE
error creating site

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#66]
when trying to create a new site this error happens

root@server-vultr:~ wo site create domain.tld --wpfc --user=manager --le
Adding repository for MySQL, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
**Reload : mysql     [Failed]**
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
**Setting up database             (1045, "Access denied for user 'root'@'::1' (using password: YES)")**
root@server-vultr:~

**Comment by VirtuBox** [comment]
Hello,
I have just run the same command to investigate on this issue but I wasn't able to reproduce it : 

```bash
wo site create site.tld --wpfc --user=manager --le
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
Updating apt-cache, please wait...
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Reload : nginx     [OK]
Restart : php7.2-fpm[OK]
Reload : mysql     [OK]
Running pre-update checks, please wait...
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading WordPress           [Done]
Setting up database             [Done]
Installing plugin nginx-helper, please wait...
Setting plugin nginx-helper, please wait...
Reload : nginx     [OK]
HTTP Auth User Name: WordOps
HTTP Auth Password : UMUUvh
WordPress admin user : manager
WordPress admin user password : GVUky4z6Sxo08JN
Successfully created site http://site.tld
Issuing SSL cert with acme.sh
Deploying SSL cert with acme.sh
Adding /var/www/site.tld/conf/nginx/ssl.conf
Adding /etc/nginx/conf.d/force-ssl-site.tld.conf
Added HTTPS Force Redirection for Site  http://site.tld
```
