### ISSUE TITLE
sudo wo/ee update: unable to download file, /tmp/woupdate20181205-200344

### ISSUE THREAD

**Issue by demyxco** [WordOps/WordOps#7]
Can't run update script,  no other errors. Migrated from EEv3.

**Comment by jeroenops** [comment]
For now, could you please run the installer to get the updated versions? We'll have the update functionality resolved this week.

**Comment by VirtuBox** [comment]
Issue has been fixed with PR https://github.com/WordOps/WordOps/pull/25
