### ISSUE TITLE
Error executing / usr / local / bin / wo stack install --all

### ISSUE THREAD

**Issue by juanpvh** [WordOps/WordOps#71]
I noticed that the error is in the repository key

root @ vultr: ~ # / usr / local / bin / wo stack install --all
WP-CLI is already installed
Adding repository for MySQL, please wait ...
Adding repository for NGINX, please wait ...
Adding repository for PHP, please wait ...
Updating apt-cache, please wait ...
Fixing missing GPG keys, please wait ...
Whoops, something went wrong ...
Check the WordOps log for more details `tail / var / log / wo / wordops.log` and please try again ...
root @ vultr: ~ # tail /var/log/wo/wordops.log
Get: 6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get: 7 http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04 Release [1,004 B]
Get: 8 http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04 Release.gpg [481 B]
Ign: 8 http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04 Release.gpg
Get: 9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists ...
W: GPG error: http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04 Release: No_PUBKEY 188C9FB063F0247A
E: The repository 'http://download.opensuse.org/repositories/home:/virtubox:/WordOps/xUbuntu_18.04 Release' is not signed.
2019-05-04 14: 12: 45,292 (INFO) wo: Whoops, something went wrong ...
2019-05-04 14: 12: 45,293 (ERROR) wo: Check the WordOps log for more details `tail / var / log / wo / wordops.log` and please try again ...
root @ vultr: ~ #

Some help?

error related to flag --all
wo stack install works perfectly

**Comment by VirtuBox** [comment]
Hello @juanpvh,

it seems to be a specific issue with vultr ubuntu template, because I have just performed `wo stack install --all` on a fresh ubuntu 18.04 VM and there were no issues related to the repository gpg key. 
I will investigate on this issue

**Comment by marciomarim** [comment]
Just an input, I dont think it is specific to Vultr Ubuntu, I have 2 instances running WO with no errors on Vultr with Ubuntu 18.04.

**Comment by VirtuBox** [comment]
> Just an input, I dont think it is specific to Vultr Ubuntu, I have 2 instances running WO with no errors on Vultr with Ubuntu 18.04.

Thanks for your input
