### ISSUE TITLE
Issue with adminer

### ISSUE THREAD

**Issue by ageng** [WordOps/WordOps#72]
Hello,

I think website adminer error SSL certificate

![image](https://user-images.githubusercontent.com/2739992/57494603-48c57e80-72f4-11e9-89b7-05b465f58f98.png)

So I can't install adminer when I use command `sudo wo stack install --all`

```
PHP 7.2 already installed
MySQL connection is already alive
WP-CLI is already installed
Downloading phpMyAdmin           [Done]
Downloading Composer             [Done]
Downloading Adminer              Unable to download file, /var/www/22222/htdocs/db/adminer/index.php
```

Any alternative not download from adminer website? example from adminer [github repository](https://github.com/vrana/adminer).

Thanks.

**Comment by VirtuBox** [comment]
Hello,
thanks for your report, I'm going to open a pull request to fix this issue.

**Comment by VirtuBox** [comment]
Issue has been fixed with the PR https://github.com/WordOps/WordOps/pull/73.
Just run `wo update` to apply the fix
