### ISSUE TITLE
Setting up database access denied

### ISSUE THREAD

**Issue by cyberfly** [WordOps/WordOps#75]
Hi when using wo site create, I faced this error Access denied when setting up database.

```
sudo -i
wo site create kerismalela.com --mysql
Running pre-update checks, please wait...
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Setting up database		(1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

Previously works like a charm, but now I am facing this problem. How to solve this?

Thanks

**Comment by ggloveswp** [comment]
Seems like an unrelated issue to WO. 
Could you please try a clean install on your OS and retry? 
Do not install MySQL or anything on your own. Initial WO setup will take care of them in auto-pilot.
