### ISSUE TITLE
silent install with parameters

### ISSUE THREAD

**Issue by devbhosale** [WordOps/WordOps#79]
WordOps installer has at least three user prompts ( do you want to upgrade, git user.name, and user.email if .gitconfig is not configured)
Can parameters be passed to installer or values taken from environment variables so that WordOps can be easily installed with DevOp tools such as Ansible silently?

**Comment by juanpvh** [comment]
you can pass this command before installing WordOps for background installation

bash -c 'echo -e "[user]\n\tname = $USER\n\temail = $USER@$HOSTNAME" > $HOME/.gitconfig'

can change $USER and $HOSTNAME

**Comment by devbhosale** [comment]
I can consider PR if environment variables such as WO_FORCE_UPDATE WO_GIT_USERNAME WO_GIT_USERMAIL sound acceptable?

**Comment by VirtuBox** [comment]
Hello @devbhosale, 
that's a good idea. I haven't used Ansible with WordOps yet, but that's always useful to provide a non-interactive way to perform install/upgrade.

**Comment by VirtuBox** [comment]
Feature added in the [latest release](https://github.com/WordOps/WordOps/releases/latest).
