### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by goran72** [WordOps/WordOps#8]
Hi!
I tried to install however got this:

wget -qO wo wordops.se/tup && sudo bash wo

Updating apt-get repository info
Installing depedencies
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package pigz
[ Thu Dec  6 14:04:46 UTC 2018 ] There was an error during dependency installation, exit status  1
Installing WordOps
Downloading WordOps straight from GitHub - fresh and brewed with love. Hold your horses...
The moment you've all been waiting for, time to install WordOps!
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
[ Thu Dec  6 14:04:48 UTC 2018 ] An error was encountered during the installation, exit status  1
Running post-install steps
chown: cannot access '/var/lib/wo/': No such file or directory
chmod: cannot access '/var/lib/wo/': No such file or directory
wo: line 654: cd: /etc/wo: No such file or directory
wo: line 705: wo: command not found

For WordOps (wo) auto completion, run the following command

source /etc/bash_completion.d/wo_auto.rc

Yay! WordOps (wo) installed/updated successfully
WordOps (wo) help: https://wordops.org/docs

**Comment by goran72** [comment]
Solved it, I did't have the universe repository added to my sources.list

**Comment by jeroenops** [comment]
Thank you for your feedback. I'll take this into account in upcoming versions - to check whether the universe repo is added and enabled.
