### ISSUE TITLE
Remote DB CLI arguments for "site create"

### ISSUE THREAD

**Issue by datawithdev** [WordOps/WordOps#89]
I did not see CLI parameters for remote "db-host", "db-user", "db-password", "wp-table-prefix".

Do these options exist anywhere?

Use Case:
I recently migrated some sites which are using remote database and db table prefix and later ended up modifying wp-config file generated by "WordOps". Will "WordOps" internal SQLite database be out of sync with these kind of changes?

It will be fanstastic to have these flags available with the CLI.

**Comment by AbileneAce** [comment]
I'm also trying to setup WordOps (Ubuntu 18.04) with DB on a remote server. Any advice would be appreciated.

**Comment by kingkool68** [comment]
There is a guide in the WordOps docs for using a remote MySQL Server with WordOps https://docs.wordops.net/how-to/remote-mysql-server/
