### ISSUE TITLE
Nginx stuck after load average reaches to number of CPU.

### ISSUE THREAD

**Issue by ankitsnlq** [WordOps/WordOps#90]
Facing issue with Nginx. As soon as load average on server reaches the number of CPU on a server, Nginx stops responding sites hosted on the server gives timeout error. I need to restart Nginx process for sites to be working. Facing issue with two servers running on digitalocean. 

First one has VCPU 1 and if load average becomes 1 Nginx stops responding. Another server has 2 vCPU and when load average is 2 Nginx stops responding and requires a restart.

System Information

- [ ] lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

- [ ] wo info
NGINX (1.16.0 ):

user                             www-data
worker_processes                 auto
worker_connections               50000
keepalive_timeout                8
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (7.2.19-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php72-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9172

PHP (7.3.6-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           php73-fpm.sock

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  1500
pm.max_children                  50
pm.start_servers                 10
pm.min_spare_servers             5
pm.max_spare_servers             15
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9173

MySQL (10.3.15-MariaDB) on localhost:

port                             3306
wait_timeout                     600
interactive_timeout              28800
max_used_connections             74
datadir                          /var/lib/mysql/
socket                           /var/run/mysqld/mysqld.sock
my.cnf [PATH]                    /etc/mysql/conf.d/my.cnf

- [ ] nginx -V
nginx version: nginx/1.16.0 (WordOps Nginx-wo)
built with OpenSSL 1.1.0g  2 Nov 2017 (running with OpenSSL 1.1.1c  28 May 2019)
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/src/packages/BUILD=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --build='WordOps Nginx-wo' --with-debug --with-pcre-jit --with-file-aio --with-threads --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --add-module=/usr/src/packages/BUILD/debian/modules/headers-more-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-auth-pam --add-module=/usr/src/packages/BUILD/debian/modules/nginx-cache-purge --add-module=/usr/src/packages/BUILD/debian/modules/nginx-echo --add-module=/usr/src/packages/BUILD/debian/modules/nginx-upstream-fair --add-module=/usr/src/packages/BUILD/debian/modules/ngx_http_substitutions_filter_module --add-module=/usr/src/packages/BUILD/debian/modules/memc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/srcache-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/HttpRedisModule --add-module=/usr/src/packages/BUILD/debian/modules/redis2-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/ngx_devel_kit --add-module=/usr/src/packages/BUILD/debian/modules/set-misc-nginx-module --add-module=/usr/src/packages/BUILD/debian/modules/nginx-module-vts --add-module=/usr/src/packages/BUILD/debian/modules/ngx_brotli

- [ ] wo -v
WordOps v3.9.5
Copyright (c) 2019 WordOps.

- [ ] wp cli info --allow-root
OS:	Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64
Shell:	/bin/bash
PHP binary:	/usr/bin/php7.3
PHP version:	7.3.6-1+ubuntu18.04.1+deb.sury.org+1
php.ini used:	/etc/php/7.3/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/var/log/nginx
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.2.0

**Comment by ankitsnlq** [comment]
This issue is due to brotli. For now I have disabled brotli from nginx.conf.

**Comment by fabineves** [comment]
Having the same issue here. Is there a fix, instead of disabling brotli?

**Comment by VirtuBox** [comment]
A new Nginx package is available on Ubuntu with TLS v1.3 support and Brotli updated to v1.0.7 👍 
https://launchpad.net/~wordops/+archive/ubuntu/nginx-wo

How to upgrade ?

```bash
sudo add-apt-repository ppa:wordops/nginx-wo -y -u
wo maintenance
```

**Comment by nsgoyat** [comment]
Hey Matt,
The website is ready at  https://partners.bizzloans.co.nz

These are the logins:
user=Agent47Hoeut
pass=Rand0mp@sto50s

**Comment by nsgoyat** [comment]
Hey VirtuBox,
Thanks for the update. How to compile it using Nginx-EE Script. Will we automatically get this updated version?

**Comment by VirtuBox** [comment]
Hello @nsgoyat, 
The new Nginx package will be automatically installed during WordOps upgrade. I have also updated my script Nginx-ee yesterday

**Comment by juanpvh** [comment]
@virtubox qual o beneficio ainda em instalar o nginx-e com wordOps?

**Comment by VirtuBox** [comment]
@juanpvh, each time I build a new nginx package for WordOps, there are less benefits of installing nginx-ee. However, there are some modules only available with nginx-ee like Naxsi WAF, Ngx_Pagespeed, RTMP and the choice betwwen LibreSSL and OpenSSL.

**Comment by ankitsnlq** [comment]
Hi @VirtuBox, 

I guess the latest version also has the same issue. I faced an issue on fresh installation yesterday. Any Plan to disable brotli until we have a proper solution?

Regards,

**Comment by nsgoyat** [comment]
Yes, the Nginx Brotli Compilation should be either optional or completely removed until the 100% CPU issue is fixed. I was the first to report this issue at EEv3 Community Forum and the issue is still going on...

**Comment by VirtuBox** [comment]
I have updated nginx.conf for the next release and added a list of well compressible MIME types to compress with Brotli, instead of the current directive `brotli_types *;`. I hope this will mitigate the issues with high CPU usage. 
Otherwise, Brotli will be disabled by default.

**Comment by ankitsnlq** [comment]
Hi @VirtuBox,

Thank you very much man! Let's hope for the best in next release.

Regards,

**Comment by VirtuBox** [comment]
I have published a new Nginx package built with libbrotli from system lib instead of compiling it from source. Let me know if it decrease Nginx resources usage.

**Comment by VirtuBox** [comment]
Currently, Nginx package is the same on Ubuntu 16.04 LTS, I haven't managed to backport the last libbrotli release yet

**Comment by ankitsnlq** [comment]
Ok @VirtuBox  will upgrade some other server. Let you know if we face issue again.
