### ISSUE TITLE
WordOPS Community (Forum) Certificate Expired!

### ISSUE THREAD

**Issue by nsgoyat** [WordOps/WordOps#91]
It seems the SSL Certificate protecting https://community.wordops.io has been expired. Due to the HSTS Policy, one can't even access the site by ignoring the warning. Please, look into it.
Thanks

**Comment by VirtuBox** [comment]
Hello @nsgoyat, 
issue has been fixed, sorry for this mistake, but after too many WordOps install on this server, there were few errors in acme.sh configuration.
