### ISSUE TITLE
Add apache for once sites

### ISSUE THREAD

**Issue by HomaEEE** [WordOps/WordOps#93]
hello, can i add apache for frontend? some site need .htaccess

**Comment by VirtuBox** [comment]
Hello @HomaEEE, 

yes, it's possible to add Apache with Nginx as reverse-proxy. 
You should find the most part of informations in this tutorial : https://www.howtoforge.com/tutorial/how-to-install-nginx-as-reverse-proxy-for-apache-on-ubuntu-16-04/
