### ISSUE TITLE
x-srcache-fetch-status is always set to BYPASS

### ISSUE THREAD

**Issue by Dereksmith590** [WordOps/WordOps#94]
Hi and thanks for this software - seems amazing and hands-solving solution.

I attended WC Europe and found George's workshop very interested, so I started applying WordOps onto a website I develop on my server.

Due to the needs of my project, I wanted to do some per-device caching and George shared some useful info, but he couldnt replicate my problem so he advised on raising a ticket here.

I've added the following to /etc/nginx/nginx.conf:

```
map $http_user_agent $device_type {
default "desktop";
~SymbianOS.*AppleWebKit "lowend";
~Opera\sMobi "mobile";
}
```

and also added --$device_type at the end of the key at nano /etc/nginx/common/redis-php73.conf:

`set $key "nginx-cache:$scheme$request_method$host$request_uri--$device_type";`

also added param here: /etc/nginx/fastcgi.conf
`fastcgi_param DEVICE_TYPE $device_type;`

I also set argument-based URLs to be cached with no skip_cache, because I have some ?amp pages i would like to cache.

After doing the above, I noticed that every single request returns 

x-srcache-fetch-status: BYPASS
x-srcache-store-status: BYPASS

So I need your help here.

If I do remove

`  srcache_fetch_skip $skip_cache;
  srcache_store_skip $skip_cache;
`

from /etc/nginx/common/redis-php73.conf - it works fine in hitting/missing/bypassing with both, but it seems that it caches my wp-admin login for every non logged in user.

**Comment by ggloveswp** [comment]
Just did a second installation and I wasnt able to replicate the issue.
Please have WO installed again, Im pretty sure that a installation from scratch wont end in a BYPASS/BYPASS case.
