### ISSUE TITLE
Redis full page caching & webp conditional image serving

### ISSUE THREAD

**Issue by Dereksmith590** [WordOps/WordOps#95]
Latest Pagespeed (Lighthouse) tool's update, suggests webp content type to be served onto supported browsers.

Since major browsers like Safari are not supporting webp yet, a conditional cached version is required both for webp supporting browsers and a second for non-webp supporting ones.

Are there any solutions for this problem yet? If a page is cached from a webp supporting browser, non-webp browsers will see this cached version aswell.

**Comment by ggloveswp** [comment]
Mapping useragent in nginx an appending the variable to cache key, after conditionally checking the variable, might do the trick.
IE: 
```
map $http_user_agent $nowebpsupport {
    default                          0;
    "~MSIE"                        1;
    "~IEMobile"                  1;
    "~Safari"                       1;
}
```

But Im sure that there could be better solutions instead of having a different cache key for each user agent. @VirtuBox or @jeroenlaylo might have better answers for this.

**Comment by VirtuBox** [comment]
Hello @Dereksmith590, 

WebP images support is already implemented in WordOps : 
- WebP mapping with Nginx : https://github.com/WordOps/WordOps/blob/ad9505482a380d3433c642dad4e2cdb64bf4ca7e/wo/cli/templates/webp.mustache#L1
- Conditional try_files with Nginx : https://github.com/WordOps/WordOps/blob/ad9505482a380d3433c642dad4e2cdb64bf4ca7e/wo/cli/templates/wpcommon.mustache#L28

It work properly with full page caching, as we are not serving images with the .webp extension, but directly with their original extension and the proper content-type header depending on the browser request headers.

**Comment by andremacola** [comment]
This configuration do not work with Cloudflare.

You can use the approach below to customize the thumbnail output.

Recommend to use some plugin like EWWW Image optimizer

```
<picture class=''>
	<source type='image/webp' srcset='image.webp'>
	<img src='image.jpg' title='' alt='' class=''> 
</picture>
```

**Comment by rsmith4321** [comment]
I think it's great that the webp is served if the image is available. However this will cause serious problems if someone is using cloudflare or any kind of cdn. The cdn will cache the webp version of the .jpeg and serve it to non compatible browsers. So I don't know if this should be on by default, it should be an installation choice.

**Comment by nsgoyat** [comment]
@rsmith4321 It's just the .Webp Conditional Support that is added on the server level. This feature doesn't generate the .webp versions of your images. You will need to generate WEBP images using a plugin.

**Comment by andremacola** [comment]
@VirtuBox  The webp.conf file needs to be optional. I have to disable to work with cloudflare.
Because the common configuration uses  `try_files $uri$webp_suffix $uri =404;` the nginx fail to start if we delete or comment the content from webp.conf.

**Comment by VirtuBox** [comment]
@andremacola I will add an additional directive to set webp_suffix variable empty if Cloudflare header is passed to Nginx
