### ISSUE TITLE
Ningx fails to start after updating to v3.9.5.3

### ISSUE THREAD

**Issue by Facer66** [WordOps/WordOps#96]
I updated to v3.9.5.3 but nginx stopped working after wo update with error:

duplicate location "/robots.txt" in /etc/nginx/common/locations-php73.conf:9

[wordops_info.txt](https://github.com/WordOps/WordOps/files/3347031/wordops_info.txt)

**Comment by VirtuBox** [comment]
Hello,

Please replace locations-php73.conf by locations-wo.conf in your Nginx vhosts.

Regards,

**Comment by Facer66** [comment]
replacing locations-php73.conf by locations-wo.conf in my Nginx vhosts **Worked!**

Thanks
